// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: api/market/v1/market.proto

// M02 行情与因子对内接口。桌面端经 admin 聚合访问，不直连本服务。
// 设计见 doc/开发文档/M02-行情与因子/设计文档.md 第 8 节。

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 复权方式。NONE：价格不复权，指标为每天当时看到的值；QFQ：前复权（以区间最后一天为基准）；HFQ：后复权。
type Adjust int32

const (
	Adjust_NONE Adjust = 0
	Adjust_QFQ  Adjust = 1
	Adjust_HFQ  Adjust = 2
)

// Enum value maps for Adjust.
var (
	Adjust_name = map[int32]string{
		0: "NONE",
		1: "QFQ",
		2: "HFQ",
	}
	Adjust_value = map[string]int32{
		"NONE": 0,
		"QFQ":  1,
		"HFQ":  2,
	}
)

func (x Adjust) Enum() *Adjust {
	p := new(Adjust)
	*p = x
	return p
}

func (x Adjust) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Adjust) Descriptor() protoreflect.EnumDescriptor {
	return file_api_market_v1_market_proto_enumTypes[0].Descriptor()
}

func (Adjust) Type() protoreflect.EnumType {
	return &file_api_market_v1_market_proto_enumTypes[0]
}

func (x Adjust) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Adjust.Descriptor instead.
func (Adjust) EnumDescriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{0}
}

type GetBarsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Symbol string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 1m 或 1d，默认 1d。
	Freq string `protobuf:"bytes,2,opt,name=freq,proto3" json:"freq,omitempty"`
	// RFC3339 或 2006-01-02，含两端。
	Start  string `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End    string `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Adjust Adjust `protobuf:"varint,5,opt,name=adjust,proto3,enum=api.market.v1.Adjust" json:"adjust,omitempty"`
	// 最多返回条数，默认 1000，上限 10000。从 end 往前取。
	Limit         int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarsRequest) Reset() {
	*x = GetBarsRequest{}
	mi := &file_api_market_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarsRequest) ProtoMessage() {}

func (x *GetBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarsRequest.ProtoReflect.Descriptor instead.
func (*GetBarsRequest) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *GetBarsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetBarsRequest) GetFreq() string {
	if x != nil {
		return x.Freq
	}
	return ""
}

func (x *GetBarsRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetBarsRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetBarsRequest) GetAdjust() Adjust {
	if x != nil {
		return x.Adjust
	}
	return Adjust_NONE
}

func (x *GetBarsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Bar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        int64                  `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	AdjFactor     float64                `protobuf:"fixed64,8,opt,name=adj_factor,json=adjFactor,proto3" json:"adj_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_api_market_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *Bar) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Bar) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Bar) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Bar) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Bar) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Bar) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Bar) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bar) GetAdjFactor() float64 {
	if x != nil {
		return x.AdjFactor
	}
	return 0
}

type GetBarsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Freq          string                 `protobuf:"bytes,2,opt,name=freq,proto3" json:"freq,omitempty"`
	Bars          []*Bar                 `protobuf:"bytes,3,rep,name=bars,proto3" json:"bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarsReply) Reset() {
	*x = GetBarsReply{}
	mi := &file_api_market_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarsReply) ProtoMessage() {}

func (x *GetBarsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarsReply.ProtoReflect.Descriptor instead.
func (*GetBarsReply) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *GetBarsReply) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetBarsReply) GetFreq() string {
	if x != nil {
		return x.Freq
	}
	return ""
}

func (x *GetBarsReply) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

type GetIndicatorsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Symbol string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Start  string                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End    string                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Adjust Adjust                 `protobuf:"varint,4,opt,name=adjust,proto3,enum=api.market.v1.Adjust" json:"adjust,omitempty"`
	// 只返回这些键，空为全部。
	Names         []string `protobuf:"bytes,5,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndicatorsRequest) Reset() {
	*x = GetIndicatorsRequest{}
	mi := &file_api_market_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndicatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndicatorsRequest) ProtoMessage() {}

func (x *GetIndicatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndicatorsRequest.ProtoReflect.Descriptor instead.
func (*GetIndicatorsRequest) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetIndicatorsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetIndicatorsRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetIndicatorsRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetIndicatorsRequest) GetAdjust() Adjust {
	if x != nil {
		return x.Adjust
	}
	return Adjust_NONE
}

func (x *GetIndicatorsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type IndicatorPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Values        map[string]float64     `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicatorPoint) Reset() {
	*x = IndicatorPoint{}
	mi := &file_api_market_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicatorPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorPoint) ProtoMessage() {}

func (x *IndicatorPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorPoint.ProtoReflect.Descriptor instead.
func (*IndicatorPoint) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *IndicatorPoint) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *IndicatorPoint) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetIndicatorsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Points        []*IndicatorPoint      `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndicatorsReply) Reset() {
	*x = GetIndicatorsReply{}
	mi := &file_api_market_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndicatorsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndicatorsReply) ProtoMessage() {}

func (x *GetIndicatorsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndicatorsReply.ProtoReflect.Descriptor instead.
func (*GetIndicatorsReply) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *GetIndicatorsReply) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetIndicatorsReply) GetPoints() []*IndicatorPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetFactorsCrossRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 2006-01-02，默认今天。
	TradeDate string `protobuf:"bytes,1,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	// RFC3339。为空取实时截面。
	AsOf string `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	// close / intraday / auction / capital，为空不限。
	Kind          string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Symbols       []string `protobuf:"bytes,4,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Names         []string `protobuf:"bytes,5,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFactorsCrossRequest) Reset() {
	*x = GetFactorsCrossRequest{}
	mi := &file_api_market_v1_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFactorsCrossRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFactorsCrossRequest) ProtoMessage() {}

func (x *GetFactorsCrossRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFactorsCrossRequest.ProtoReflect.Descriptor instead.
func (*GetFactorsCrossRequest) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{6}
}

func (x *GetFactorsCrossRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *GetFactorsCrossRequest) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

func (x *GetFactorsCrossRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetFactorsCrossRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *GetFactorsCrossRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type FactorRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AsOf          string                 `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Values        map[string]float64     `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Stale         bool                   `protobuf:"varint,5,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorRow) Reset() {
	*x = FactorRow{}
	mi := &file_api_market_v1_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorRow) ProtoMessage() {}

func (x *FactorRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorRow.ProtoReflect.Descriptor instead.
func (*FactorRow) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{7}
}

func (x *FactorRow) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FactorRow) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

func (x *FactorRow) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FactorRow) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *FactorRow) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

type GetFactorsCrossReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeDate     string                 `protobuf:"bytes,1,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	Rows          []*FactorRow           `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFactorsCrossReply) Reset() {
	*x = GetFactorsCrossReply{}
	mi := &file_api_market_v1_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFactorsCrossReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFactorsCrossReply) ProtoMessage() {}

func (x *GetFactorsCrossReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFactorsCrossReply.ProtoReflect.Descriptor instead.
func (*GetFactorsCrossReply) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{8}
}

func (x *GetFactorsCrossReply) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *GetFactorsCrossReply) GetRows() []*FactorRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type GetSentimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeDate     string                 `protobuf:"bytes,1,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	AsOf          string                 `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSentimentRequest) Reset() {
	*x = GetSentimentRequest{}
	mi := &file_api_market_v1_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSentimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSentimentRequest) ProtoMessage() {}

func (x *GetSentimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSentimentRequest.ProtoReflect.Descriptor instead.
func (*GetSentimentRequest) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{9}
}

func (x *GetSentimentRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *GetSentimentRequest) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

type Sentiment struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TradeDate    string                 `protobuf:"bytes,1,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	AsOf         string                 `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	UpCount      int32                  `protobuf:"varint,3,opt,name=up_count,json=upCount,proto3" json:"up_count,omitempty"`
	DownCount    int32                  `protobuf:"varint,4,opt,name=down_count,json=downCount,proto3" json:"down_count,omitempty"`
	BrokenCount  int32                  `protobuf:"varint,5,opt,name=broken_count,json=brokenCount,proto3" json:"broken_count,omitempty"`
	BrokenRate   float64                `protobuf:"fixed64,6,opt,name=broken_rate,json=brokenRate,proto3" json:"broken_rate,omitempty"`
	MaxHeight    int32                  `protobuf:"varint,7,opt,name=max_height,json=maxHeight,proto3" json:"max_height,omitempty"`
	ProfitEffect float64                `protobuf:"fixed64,8,opt,name=profit_effect,json=profitEffect,proto3" json:"profit_effect,omitempty"`
	Advance      int32                  `protobuf:"varint,9,opt,name=advance,proto3" json:"advance,omitempty"`
	Decline      int32                  `protobuf:"varint,10,opt,name=decline,proto3" json:"decline,omitempty"`
	Flat         int32                  `protobuf:"varint,11,opt,name=flat,proto3" json:"flat,omitempty"`
	Amount       float64                `protobuf:"fixed64,12,opt,name=amount,proto3" json:"amount,omitempty"`
	// ICE / RECOVER / WARM / HOT / FADE
	Phase         string  `protobuf:"bytes,13,opt,name=phase,proto3" json:"phase,omitempty"`
	ScoreCoef     float64 `protobuf:"fixed64,14,opt,name=score_coef,json=scoreCoef,proto3" json:"score_coef,omitempty"`
	PositionScale float64 `protobuf:"fixed64,15,opt,name=position_scale,json=positionScale,proto3" json:"position_scale,omitempty"`
	Stale         bool    `protobuf:"varint,16,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sentiment) Reset() {
	*x = Sentiment{}
	mi := &file_api_market_v1_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sentiment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sentiment) ProtoMessage() {}

func (x *Sentiment) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sentiment.ProtoReflect.Descriptor instead.
func (*Sentiment) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{10}
}

func (x *Sentiment) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *Sentiment) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

func (x *Sentiment) GetUpCount() int32 {
	if x != nil {
		return x.UpCount
	}
	return 0
}

func (x *Sentiment) GetDownCount() int32 {
	if x != nil {
		return x.DownCount
	}
	return 0
}

func (x *Sentiment) GetBrokenCount() int32 {
	if x != nil {
		return x.BrokenCount
	}
	return 0
}

func (x *Sentiment) GetBrokenRate() float64 {
	if x != nil {
		return x.BrokenRate
	}
	return 0
}

func (x *Sentiment) GetMaxHeight() int32 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

func (x *Sentiment) GetProfitEffect() float64 {
	if x != nil {
		return x.ProfitEffect
	}
	return 0
}

func (x *Sentiment) GetAdvance() int32 {
	if x != nil {
		return x.Advance
	}
	return 0
}

func (x *Sentiment) GetDecline() int32 {
	if x != nil {
		return x.Decline
	}
	return 0
}

func (x *Sentiment) GetFlat() int32 {
	if x != nil {
		return x.Flat
	}
	return 0
}

func (x *Sentiment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Sentiment) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Sentiment) GetScoreCoef() float64 {
	if x != nil {
		return x.ScoreCoef
	}
	return 0
}

func (x *Sentiment) GetPositionScale() float64 {
	if x != nil {
		return x.PositionScale
	}
	return 0
}

func (x *Sentiment) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

type GetLimitBoardsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TradeDate string                 `protobuf:"bytes,1,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	// UP / DOWN，为空不限。
	Direction string `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	// SEALED / BROKEN，为空不限。
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitBoardsRequest) Reset() {
	*x = GetLimitBoardsRequest{}
	mi := &file_api_market_v1_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitBoardsRequest) ProtoMessage() {}

func (x *GetLimitBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitBoardsRequest.ProtoReflect.Descriptor instead.
func (*GetLimitBoardsRequest) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{11}
}

func (x *GetLimitBoardsRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *GetLimitBoardsRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *GetLimitBoardsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LimitBoard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TradeDate     string                 `protobuf:"bytes,2,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LimitPrice    float64                `protobuf:"fixed64,5,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	FirstSealAt   string                 `protobuf:"bytes,6,opt,name=first_seal_at,json=firstSealAt,proto3" json:"first_seal_at,omitempty"`
	LastSealAt    string                 `protobuf:"bytes,7,opt,name=last_seal_at,json=lastSealAt,proto3" json:"last_seal_at,omitempty"`
	OpenCount     int32                  `protobuf:"varint,8,opt,name=open_count,json=openCount,proto3" json:"open_count,omitempty"`
	SealAmount    float64                `protobuf:"fixed64,9,opt,name=seal_amount,json=sealAmount,proto3" json:"seal_amount,omitempty"`
	Consecutive   int32                  `protobuf:"varint,10,opt,name=consecutive,proto3" json:"consecutive,omitempty"`
	AsOf          string                 `protobuf:"bytes,11,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitBoard) Reset() {
	*x = LimitBoard{}
	mi := &file_api_market_v1_market_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitBoard) ProtoMessage() {}

func (x *LimitBoard) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitBoard.ProtoReflect.Descriptor instead.
func (*LimitBoard) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{12}
}

func (x *LimitBoard) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *LimitBoard) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *LimitBoard) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *LimitBoard) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LimitBoard) GetLimitPrice() float64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

func (x *LimitBoard) GetFirstSealAt() string {
	if x != nil {
		return x.FirstSealAt
	}
	return ""
}

func (x *LimitBoard) GetLastSealAt() string {
	if x != nil {
		return x.LastSealAt
	}
	return ""
}

func (x *LimitBoard) GetOpenCount() int32 {
	if x != nil {
		return x.OpenCount
	}
	return 0
}

func (x *LimitBoard) GetSealAmount() float64 {
	if x != nil {
		return x.SealAmount
	}
	return 0
}

func (x *LimitBoard) GetConsecutive() int32 {
	if x != nil {
		return x.Consecutive
	}
	return 0
}

func (x *LimitBoard) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

type GetLimitBoardsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boards        []*LimitBoard          `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitBoardsReply) Reset() {
	*x = GetLimitBoardsReply{}
	mi := &file_api_market_v1_market_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitBoardsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitBoardsReply) ProtoMessage() {}

func (x *GetLimitBoardsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitBoardsReply.ProtoReflect.Descriptor instead.
func (*GetLimitBoardsReply) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{13}
}

func (x *GetLimitBoardsReply) GetBoards() []*LimitBoard {
	if x != nil {
		return x.Boards
	}
	return nil
}

type GetSectorHeatRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TradeDate string                 `protobuf:"bytes,1,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	// 为空取实时排名。
	AsOf string `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	// 默认 50。
	Top           int32 `protobuf:"varint,3,opt,name=top,proto3" json:"top,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectorHeatRequest) Reset() {
	*x = GetSectorHeatRequest{}
	mi := &file_api_market_v1_market_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectorHeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectorHeatRequest) ProtoMessage() {}

func (x *GetSectorHeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectorHeatRequest.ProtoReflect.Descriptor instead.
func (*GetSectorHeatRequest) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{14}
}

func (x *GetSectorHeatRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *GetSectorHeatRequest) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

func (x *GetSectorHeatRequest) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

type SectorHeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SectorCode      string                 `protobuf:"bytes,1,opt,name=sector_code,json=sectorCode,proto3" json:"sector_code,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rank            int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Heat            float64                `protobuf:"fixed64,4,opt,name=heat,proto3" json:"heat,omitempty"`
	AvgPct          float64                `protobuf:"fixed64,5,opt,name=avg_pct,json=avgPct,proto3" json:"avg_pct,omitempty"`
	UpLimitCount    int32                  `protobuf:"varint,6,opt,name=up_limit_count,json=upLimitCount,proto3" json:"up_limit_count,omitempty"`
	AdvanceRatio    float64                `protobuf:"fixed64,7,opt,name=advance_ratio,json=advanceRatio,proto3" json:"advance_ratio,omitempty"`
	Amount          float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	MemberCount     int32                  `protobuf:"varint,9,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	LeaderSymbol    string                 `protobuf:"bytes,10,opt,name=leader_symbol,json=leaderSymbol,proto3" json:"leader_symbol,omitempty"`
	LeaderReason    string                 `protobuf:"bytes,11,opt,name=leader_reason,json=leaderReason,proto3" json:"leader_reason,omitempty"`
	OverseasImpulse float64                `protobuf:"fixed64,12,opt,name=overseas_impulse,json=overseasImpulse,proto3" json:"overseas_impulse,omitempty"`
	AsOf            string                 `protobuf:"bytes,13,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SectorHeat) Reset() {
	*x = SectorHeat{}
	mi := &file_api_market_v1_market_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectorHeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectorHeat) ProtoMessage() {}

func (x *SectorHeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectorHeat.ProtoReflect.Descriptor instead.
func (*SectorHeat) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{15}
}

func (x *SectorHeat) GetSectorCode() string {
	if x != nil {
		return x.SectorCode
	}
	return ""
}

func (x *SectorHeat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SectorHeat) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *SectorHeat) GetHeat() float64 {
	if x != nil {
		return x.Heat
	}
	return 0
}

func (x *SectorHeat) GetAvgPct() float64 {
	if x != nil {
		return x.AvgPct
	}
	return 0
}

func (x *SectorHeat) GetUpLimitCount() int32 {
	if x != nil {
		return x.UpLimitCount
	}
	return 0
}

func (x *SectorHeat) GetAdvanceRatio() float64 {
	if x != nil {
		return x.AdvanceRatio
	}
	return 0
}

func (x *SectorHeat) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SectorHeat) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *SectorHeat) GetLeaderSymbol() string {
	if x != nil {
		return x.LeaderSymbol
	}
	return ""
}

func (x *SectorHeat) GetLeaderReason() string {
	if x != nil {
		return x.LeaderReason
	}
	return ""
}

func (x *SectorHeat) GetOverseasImpulse() float64 {
	if x != nil {
		return x.OverseasImpulse
	}
	return 0
}

func (x *SectorHeat) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

type GetSectorHeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sectors       []*SectorHeat          `protobuf:"bytes,1,rep,name=sectors,proto3" json:"sectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectorHeatReply) Reset() {
	*x = GetSectorHeatReply{}
	mi := &file_api_market_v1_market_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectorHeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectorHeatReply) ProtoMessage() {}

func (x *GetSectorHeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectorHeatReply.ProtoReflect.Descriptor instead.
func (*GetSectorHeatReply) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{16}
}

func (x *GetSectorHeatReply) GetSectors() []*SectorHeat {
	if x != nil {
		return x.Sectors
	}
	return nil
}

type SetWatchlistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登记方，例如 strategy。
	Owner   string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Symbols []string `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	// 租约秒数，默认 600。
	TtlSeconds    int32 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWatchlistRequest) Reset() {
	*x = SetWatchlistRequest{}
	mi := &file_api_market_v1_market_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWatchlistRequest) ProtoMessage() {}

func (x *SetWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWatchlistRequest.ProtoReflect.Descriptor instead.
func (*SetWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{17}
}

func (x *SetWatchlistRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SetWatchlistRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *SetWatchlistRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetWatchlistReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWatchlistReply) Reset() {
	*x = SetWatchlistReply{}
	mi := &file_api_market_v1_market_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWatchlistReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWatchlistReply) ProtoMessage() {}

func (x *SetWatchlistReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_v1_market_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWatchlistReply.ProtoReflect.Descriptor instead.
func (*SetWatchlistReply) Descriptor() ([]byte, []int) {
	return file_api_market_v1_market_proto_rawDescGZIP(), []int{18}
}

func (x *SetWatchlistReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SetWatchlistReply) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_api_market_v1_market_proto protoreflect.FileDescriptor

const file_api_market_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/market/v1/market.proto\x12\rapi.market.v1\x1a\x1cgoogle/api/annotations.proto\"\xa9\x01\n" +
	"\x0eGetBarsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04freq\x18\x02 \x01(\tR\x04freq\x12\x14\n" +
	"\x05start\x18\x03 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\tR\x03end\x12-\n" +
	"\x06adjust\x18\x05 \x01(\x0e2\x15.api.market.v1.AdjustR\x06adjust\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\xb8\x01\n" +
	"\x03Bar\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x03R\x06volume\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"adj_factor\x18\b \x01(\x01R\tadjFactor\"b\n" +
	"\fGetBarsReply\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04freq\x18\x02 \x01(\tR\x04freq\x12&\n" +
	"\x04bars\x18\x03 \x03(\v2\x12.api.market.v1.BarR\x04bars\"\x9b\x01\n" +
	"\x14GetIndicatorsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05start\x18\x02 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\x12-\n" +
	"\x06adjust\x18\x04 \x01(\x0e2\x15.api.market.v1.AdjustR\x06adjust\x12\x14\n" +
	"\x05names\x18\x05 \x03(\tR\x05names\"\xa2\x01\n" +
	"\x0eIndicatorPoint\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12A\n" +
	"\x06values\x18\x02 \x03(\v2).api.market.v1.IndicatorPoint.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"c\n" +
	"\x12GetIndicatorsReply\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x125\n" +
	"\x06points\x18\x02 \x03(\v2\x1d.api.market.v1.IndicatorPointR\x06points\"\x90\x01\n" +
	"\x16GetFactorsCrossRequest\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x01 \x01(\tR\ttradeDate\x12\x13\n" +
	"\x05as_of\x18\x02 \x01(\tR\x04asOf\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\asymbols\x18\x04 \x03(\tR\asymbols\x12\x14\n" +
	"\x05names\x18\x05 \x03(\tR\x05names\"\xdb\x01\n" +
	"\tFactorRow\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x13\n" +
	"\x05as_of\x18\x02 \x01(\tR\x04asOf\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12<\n" +
	"\x06values\x18\x04 \x03(\v2$.api.market.v1.FactorRow.ValuesEntryR\x06values\x12\x14\n" +
	"\x05stale\x18\x05 \x01(\bR\x05stale\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"c\n" +
	"\x14GetFactorsCrossReply\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x01 \x01(\tR\ttradeDate\x12,\n" +
	"\x04rows\x18\x02 \x03(\v2\x18.api.market.v1.FactorRowR\x04rows\"I\n" +
	"\x13GetSentimentRequest\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x01 \x01(\tR\ttradeDate\x12\x13\n" +
	"\x05as_of\x18\x02 \x01(\tR\x04asOf\"\xd3\x03\n" +
	"\tSentiment\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x01 \x01(\tR\ttradeDate\x12\x13\n" +
	"\x05as_of\x18\x02 \x01(\tR\x04asOf\x12\x19\n" +
	"\bup_count\x18\x03 \x01(\x05R\aupCount\x12\x1d\n" +
	"\n" +
	"down_count\x18\x04 \x01(\x05R\tdownCount\x12!\n" +
	"\fbroken_count\x18\x05 \x01(\x05R\vbrokenCount\x12\x1f\n" +
	"\vbroken_rate\x18\x06 \x01(\x01R\n" +
	"brokenRate\x12\x1d\n" +
	"\n" +
	"max_height\x18\a \x01(\x05R\tmaxHeight\x12#\n" +
	"\rprofit_effect\x18\b \x01(\x01R\fprofitEffect\x12\x18\n" +
	"\aadvance\x18\t \x01(\x05R\aadvance\x12\x18\n" +
	"\adecline\x18\n" +
	" \x01(\x05R\adecline\x12\x12\n" +
	"\x04flat\x18\v \x01(\x05R\x04flat\x12\x16\n" +
	"\x06amount\x18\f \x01(\x01R\x06amount\x12\x14\n" +
	"\x05phase\x18\r \x01(\tR\x05phase\x12\x1d\n" +
	"\n" +
	"score_coef\x18\x0e \x01(\x01R\tscoreCoef\x12%\n" +
	"\x0eposition_scale\x18\x0f \x01(\x01R\rpositionScale\x12\x14\n" +
	"\x05stale\x18\x10 \x01(\bR\x05stale\"l\n" +
	"\x15GetLimitBoardsRequest\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x01 \x01(\tR\ttradeDate\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xd7\x02\n" +
	"\n" +
	"LimitBoard\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x02 \x01(\tR\ttradeDate\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vlimit_price\x18\x05 \x01(\x01R\n" +
	"limitPrice\x12\"\n" +
	"\rfirst_seal_at\x18\x06 \x01(\tR\vfirstSealAt\x12 \n" +
	"\flast_seal_at\x18\a \x01(\tR\n" +
	"lastSealAt\x12\x1d\n" +
	"\n" +
	"open_count\x18\b \x01(\x05R\topenCount\x12\x1f\n" +
	"\vseal_amount\x18\t \x01(\x01R\n" +
	"sealAmount\x12 \n" +
	"\vconsecutive\x18\n" +
	" \x01(\x05R\vconsecutive\x12\x13\n" +
	"\x05as_of\x18\v \x01(\tR\x04asOf\"H\n" +
	"\x13GetLimitBoardsReply\x121\n" +
	"\x06boards\x18\x01 \x03(\v2\x19.api.market.v1.LimitBoardR\x06boards\"\\\n" +
	"\x14GetSectorHeatRequest\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x01 \x01(\tR\ttradeDate\x12\x13\n" +
	"\x05as_of\x18\x02 \x01(\tR\x04asOf\x12\x10\n" +
	"\x03top\x18\x03 \x01(\x05R\x03top\"\x92\x03\n" +
	"\n" +
	"SectorHeat\x12\x1f\n" +
	"\vsector_code\x18\x01 \x01(\tR\n" +
	"sectorCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x12\n" +
	"\x04heat\x18\x04 \x01(\x01R\x04heat\x12\x17\n" +
	"\aavg_pct\x18\x05 \x01(\x01R\x06avgPct\x12$\n" +
	"\x0eup_limit_count\x18\x06 \x01(\x05R\fupLimitCount\x12#\n" +
	"\radvance_ratio\x18\a \x01(\x01R\fadvanceRatio\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12!\n" +
	"\fmember_count\x18\t \x01(\x05R\vmemberCount\x12#\n" +
	"\rleader_symbol\x18\n" +
	" \x01(\tR\fleaderSymbol\x12#\n" +
	"\rleader_reason\x18\v \x01(\tR\fleaderReason\x12)\n" +
	"\x10overseas_impulse\x18\f \x01(\x01R\x0foverseasImpulse\x12\x13\n" +
	"\x05as_of\x18\r \x01(\tR\x04asOf\"I\n" +
	"\x12GetSectorHeatReply\x123\n" +
	"\asectors\x18\x01 \x03(\v2\x19.api.market.v1.SectorHeatR\asectors\"f\n" +
	"\x13SetWatchlistRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"H\n" +
	"\x11SetWatchlistReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt*$\n" +
	"\x06Adjust\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03QFQ\x10\x01\x12\a\n" +
	"\x03HFQ\x10\x022\xaa\x06\n" +
	"\x06Market\x12^\n" +
	"\aGetBars\x12\x1d.api.market.v1.GetBarsRequest\x1a\x1b.api.market.v1.GetBarsReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/market/bars\x12v\n" +
	"\rGetIndicators\x12#.api.market.v1.GetIndicatorsRequest\x1a!.api.market.v1.GetIndicatorsReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/market/indicators\x12y\n" +
	"\x0fGetFactorsCross\x12%.api.market.v1.GetFactorsCrossRequest\x1a#.api.market.v1.GetFactorsCrossReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/market/factors\x12j\n" +
	"\fGetSentiment\x12\".api.market.v1.GetSentimentRequest\x1a\x18.api.market.v1.Sentiment\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/market/sentiment\x12u\n" +
	"\x0eGetLimitBoards\x12$.api.market.v1.GetLimitBoardsRequest\x1a\".api.market.v1.GetLimitBoardsReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/market/limits\x12s\n" +
	"\rGetSectorHeat\x12#.api.market.v1.GetSectorHeatRequest\x1a!.api.market.v1.GetSectorHeatReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/market/sectors\x12u\n" +
	"\fSetWatchlist\x12\".api.market.v1.SetWatchlistRequest\x1a .api.market.v1.SetWatchlistReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/market/watchlistB\x19Z\x17server/api/market/v1;v1b\x06proto3"

var (
	file_api_market_v1_market_proto_rawDescOnce sync.Once
	file_api_market_v1_market_proto_rawDescData []byte
)

func file_api_market_v1_market_proto_rawDescGZIP() []byte {
	file_api_market_v1_market_proto_rawDescOnce.Do(func() {
		file_api_market_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_market_v1_market_proto_rawDesc), len(file_api_market_v1_market_proto_rawDesc)))
	})
	return file_api_market_v1_market_proto_rawDescData
}

var file_api_market_v1_market_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_market_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_market_v1_market_proto_goTypes = []any{
	(Adjust)(0),                    // 0: api.market.v1.Adjust
	(*GetBarsRequest)(nil),         // 1: api.market.v1.GetBarsRequest
	(*Bar)(nil),                    // 2: api.market.v1.Bar
	(*GetBarsReply)(nil),           // 3: api.market.v1.GetBarsReply
	(*GetIndicatorsRequest)(nil),   // 4: api.market.v1.GetIndicatorsRequest
	(*IndicatorPoint)(nil),         // 5: api.market.v1.IndicatorPoint
	(*GetIndicatorsReply)(nil),     // 6: api.market.v1.GetIndicatorsReply
	(*GetFactorsCrossRequest)(nil), // 7: api.market.v1.GetFactorsCrossRequest
	(*FactorRow)(nil),              // 8: api.market.v1.FactorRow
	(*GetFactorsCrossReply)(nil),   // 9: api.market.v1.GetFactorsCrossReply
	(*GetSentimentRequest)(nil),    // 10: api.market.v1.GetSentimentRequest
	(*Sentiment)(nil),              // 11: api.market.v1.Sentiment
	(*GetLimitBoardsRequest)(nil),  // 12: api.market.v1.GetLimitBoardsRequest
	(*LimitBoard)(nil),             // 13: api.market.v1.LimitBoard
	(*GetLimitBoardsReply)(nil),    // 14: api.market.v1.GetLimitBoardsReply
	(*GetSectorHeatRequest)(nil),   // 15: api.market.v1.GetSectorHeatRequest
	(*SectorHeat)(nil),             // 16: api.market.v1.SectorHeat
	(*GetSectorHeatReply)(nil),     // 17: api.market.v1.GetSectorHeatReply
	(*SetWatchlistRequest)(nil),    // 18: api.market.v1.SetWatchlistRequest
	(*SetWatchlistReply)(nil),      // 19: api.market.v1.SetWatchlistReply
	nil,                            // 20: api.market.v1.IndicatorPoint.ValuesEntry
	nil,                            // 21: api.market.v1.FactorRow.ValuesEntry
}
var file_api_market_v1_market_proto_depIdxs = []int32{
	0,  // 0: api.market.v1.GetBarsRequest.adjust:type_name -> api.market.v1.Adjust
	2,  // 1: api.market.v1.GetBarsReply.bars:type_name -> api.market.v1.Bar
	0,  // 2: api.market.v1.GetIndicatorsRequest.adjust:type_name -> api.market.v1.Adjust
	20, // 3: api.market.v1.IndicatorPoint.values:type_name -> api.market.v1.IndicatorPoint.ValuesEntry
	5,  // 4: api.market.v1.GetIndicatorsReply.points:type_name -> api.market.v1.IndicatorPoint
	21, // 5: api.market.v1.FactorRow.values:type_name -> api.market.v1.FactorRow.ValuesEntry
	8,  // 6: api.market.v1.GetFactorsCrossReply.rows:type_name -> api.market.v1.FactorRow
	13, // 7: api.market.v1.GetLimitBoardsReply.boards:type_name -> api.market.v1.LimitBoard
	16, // 8: api.market.v1.GetSectorHeatReply.sectors:type_name -> api.market.v1.SectorHeat
	1,  // 9: api.market.v1.Market.GetBars:input_type -> api.market.v1.GetBarsRequest
	4,  // 10: api.market.v1.Market.GetIndicators:input_type -> api.market.v1.GetIndicatorsRequest
	7,  // 11: api.market.v1.Market.GetFactorsCross:input_type -> api.market.v1.GetFactorsCrossRequest
	10, // 12: api.market.v1.Market.GetSentiment:input_type -> api.market.v1.GetSentimentRequest
	12, // 13: api.market.v1.Market.GetLimitBoards:input_type -> api.market.v1.GetLimitBoardsRequest
	15, // 14: api.market.v1.Market.GetSectorHeat:input_type -> api.market.v1.GetSectorHeatRequest
	18, // 15: api.market.v1.Market.SetWatchlist:input_type -> api.market.v1.SetWatchlistRequest
	3,  // 16: api.market.v1.Market.GetBars:output_type -> api.market.v1.GetBarsReply
	6,  // 17: api.market.v1.Market.GetIndicators:output_type -> api.market.v1.GetIndicatorsReply
	9,  // 18: api.market.v1.Market.GetFactorsCross:output_type -> api.market.v1.GetFactorsCrossReply
	11, // 19: api.market.v1.Market.GetSentiment:output_type -> api.market.v1.Sentiment
	14, // 20: api.market.v1.Market.GetLimitBoards:output_type -> api.market.v1.GetLimitBoardsReply
	17, // 21: api.market.v1.Market.GetSectorHeat:output_type -> api.market.v1.GetSectorHeatReply
	19, // 22: api.market.v1.Market.SetWatchlist:output_type -> api.market.v1.SetWatchlistReply
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_market_v1_market_proto_init() }
func file_api_market_v1_market_proto_init() {
	if File_api_market_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_market_v1_market_proto_rawDesc), len(file_api_market_v1_market_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_market_v1_market_proto_goTypes,
		DependencyIndexes: file_api_market_v1_market_proto_depIdxs,
		EnumInfos:         file_api_market_v1_market_proto_enumTypes,
		MessageInfos:      file_api_market_v1_market_proto_msgTypes,
	}.Build()
	File_api_market_v1_market_proto = out.File
	file_api_market_v1_market_proto_goTypes = nil
	file_api_market_v1_market_proto_depIdxs = nil
}
