// Code generated by ent, DO NOT EDIT.

package position

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the position type in the database.
	Label = "position"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBook holds the string denoting the book field in the database.
	FieldBook = "book"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldAvailable holds the string denoting the available field in the database.
	FieldAvailable = "available"
	// FieldAvgCost holds the string denoting the avg_cost field in the database.
	FieldAvgCost = "avg_cost"
	// FieldCurrentPrice holds the string denoting the current_price field in the database.
	FieldCurrentPrice = "current_price"
	// FieldPnl holds the string denoting the pnl field in the database.
	FieldPnl = "pnl"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the position in the database.
	Table = "positions"
)

// Columns holds all SQL columns for position fields.
var Columns = []string{
	FieldID,
	FieldBook,
	FieldSymbol,
	FieldQuantity,
	FieldAvailable,
	FieldAvgCost,
	FieldCurrentPrice,
	FieldPnl,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBook holds the default value on creation for the "book" field.
	DefaultBook string
	// BookValidator is a validator for the "book" field. It is called by the builders before save.
	BookValidator func(string) error
	// SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	SymbolValidator func(string) error
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity int
	// DefaultAvailable holds the default value on creation for the "available" field.
	DefaultAvailable int
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Position queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBook orders the results by the book field.
func ByBook(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBook, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByAvailable orders the results by the available field.
func ByAvailable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailable, opts...).ToFunc()
}

// ByAvgCost orders the results by the avg_cost field.
func ByAvgCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgCost, opts...).ToFunc()
}

// ByCurrentPrice orders the results by the current_price field.
func ByCurrentPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPrice, opts...).ToFunc()
}

// ByPnl orders the results by the pnl field.
func ByPnl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPnl, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
