// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: api/admin/v1/airportinfo.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AirportServiceClient is the client API for AirportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirportServiceClient interface {
	GetAirInfoComplete(ctx context.Context, in *GetAirCompleteReq, opts ...grpc.CallOption) (*Airportinfo, error)
	UpdateAirInfoComplete(ctx context.Context, in *Airportinfo, opts ...grpc.CallOption) (*UpdateAirCompleteRes, error)
}

type airportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAirportServiceClient(cc grpc.ClientConnInterface) AirportServiceClient {
	return &airportServiceClient{cc}
}

func (c *airportServiceClient) GetAirInfoComplete(ctx context.Context, in *GetAirCompleteReq, opts ...grpc.CallOption) (*Airportinfo, error) {
	out := new(Airportinfo)
	err := c.cc.Invoke(ctx, "/admin.v1.AirportService/GetAirInfoComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airportServiceClient) UpdateAirInfoComplete(ctx context.Context, in *Airportinfo, opts ...grpc.CallOption) (*UpdateAirCompleteRes, error) {
	out := new(UpdateAirCompleteRes)
	err := c.cc.Invoke(ctx, "/admin.v1.AirportService/UpdateAirInfoComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirportServiceServer is the server API for AirportService service.
// All implementations must embed UnimplementedAirportServiceServer
// for forward compatibility
type AirportServiceServer interface {
	GetAirInfoComplete(context.Context, *GetAirCompleteReq) (*Airportinfo, error)
	UpdateAirInfoComplete(context.Context, *Airportinfo) (*UpdateAirCompleteRes, error)
	mustEmbedUnimplementedAirportServiceServer()
}

// UnimplementedAirportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAirportServiceServer struct {
}

func (UnimplementedAirportServiceServer) GetAirInfoComplete(context.Context, *GetAirCompleteReq) (*Airportinfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAirInfoComplete not implemented")
}
func (UnimplementedAirportServiceServer) UpdateAirInfoComplete(context.Context, *Airportinfo) (*UpdateAirCompleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAirInfoComplete not implemented")
}
func (UnimplementedAirportServiceServer) mustEmbedUnimplementedAirportServiceServer() {}

// UnsafeAirportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirportServiceServer will
// result in compilation errors.
type UnsafeAirportServiceServer interface {
	mustEmbedUnimplementedAirportServiceServer()
}

func RegisterAirportServiceServer(s grpc.ServiceRegistrar, srv AirportServiceServer) {
	s.RegisterService(&AirportService_ServiceDesc, srv)
}

func _AirportService_GetAirInfoComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAirCompleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirportServiceServer).GetAirInfoComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.AirportService/GetAirInfoComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirportServiceServer).GetAirInfoComplete(ctx, req.(*GetAirCompleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirportService_UpdateAirInfoComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Airportinfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirportServiceServer).UpdateAirInfoComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.AirportService/UpdateAirInfoComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirportServiceServer).UpdateAirInfoComplete(ctx, req.(*Airportinfo))
	}
	return interceptor(ctx, in, info, handler)
}

// AirportService_ServiceDesc is the grpc.ServiceDesc for AirportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.AirportService",
	HandlerType: (*AirportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAirInfoComplete",
			Handler:    _AirportService_GetAirInfoComplete_Handler,
		},
		{
			MethodName: "UpdateAirInfoComplete",
			Handler:    _AirportService_UpdateAirInfoComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/admin/v1/airportinfo.proto",
}
