// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.3.1
// - protoc             v3.21.2
// source: api/admin/v1/dataForward.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	v1 "server/api/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDataForwardServiceSetDataForwardSendData = "/api.admin.v1.DataForwardService/SetDataForwardSendData"
const OperationDataForwardServiceSetDataForwardSendStatus = "/api.admin.v1.DataForwardService/SetDataForwardSendStatus"

type DataForwardServiceHTTPServer interface {
	SetDataForwardSendData(context.Context, *v1.DataForwardCmd) (*emptypb.Empty, error)
	SetDataForwardSendStatus(context.Context, *v1.DataForwardStatusCmd) (*emptypb.Empty, error)
}

func RegisterDataForwardServiceHTTPServer(s *http.Server, srv DataForwardServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/dataForward/setDataForwardSendData", _DataForwardService_SetDataForwardSendData0_HTTP_Handler(srv))
	r.POST("/dataForward/setDataForwardSendStatus", _DataForwardService_SetDataForwardSendStatus0_HTTP_Handler(srv))
}

func _DataForwardService_SetDataForwardSendData0_HTTP_Handler(srv DataForwardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.DataForwardCmd
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataForwardServiceSetDataForwardSendData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetDataForwardSendData(ctx, req.(*v1.DataForwardCmd))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _DataForwardService_SetDataForwardSendStatus0_HTTP_Handler(srv DataForwardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.DataForwardStatusCmd
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataForwardServiceSetDataForwardSendStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetDataForwardSendStatus(ctx, req.(*v1.DataForwardStatusCmd))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type DataForwardServiceHTTPClient interface {
	SetDataForwardSendData(ctx context.Context, req *v1.DataForwardCmd, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	SetDataForwardSendStatus(ctx context.Context, req *v1.DataForwardStatusCmd, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type DataForwardServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDataForwardServiceHTTPClient(client *http.Client) DataForwardServiceHTTPClient {
	return &DataForwardServiceHTTPClientImpl{client}
}

func (c *DataForwardServiceHTTPClientImpl) SetDataForwardSendData(ctx context.Context, in *v1.DataForwardCmd, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/dataForward/setDataForwardSendData"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataForwardServiceSetDataForwardSendData))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *DataForwardServiceHTTPClientImpl) SetDataForwardSendStatus(ctx context.Context, in *v1.DataForwardStatusCmd, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/dataForward/setDataForwardSendStatus"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataForwardServiceSetDataForwardSendStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
