// Code generated by ent, DO NOT EDIT.

package seattag

import (
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldLTE(FieldID, id))
}

// SeatName applies equality check predicate on the "seat_name" field. It's identical to SeatNameEQ.
func SeatName(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEQ(FieldSeatName, v))
}

// Tag applies equality check predicate on the "tag" field. It's identical to TagEQ.
func Tag(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEQ(FieldTag, v))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEQ(FieldAlias, v))
}

// SeatNameEQ applies the EQ predicate on the "seat_name" field.
func SeatNameEQ(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEQ(FieldSeatName, v))
}

// SeatNameNEQ applies the NEQ predicate on the "seat_name" field.
func SeatNameNEQ(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldNEQ(FieldSeatName, v))
}

// SeatNameIn applies the In predicate on the "seat_name" field.
func SeatNameIn(vs ...string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldIn(FieldSeatName, vs...))
}

// SeatNameNotIn applies the NotIn predicate on the "seat_name" field.
func SeatNameNotIn(vs ...string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldNotIn(FieldSeatName, vs...))
}

// SeatNameGT applies the GT predicate on the "seat_name" field.
func SeatNameGT(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldGT(FieldSeatName, v))
}

// SeatNameGTE applies the GTE predicate on the "seat_name" field.
func SeatNameGTE(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldGTE(FieldSeatName, v))
}

// SeatNameLT applies the LT predicate on the "seat_name" field.
func SeatNameLT(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldLT(FieldSeatName, v))
}

// SeatNameLTE applies the LTE predicate on the "seat_name" field.
func SeatNameLTE(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldLTE(FieldSeatName, v))
}

// SeatNameContains applies the Contains predicate on the "seat_name" field.
func SeatNameContains(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldContains(FieldSeatName, v))
}

// SeatNameHasPrefix applies the HasPrefix predicate on the "seat_name" field.
func SeatNameHasPrefix(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldHasPrefix(FieldSeatName, v))
}

// SeatNameHasSuffix applies the HasSuffix predicate on the "seat_name" field.
func SeatNameHasSuffix(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldHasSuffix(FieldSeatName, v))
}

// SeatNameEqualFold applies the EqualFold predicate on the "seat_name" field.
func SeatNameEqualFold(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEqualFold(FieldSeatName, v))
}

// SeatNameContainsFold applies the ContainsFold predicate on the "seat_name" field.
func SeatNameContainsFold(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldContainsFold(FieldSeatName, v))
}

// TagEQ applies the EQ predicate on the "tag" field.
func TagEQ(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEQ(FieldTag, v))
}

// TagNEQ applies the NEQ predicate on the "tag" field.
func TagNEQ(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldNEQ(FieldTag, v))
}

// TagIn applies the In predicate on the "tag" field.
func TagIn(vs ...string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldIn(FieldTag, vs...))
}

// TagNotIn applies the NotIn predicate on the "tag" field.
func TagNotIn(vs ...string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldNotIn(FieldTag, vs...))
}

// TagGT applies the GT predicate on the "tag" field.
func TagGT(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldGT(FieldTag, v))
}

// TagGTE applies the GTE predicate on the "tag" field.
func TagGTE(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldGTE(FieldTag, v))
}

// TagLT applies the LT predicate on the "tag" field.
func TagLT(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldLT(FieldTag, v))
}

// TagLTE applies the LTE predicate on the "tag" field.
func TagLTE(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldLTE(FieldTag, v))
}

// TagContains applies the Contains predicate on the "tag" field.
func TagContains(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldContains(FieldTag, v))
}

// TagHasPrefix applies the HasPrefix predicate on the "tag" field.
func TagHasPrefix(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldHasPrefix(FieldTag, v))
}

// TagHasSuffix applies the HasSuffix predicate on the "tag" field.
func TagHasSuffix(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldHasSuffix(FieldTag, v))
}

// TagEqualFold applies the EqualFold predicate on the "tag" field.
func TagEqualFold(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEqualFold(FieldTag, v))
}

// TagContainsFold applies the ContainsFold predicate on the "tag" field.
func TagContainsFold(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldContainsFold(FieldTag, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.SeatTag {
	return predicate.SeatTag(sql.FieldContainsFold(FieldAlias, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SeatTag) predicate.SeatTag {
	return predicate.SeatTag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SeatTag) predicate.SeatTag {
	return predicate.SeatTag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SeatTag) predicate.SeatTag {
	return predicate.SeatTag(sql.NotPredicates(p))
}
