// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.32.1
// source: api/intel/v1/knowledge.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationKnowledgeDeleteDocument = "/api.intel.v1.Knowledge/DeleteDocument"
const OperationKnowledgeGetDocument = "/api.intel.v1.Knowledge/GetDocument"
const OperationKnowledgeIngestDocument = "/api.intel.v1.Knowledge/IngestDocument"
const OperationKnowledgeListDocuments = "/api.intel.v1.Knowledge/ListDocuments"
const OperationKnowledgeRecordCase = "/api.intel.v1.Knowledge/RecordCase"
const OperationKnowledgeSearch = "/api.intel.v1.Knowledge/Search"
const OperationKnowledgeSimilarCases = "/api.intel.v1.Knowledge/SimilarCases"

type KnowledgeHTTPServer interface {
	// DeleteDocument 标记删除，月度清理时连同向量一起删。
	DeleteDocument(context.Context, *KbDeleteDocumentRequest) (*KbDeleteDocumentReply, error)
	// GetDocument 文档详情和全部分块。
	GetDocument(context.Context, *KbGetDocumentRequest) (*KbGetDocumentReply, error)
	// IngestDocument 上传文档入库。同一内容重复上传返回原 doc_id。
	IngestDocument(context.Context, *KbIngestRequest) (*KbIngestReply, error)
	ListDocuments(context.Context, *KbListDocumentsRequest) (*KbListDocumentsReply, error)
	// RecordCase 补录走完的信号，与 strategy.signal.updated 消费走同一逻辑。
	RecordCase(context.Context, *KbSignalCase) (*KbRecordCaseReply, error)
	// Search 向量 + 关键词混合检索，结果带出处。
	Search(context.Context, *KbSearchRequest) (*KbSearchReply, error)
	// SimilarCases 相似历史案例。只返回 as_of 之前已结束的案例。
	SimilarCases(context.Context, *KbSimilarCasesRequest) (*KbSimilarCasesReply, error)
}

func RegisterKnowledgeHTTPServer(s *http.Server, srv KnowledgeHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/kb/documents", _Knowledge_IngestDocument0_HTTP_Handler(srv))
	r.GET("/v1/kb/documents/{id}", _Knowledge_GetDocument0_HTTP_Handler(srv))
	r.GET("/v1/kb/documents", _Knowledge_ListDocuments0_HTTP_Handler(srv))
	r.DELETE("/v1/kb/documents/{id}", _Knowledge_DeleteDocument0_HTTP_Handler(srv))
	r.POST("/v1/kb/search", _Knowledge_Search0_HTTP_Handler(srv))
	r.POST("/v1/kb/cases/similar", _Knowledge_SimilarCases0_HTTP_Handler(srv))
	r.POST("/v1/kb/cases", _Knowledge_RecordCase0_HTTP_Handler(srv))
}

func _Knowledge_IngestDocument0_HTTP_Handler(srv KnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KbIngestRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeIngestDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.IngestDocument(ctx, req.(*KbIngestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KbIngestReply)
		return ctx.Result(200, reply)
	}
}

func _Knowledge_GetDocument0_HTTP_Handler(srv KnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KbGetDocumentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeGetDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDocument(ctx, req.(*KbGetDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KbGetDocumentReply)
		return ctx.Result(200, reply)
	}
}

func _Knowledge_ListDocuments0_HTTP_Handler(srv KnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KbListDocumentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeListDocuments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDocuments(ctx, req.(*KbListDocumentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KbListDocumentsReply)
		return ctx.Result(200, reply)
	}
}

func _Knowledge_DeleteDocument0_HTTP_Handler(srv KnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KbDeleteDocumentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeDeleteDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDocument(ctx, req.(*KbDeleteDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KbDeleteDocumentReply)
		return ctx.Result(200, reply)
	}
}

func _Knowledge_Search0_HTTP_Handler(srv KnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KbSearchRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeSearch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Search(ctx, req.(*KbSearchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KbSearchReply)
		return ctx.Result(200, reply)
	}
}

func _Knowledge_SimilarCases0_HTTP_Handler(srv KnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KbSimilarCasesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeSimilarCases)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SimilarCases(ctx, req.(*KbSimilarCasesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KbSimilarCasesReply)
		return ctx.Result(200, reply)
	}
}

func _Knowledge_RecordCase0_HTTP_Handler(srv KnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KbSignalCase
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeRecordCase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RecordCase(ctx, req.(*KbSignalCase))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KbRecordCaseReply)
		return ctx.Result(200, reply)
	}
}

type KnowledgeHTTPClient interface {
	// DeleteDocument 标记删除，月度清理时连同向量一起删。
	DeleteDocument(ctx context.Context, req *KbDeleteDocumentRequest, opts ...http.CallOption) (rsp *KbDeleteDocumentReply, err error)
	// GetDocument 文档详情和全部分块。
	GetDocument(ctx context.Context, req *KbGetDocumentRequest, opts ...http.CallOption) (rsp *KbGetDocumentReply, err error)
	// IngestDocument 上传文档入库。同一内容重复上传返回原 doc_id。
	IngestDocument(ctx context.Context, req *KbIngestRequest, opts ...http.CallOption) (rsp *KbIngestReply, err error)
	ListDocuments(ctx context.Context, req *KbListDocumentsRequest, opts ...http.CallOption) (rsp *KbListDocumentsReply, err error)
	// RecordCase 补录走完的信号，与 strategy.signal.updated 消费走同一逻辑。
	RecordCase(ctx context.Context, req *KbSignalCase, opts ...http.CallOption) (rsp *KbRecordCaseReply, err error)
	// Search 向量 + 关键词混合检索，结果带出处。
	Search(ctx context.Context, req *KbSearchRequest, opts ...http.CallOption) (rsp *KbSearchReply, err error)
	// SimilarCases 相似历史案例。只返回 as_of 之前已结束的案例。
	SimilarCases(ctx context.Context, req *KbSimilarCasesRequest, opts ...http.CallOption) (rsp *KbSimilarCasesReply, err error)
}

type KnowledgeHTTPClientImpl struct {
	cc *http.Client
}

func NewKnowledgeHTTPClient(client *http.Client) KnowledgeHTTPClient {
	return &KnowledgeHTTPClientImpl{client}
}

// DeleteDocument 标记删除，月度清理时连同向量一起删。
func (c *KnowledgeHTTPClientImpl) DeleteDocument(ctx context.Context, in *KbDeleteDocumentRequest, opts ...http.CallOption) (*KbDeleteDocumentReply, error) {
	var out KbDeleteDocumentReply
	pattern := "/v1/kb/documents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeDeleteDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDocument 文档详情和全部分块。
func (c *KnowledgeHTTPClientImpl) GetDocument(ctx context.Context, in *KbGetDocumentRequest, opts ...http.CallOption) (*KbGetDocumentReply, error) {
	var out KbGetDocumentReply
	pattern := "/v1/kb/documents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeGetDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// IngestDocument 上传文档入库。同一内容重复上传返回原 doc_id。
func (c *KnowledgeHTTPClientImpl) IngestDocument(ctx context.Context, in *KbIngestRequest, opts ...http.CallOption) (*KbIngestReply, error) {
	var out KbIngestReply
	pattern := "/v1/kb/documents"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeIngestDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeHTTPClientImpl) ListDocuments(ctx context.Context, in *KbListDocumentsRequest, opts ...http.CallOption) (*KbListDocumentsReply, error) {
	var out KbListDocumentsReply
	pattern := "/v1/kb/documents"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeListDocuments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RecordCase 补录走完的信号，与 strategy.signal.updated 消费走同一逻辑。
func (c *KnowledgeHTTPClientImpl) RecordCase(ctx context.Context, in *KbSignalCase, opts ...http.CallOption) (*KbRecordCaseReply, error) {
	var out KbRecordCaseReply
	pattern := "/v1/kb/cases"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeRecordCase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Search 向量 + 关键词混合检索，结果带出处。
func (c *KnowledgeHTTPClientImpl) Search(ctx context.Context, in *KbSearchRequest, opts ...http.CallOption) (*KbSearchReply, error) {
	var out KbSearchReply
	pattern := "/v1/kb/search"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeSearch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SimilarCases 相似历史案例。只返回 as_of 之前已结束的案例。
func (c *KnowledgeHTTPClientImpl) SimilarCases(ctx context.Context, in *KbSimilarCasesRequest, opts ...http.CallOption) (*KbSimilarCasesReply, error) {
	var out KbSimilarCasesReply
	pattern := "/v1/kb/cases/similar"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeSimilarCases))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
