// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.1
// source: api/trade/v1/trade.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTradeApplyBar = "/api.trade.v1.Trade/ApplyBar"
const OperationTradeCancelOrder = "/api.trade.v1.Trade/CancelOrder"
const OperationTradeGetAccount = "/api.trade.v1.Trade/GetAccount"
const OperationTradeGetOrder = "/api.trade.v1.Trade/GetOrder"
const OperationTradeListPositions = "/api.trade.v1.Trade/ListPositions"
const OperationTradePlaceOrder = "/api.trade.v1.Trade/PlaceOrder"
const OperationTradeReconcile = "/api.trade.v1.Trade/Reconcile"
const OperationTradeRollDay = "/api.trade.v1.Trade/RollDay"

type TradeHTTPServer interface {
	// ApplyBar 用一根 K 线撮合该标的未完成委托。涨跌停价为 0 时不判断封板。
	ApplyBar(context.Context, *ApplyBarRequest) (*ApplyBarReply, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*Order, error)
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	GetOrder(context.Context, *GetOrderRequest) (*Order, error)
	ListPositions(context.Context, *ListPositionsRequest) (*ListPositionsReply, error)
	PlaceOrder(context.Context, *PlaceOrderRequest) (*Order, error)
	Reconcile(context.Context, *ReconcileRequest) (*ReconcileReply, error)
	RollDay(context.Context, *RollDayRequest) (*Account, error)
}

func RegisterTradeHTTPServer(s *http.Server, srv TradeHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/trade/orders", _Trade_PlaceOrder0_HTTP_Handler(srv))
	r.POST("/v1/trade/orders/{client_order_id}/cancel", _Trade_CancelOrder0_HTTP_Handler(srv))
	r.GET("/v1/trade/orders/{client_order_id}", _Trade_GetOrder0_HTTP_Handler(srv))
	r.GET("/v1/trade/positions", _Trade_ListPositions0_HTTP_Handler(srv))
	r.GET("/v1/trade/account", _Trade_GetAccount0_HTTP_Handler(srv))
	r.POST("/v1/trade/bars", _Trade_ApplyBar0_HTTP_Handler(srv))
	r.POST("/v1/trade/roll", _Trade_RollDay0_HTTP_Handler(srv))
	r.POST("/v1/trade/reconcile", _Trade_Reconcile0_HTTP_Handler(srv))
}

func _Trade_PlaceOrder0_HTTP_Handler(srv TradeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PlaceOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTradePlaceOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PlaceOrder(ctx, req.(*PlaceOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Order)
		return ctx.Result(200, reply)
	}
}

func _Trade_CancelOrder0_HTTP_Handler(srv TradeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTradeCancelOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelOrder(ctx, req.(*CancelOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Order)
		return ctx.Result(200, reply)
	}
}

func _Trade_GetOrder0_HTTP_Handler(srv TradeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTradeGetOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrder(ctx, req.(*GetOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Order)
		return ctx.Result(200, reply)
	}
}

func _Trade_ListPositions0_HTTP_Handler(srv TradeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPositionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTradeListPositions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPositions(ctx, req.(*ListPositionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPositionsReply)
		return ctx.Result(200, reply)
	}
}

func _Trade_GetAccount0_HTTP_Handler(srv TradeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTradeGetAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAccount(ctx, req.(*GetAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Account)
		return ctx.Result(200, reply)
	}
}

func _Trade_ApplyBar0_HTTP_Handler(srv TradeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyBarRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTradeApplyBar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyBar(ctx, req.(*ApplyBarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplyBarReply)
		return ctx.Result(200, reply)
	}
}

func _Trade_RollDay0_HTTP_Handler(srv TradeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RollDayRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTradeRollDay)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RollDay(ctx, req.(*RollDayRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Account)
		return ctx.Result(200, reply)
	}
}

func _Trade_Reconcile0_HTTP_Handler(srv TradeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReconcileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTradeReconcile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Reconcile(ctx, req.(*ReconcileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReconcileReply)
		return ctx.Result(200, reply)
	}
}

type TradeHTTPClient interface {
	// ApplyBar 用一根 K 线撮合该标的未完成委托。涨跌停价为 0 时不判断封板。
	ApplyBar(ctx context.Context, req *ApplyBarRequest, opts ...http.CallOption) (rsp *ApplyBarReply, err error)
	CancelOrder(ctx context.Context, req *CancelOrderRequest, opts ...http.CallOption) (rsp *Order, err error)
	GetAccount(ctx context.Context, req *GetAccountRequest, opts ...http.CallOption) (rsp *Account, err error)
	GetOrder(ctx context.Context, req *GetOrderRequest, opts ...http.CallOption) (rsp *Order, err error)
	ListPositions(ctx context.Context, req *ListPositionsRequest, opts ...http.CallOption) (rsp *ListPositionsReply, err error)
	PlaceOrder(ctx context.Context, req *PlaceOrderRequest, opts ...http.CallOption) (rsp *Order, err error)
	Reconcile(ctx context.Context, req *ReconcileRequest, opts ...http.CallOption) (rsp *ReconcileReply, err error)
	RollDay(ctx context.Context, req *RollDayRequest, opts ...http.CallOption) (rsp *Account, err error)
}

type TradeHTTPClientImpl struct {
	cc *http.Client
}

func NewTradeHTTPClient(client *http.Client) TradeHTTPClient {
	return &TradeHTTPClientImpl{client}
}

// ApplyBar 用一根 K 线撮合该标的未完成委托。涨跌停价为 0 时不判断封板。
func (c *TradeHTTPClientImpl) ApplyBar(ctx context.Context, in *ApplyBarRequest, opts ...http.CallOption) (*ApplyBarReply, error) {
	var out ApplyBarReply
	pattern := "/v1/trade/bars"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTradeApplyBar))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TradeHTTPClientImpl) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...http.CallOption) (*Order, error) {
	var out Order
	pattern := "/v1/trade/orders/{client_order_id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTradeCancelOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TradeHTTPClientImpl) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...http.CallOption) (*Account, error) {
	var out Account
	pattern := "/v1/trade/account"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTradeGetAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TradeHTTPClientImpl) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...http.CallOption) (*Order, error) {
	var out Order
	pattern := "/v1/trade/orders/{client_order_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTradeGetOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TradeHTTPClientImpl) ListPositions(ctx context.Context, in *ListPositionsRequest, opts ...http.CallOption) (*ListPositionsReply, error) {
	var out ListPositionsReply
	pattern := "/v1/trade/positions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTradeListPositions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TradeHTTPClientImpl) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...http.CallOption) (*Order, error) {
	var out Order
	pattern := "/v1/trade/orders"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTradePlaceOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TradeHTTPClientImpl) Reconcile(ctx context.Context, in *ReconcileRequest, opts ...http.CallOption) (*ReconcileReply, error) {
	var out ReconcileReply
	pattern := "/v1/trade/reconcile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTradeReconcile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TradeHTTPClientImpl) RollDay(ctx context.Context, in *RollDayRequest, opts ...http.CallOption) (*Account, error) {
	var out Account
	pattern := "/v1/trade/roll"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTradeRollDay))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
