// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/ent/dataqualityissue"
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DataQualityIssueDelete is the builder for deleting a DataQualityIssue entity.
type DataQualityIssueDelete struct {
	config
	hooks    []Hook
	mutation *DataQualityIssueMutation
}

// Where appends a list predicates to the DataQualityIssueDelete builder.
func (_d *DataQualityIssueDelete) Where(ps ...predicate.DataQualityIssue) *DataQualityIssueDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DataQualityIssueDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DataQualityIssueDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DataQualityIssueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dataqualityissue.Table, sqlgraph.NewFieldSpec(dataqualityissue.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DataQualityIssueDeleteOne is the builder for deleting a single DataQualityIssue entity.
type DataQualityIssueDeleteOne struct {
	_d *DataQualityIssueDelete
}

// Where appends a list predicates to the DataQualityIssueDelete builder.
func (_d *DataQualityIssueDeleteOne) Where(ps ...predicate.DataQualityIssue) *DataQualityIssueDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DataQualityIssueDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dataqualityissue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DataQualityIssueDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
