// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/ent/hotrank"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// HotRank is the model entity for the HotRank schema.
type HotRank struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 榜单，例如 eastmoney_popularity
	Board string `json:"board,omitempty"`
	// SnapTime holds the value of the "snap_time" field.
	SnapTime time.Time `json:"snap_time,omitempty"`
	// Rank holds the value of the "rank" field.
	Rank int `json:"rank,omitempty"`
	// Symbol holds the value of the "symbol" field.
	Symbol string `json:"symbol,omitempty"`
	// Heat holds the value of the "heat" field.
	Heat *float64 `json:"heat,omitempty"`
	// Source holds the value of the "source" field.
	Source       string `json:"source,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HotRank) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hotrank.FieldHeat:
			values[i] = new(sql.NullFloat64)
		case hotrank.FieldID, hotrank.FieldRank:
			values[i] = new(sql.NullInt64)
		case hotrank.FieldBoard, hotrank.FieldSymbol, hotrank.FieldSource:
			values[i] = new(sql.NullString)
		case hotrank.FieldSnapTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HotRank fields.
func (_m *HotRank) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hotrank.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case hotrank.FieldBoard:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field board", values[i])
			} else if value.Valid {
				_m.Board = value.String
			}
		case hotrank.FieldSnapTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field snap_time", values[i])
			} else if value.Valid {
				_m.SnapTime = value.Time
			}
		case hotrank.FieldRank:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rank", values[i])
			} else if value.Valid {
				_m.Rank = int(value.Int64)
			}
		case hotrank.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				_m.Symbol = value.String
			}
		case hotrank.FieldHeat:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field heat", values[i])
			} else if value.Valid {
				_m.Heat = new(float64)
				*_m.Heat = value.Float64
			}
		case hotrank.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HotRank.
// This includes values selected through modifiers, order, etc.
func (_m *HotRank) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this HotRank.
// Note that you need to call HotRank.Unwrap() before calling this method if this HotRank
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HotRank) Update() *HotRankUpdateOne {
	return NewHotRankClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HotRank entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HotRank) Unwrap() *HotRank {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HotRank is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HotRank) String() string {
	var builder strings.Builder
	builder.WriteString("HotRank(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("board=")
	builder.WriteString(_m.Board)
	builder.WriteString(", ")
	builder.WriteString("snap_time=")
	builder.WriteString(_m.SnapTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("rank=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rank))
	builder.WriteString(", ")
	builder.WriteString("symbol=")
	builder.WriteString(_m.Symbol)
	builder.WriteString(", ")
	if v := _m.Heat; v != nil {
		builder.WriteString("heat=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteByte(')')
	return builder.String()
}

// HotRanks is a parsable slice of HotRank.
type HotRanks []*HotRank
