// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/limitboard"
	"server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LimitBoardUpdate is the builder for updating LimitBoard entities.
type LimitBoardUpdate struct {
	config
	hooks    []Hook
	mutation *LimitBoardMutation
}

// Where appends a list predicates to the LimitBoardUpdate builder.
func (_u *LimitBoardUpdate) Where(ps ...predicate.LimitBoard) *LimitBoardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *LimitBoardUpdate) SetSymbol(v string) *LimitBoardUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableSymbol(v *string) *LimitBoardUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetTradeDate sets the "trade_date" field.
func (_u *LimitBoardUpdate) SetTradeDate(v time.Time) *LimitBoardUpdate {
	_u.mutation.SetTradeDate(v)
	return _u
}

// SetNillableTradeDate sets the "trade_date" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableTradeDate(v *time.Time) *LimitBoardUpdate {
	if v != nil {
		_u.SetTradeDate(*v)
	}
	return _u
}

// SetDirection sets the "direction" field.
func (_u *LimitBoardUpdate) SetDirection(v string) *LimitBoardUpdate {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableDirection(v *string) *LimitBoardUpdate {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LimitBoardUpdate) SetStatus(v string) *LimitBoardUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableStatus(v *string) *LimitBoardUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLimitPrice sets the "limit_price" field.
func (_u *LimitBoardUpdate) SetLimitPrice(v float64) *LimitBoardUpdate {
	_u.mutation.ResetLimitPrice()
	_u.mutation.SetLimitPrice(v)
	return _u
}

// SetNillableLimitPrice sets the "limit_price" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableLimitPrice(v *float64) *LimitBoardUpdate {
	if v != nil {
		_u.SetLimitPrice(*v)
	}
	return _u
}

// AddLimitPrice adds value to the "limit_price" field.
func (_u *LimitBoardUpdate) AddLimitPrice(v float64) *LimitBoardUpdate {
	_u.mutation.AddLimitPrice(v)
	return _u
}

// SetFirstSealAt sets the "first_seal_at" field.
func (_u *LimitBoardUpdate) SetFirstSealAt(v time.Time) *LimitBoardUpdate {
	_u.mutation.SetFirstSealAt(v)
	return _u
}

// SetNillableFirstSealAt sets the "first_seal_at" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableFirstSealAt(v *time.Time) *LimitBoardUpdate {
	if v != nil {
		_u.SetFirstSealAt(*v)
	}
	return _u
}

// ClearFirstSealAt clears the value of the "first_seal_at" field.
func (_u *LimitBoardUpdate) ClearFirstSealAt() *LimitBoardUpdate {
	_u.mutation.ClearFirstSealAt()
	return _u
}

// SetLastSealAt sets the "last_seal_at" field.
func (_u *LimitBoardUpdate) SetLastSealAt(v time.Time) *LimitBoardUpdate {
	_u.mutation.SetLastSealAt(v)
	return _u
}

// SetNillableLastSealAt sets the "last_seal_at" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableLastSealAt(v *time.Time) *LimitBoardUpdate {
	if v != nil {
		_u.SetLastSealAt(*v)
	}
	return _u
}

// ClearLastSealAt clears the value of the "last_seal_at" field.
func (_u *LimitBoardUpdate) ClearLastSealAt() *LimitBoardUpdate {
	_u.mutation.ClearLastSealAt()
	return _u
}

// SetOpenCount sets the "open_count" field.
func (_u *LimitBoardUpdate) SetOpenCount(v int) *LimitBoardUpdate {
	_u.mutation.ResetOpenCount()
	_u.mutation.SetOpenCount(v)
	return _u
}

// SetNillableOpenCount sets the "open_count" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableOpenCount(v *int) *LimitBoardUpdate {
	if v != nil {
		_u.SetOpenCount(*v)
	}
	return _u
}

// AddOpenCount adds value to the "open_count" field.
func (_u *LimitBoardUpdate) AddOpenCount(v int) *LimitBoardUpdate {
	_u.mutation.AddOpenCount(v)
	return _u
}

// SetSealAmount sets the "seal_amount" field.
func (_u *LimitBoardUpdate) SetSealAmount(v float64) *LimitBoardUpdate {
	_u.mutation.ResetSealAmount()
	_u.mutation.SetSealAmount(v)
	return _u
}

// SetNillableSealAmount sets the "seal_amount" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableSealAmount(v *float64) *LimitBoardUpdate {
	if v != nil {
		_u.SetSealAmount(*v)
	}
	return _u
}

// AddSealAmount adds value to the "seal_amount" field.
func (_u *LimitBoardUpdate) AddSealAmount(v float64) *LimitBoardUpdate {
	_u.mutation.AddSealAmount(v)
	return _u
}

// SetConsecutive sets the "consecutive" field.
func (_u *LimitBoardUpdate) SetConsecutive(v int) *LimitBoardUpdate {
	_u.mutation.ResetConsecutive()
	_u.mutation.SetConsecutive(v)
	return _u
}

// SetNillableConsecutive sets the "consecutive" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableConsecutive(v *int) *LimitBoardUpdate {
	if v != nil {
		_u.SetConsecutive(*v)
	}
	return _u
}

// AddConsecutive adds value to the "consecutive" field.
func (_u *LimitBoardUpdate) AddConsecutive(v int) *LimitBoardUpdate {
	_u.mutation.AddConsecutive(v)
	return _u
}

// SetAsOf sets the "as_of" field.
func (_u *LimitBoardUpdate) SetAsOf(v time.Time) *LimitBoardUpdate {
	_u.mutation.SetAsOf(v)
	return _u
}

// SetNillableAsOf sets the "as_of" field if the given value is not nil.
func (_u *LimitBoardUpdate) SetNillableAsOf(v *time.Time) *LimitBoardUpdate {
	if v != nil {
		_u.SetAsOf(*v)
	}
	return _u
}

// Mutation returns the LimitBoardMutation object of the builder.
func (_u *LimitBoardUpdate) Mutation() *LimitBoardMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LimitBoardUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LimitBoardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LimitBoardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LimitBoardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LimitBoardUpdate) check() error {
	if v, ok := _u.mutation.Symbol(); ok {
		if err := limitboard.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "LimitBoard.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := limitboard.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "LimitBoard.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := limitboard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LimitBoard.status": %w`, err)}
		}
	}
	return nil
}

func (_u *LimitBoardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(limitboard.Table, limitboard.Columns, sqlgraph.NewFieldSpec(limitboard.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(limitboard.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeDate(); ok {
		_spec.SetField(limitboard.FieldTradeDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(limitboard.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(limitboard.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LimitPrice(); ok {
		_spec.SetField(limitboard.FieldLimitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLimitPrice(); ok {
		_spec.AddField(limitboard.FieldLimitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FirstSealAt(); ok {
		_spec.SetField(limitboard.FieldFirstSealAt, field.TypeTime, value)
	}
	if _u.mutation.FirstSealAtCleared() {
		_spec.ClearField(limitboard.FieldFirstSealAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSealAt(); ok {
		_spec.SetField(limitboard.FieldLastSealAt, field.TypeTime, value)
	}
	if _u.mutation.LastSealAtCleared() {
		_spec.ClearField(limitboard.FieldLastSealAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OpenCount(); ok {
		_spec.SetField(limitboard.FieldOpenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenCount(); ok {
		_spec.AddField(limitboard.FieldOpenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SealAmount(); ok {
		_spec.SetField(limitboard.FieldSealAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSealAmount(); ok {
		_spec.AddField(limitboard.FieldSealAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Consecutive(); ok {
		_spec.SetField(limitboard.FieldConsecutive, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutive(); ok {
		_spec.AddField(limitboard.FieldConsecutive, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AsOf(); ok {
		_spec.SetField(limitboard.FieldAsOf, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{limitboard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LimitBoardUpdateOne is the builder for updating a single LimitBoard entity.
type LimitBoardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LimitBoardMutation
}

// SetSymbol sets the "symbol" field.
func (_u *LimitBoardUpdateOne) SetSymbol(v string) *LimitBoardUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableSymbol(v *string) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetTradeDate sets the "trade_date" field.
func (_u *LimitBoardUpdateOne) SetTradeDate(v time.Time) *LimitBoardUpdateOne {
	_u.mutation.SetTradeDate(v)
	return _u
}

// SetNillableTradeDate sets the "trade_date" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableTradeDate(v *time.Time) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetTradeDate(*v)
	}
	return _u
}

// SetDirection sets the "direction" field.
func (_u *LimitBoardUpdateOne) SetDirection(v string) *LimitBoardUpdateOne {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableDirection(v *string) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LimitBoardUpdateOne) SetStatus(v string) *LimitBoardUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableStatus(v *string) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLimitPrice sets the "limit_price" field.
func (_u *LimitBoardUpdateOne) SetLimitPrice(v float64) *LimitBoardUpdateOne {
	_u.mutation.ResetLimitPrice()
	_u.mutation.SetLimitPrice(v)
	return _u
}

// SetNillableLimitPrice sets the "limit_price" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableLimitPrice(v *float64) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetLimitPrice(*v)
	}
	return _u
}

// AddLimitPrice adds value to the "limit_price" field.
func (_u *LimitBoardUpdateOne) AddLimitPrice(v float64) *LimitBoardUpdateOne {
	_u.mutation.AddLimitPrice(v)
	return _u
}

// SetFirstSealAt sets the "first_seal_at" field.
func (_u *LimitBoardUpdateOne) SetFirstSealAt(v time.Time) *LimitBoardUpdateOne {
	_u.mutation.SetFirstSealAt(v)
	return _u
}

// SetNillableFirstSealAt sets the "first_seal_at" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableFirstSealAt(v *time.Time) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetFirstSealAt(*v)
	}
	return _u
}

// ClearFirstSealAt clears the value of the "first_seal_at" field.
func (_u *LimitBoardUpdateOne) ClearFirstSealAt() *LimitBoardUpdateOne {
	_u.mutation.ClearFirstSealAt()
	return _u
}

// SetLastSealAt sets the "last_seal_at" field.
func (_u *LimitBoardUpdateOne) SetLastSealAt(v time.Time) *LimitBoardUpdateOne {
	_u.mutation.SetLastSealAt(v)
	return _u
}

// SetNillableLastSealAt sets the "last_seal_at" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableLastSealAt(v *time.Time) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetLastSealAt(*v)
	}
	return _u
}

// ClearLastSealAt clears the value of the "last_seal_at" field.
func (_u *LimitBoardUpdateOne) ClearLastSealAt() *LimitBoardUpdateOne {
	_u.mutation.ClearLastSealAt()
	return _u
}

// SetOpenCount sets the "open_count" field.
func (_u *LimitBoardUpdateOne) SetOpenCount(v int) *LimitBoardUpdateOne {
	_u.mutation.ResetOpenCount()
	_u.mutation.SetOpenCount(v)
	return _u
}

// SetNillableOpenCount sets the "open_count" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableOpenCount(v *int) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetOpenCount(*v)
	}
	return _u
}

// AddOpenCount adds value to the "open_count" field.
func (_u *LimitBoardUpdateOne) AddOpenCount(v int) *LimitBoardUpdateOne {
	_u.mutation.AddOpenCount(v)
	return _u
}

// SetSealAmount sets the "seal_amount" field.
func (_u *LimitBoardUpdateOne) SetSealAmount(v float64) *LimitBoardUpdateOne {
	_u.mutation.ResetSealAmount()
	_u.mutation.SetSealAmount(v)
	return _u
}

// SetNillableSealAmount sets the "seal_amount" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableSealAmount(v *float64) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetSealAmount(*v)
	}
	return _u
}

// AddSealAmount adds value to the "seal_amount" field.
func (_u *LimitBoardUpdateOne) AddSealAmount(v float64) *LimitBoardUpdateOne {
	_u.mutation.AddSealAmount(v)
	return _u
}

// SetConsecutive sets the "consecutive" field.
func (_u *LimitBoardUpdateOne) SetConsecutive(v int) *LimitBoardUpdateOne {
	_u.mutation.ResetConsecutive()
	_u.mutation.SetConsecutive(v)
	return _u
}

// SetNillableConsecutive sets the "consecutive" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableConsecutive(v *int) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetConsecutive(*v)
	}
	return _u
}

// AddConsecutive adds value to the "consecutive" field.
func (_u *LimitBoardUpdateOne) AddConsecutive(v int) *LimitBoardUpdateOne {
	_u.mutation.AddConsecutive(v)
	return _u
}

// SetAsOf sets the "as_of" field.
func (_u *LimitBoardUpdateOne) SetAsOf(v time.Time) *LimitBoardUpdateOne {
	_u.mutation.SetAsOf(v)
	return _u
}

// SetNillableAsOf sets the "as_of" field if the given value is not nil.
func (_u *LimitBoardUpdateOne) SetNillableAsOf(v *time.Time) *LimitBoardUpdateOne {
	if v != nil {
		_u.SetAsOf(*v)
	}
	return _u
}

// Mutation returns the LimitBoardMutation object of the builder.
func (_u *LimitBoardUpdateOne) Mutation() *LimitBoardMutation {
	return _u.mutation
}

// Where appends a list predicates to the LimitBoardUpdate builder.
func (_u *LimitBoardUpdateOne) Where(ps ...predicate.LimitBoard) *LimitBoardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LimitBoardUpdateOne) Select(field string, fields ...string) *LimitBoardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LimitBoard entity.
func (_u *LimitBoardUpdateOne) Save(ctx context.Context) (*LimitBoard, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LimitBoardUpdateOne) SaveX(ctx context.Context) *LimitBoard {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LimitBoardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LimitBoardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LimitBoardUpdateOne) check() error {
	if v, ok := _u.mutation.Symbol(); ok {
		if err := limitboard.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "LimitBoard.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := limitboard.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "LimitBoard.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := limitboard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LimitBoard.status": %w`, err)}
		}
	}
	return nil
}

func (_u *LimitBoardUpdateOne) sqlSave(ctx context.Context) (_node *LimitBoard, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(limitboard.Table, limitboard.Columns, sqlgraph.NewFieldSpec(limitboard.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LimitBoard.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, limitboard.FieldID)
		for _, f := range fields {
			if !limitboard.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != limitboard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(limitboard.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeDate(); ok {
		_spec.SetField(limitboard.FieldTradeDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(limitboard.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(limitboard.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LimitPrice(); ok {
		_spec.SetField(limitboard.FieldLimitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLimitPrice(); ok {
		_spec.AddField(limitboard.FieldLimitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FirstSealAt(); ok {
		_spec.SetField(limitboard.FieldFirstSealAt, field.TypeTime, value)
	}
	if _u.mutation.FirstSealAtCleared() {
		_spec.ClearField(limitboard.FieldFirstSealAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSealAt(); ok {
		_spec.SetField(limitboard.FieldLastSealAt, field.TypeTime, value)
	}
	if _u.mutation.LastSealAtCleared() {
		_spec.ClearField(limitboard.FieldLastSealAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OpenCount(); ok {
		_spec.SetField(limitboard.FieldOpenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenCount(); ok {
		_spec.AddField(limitboard.FieldOpenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SealAmount(); ok {
		_spec.SetField(limitboard.FieldSealAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSealAmount(); ok {
		_spec.AddField(limitboard.FieldSealAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Consecutive(); ok {
		_spec.SetField(limitboard.FieldConsecutive, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutive(); ok {
		_spec.AddField(limitboard.FieldConsecutive, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AsOf(); ok {
		_spec.SetField(limitboard.FieldAsOf, field.TypeTime, value)
	}
	_node = &LimitBoard{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{limitboard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
