// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/moneyflow"
	"server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MoneyFlowUpdate is the builder for updating MoneyFlow entities.
type MoneyFlowUpdate struct {
	config
	hooks    []Hook
	mutation *MoneyFlowMutation
}

// Where appends a list predicates to the MoneyFlowUpdate builder.
func (_u *MoneyFlowUpdate) Where(ps ...predicate.MoneyFlow) *MoneyFlowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *MoneyFlowUpdate) SetSymbol(v string) *MoneyFlowUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *MoneyFlowUpdate) SetNillableSymbol(v *string) *MoneyFlowUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetTradeDate sets the "trade_date" field.
func (_u *MoneyFlowUpdate) SetTradeDate(v time.Time) *MoneyFlowUpdate {
	_u.mutation.SetTradeDate(v)
	return _u
}

// SetNillableTradeDate sets the "trade_date" field if the given value is not nil.
func (_u *MoneyFlowUpdate) SetNillableTradeDate(v *time.Time) *MoneyFlowUpdate {
	if v != nil {
		_u.SetTradeDate(*v)
	}
	return _u
}

// SetMainNet sets the "main_net" field.
func (_u *MoneyFlowUpdate) SetMainNet(v float64) *MoneyFlowUpdate {
	_u.mutation.ResetMainNet()
	_u.mutation.SetMainNet(v)
	return _u
}

// SetNillableMainNet sets the "main_net" field if the given value is not nil.
func (_u *MoneyFlowUpdate) SetNillableMainNet(v *float64) *MoneyFlowUpdate {
	if v != nil {
		_u.SetMainNet(*v)
	}
	return _u
}

// AddMainNet adds value to the "main_net" field.
func (_u *MoneyFlowUpdate) AddMainNet(v float64) *MoneyFlowUpdate {
	_u.mutation.AddMainNet(v)
	return _u
}

// SetSuperNet sets the "super_net" field.
func (_u *MoneyFlowUpdate) SetSuperNet(v float64) *MoneyFlowUpdate {
	_u.mutation.ResetSuperNet()
	_u.mutation.SetSuperNet(v)
	return _u
}

// SetNillableSuperNet sets the "super_net" field if the given value is not nil.
func (_u *MoneyFlowUpdate) SetNillableSuperNet(v *float64) *MoneyFlowUpdate {
	if v != nil {
		_u.SetSuperNet(*v)
	}
	return _u
}

// AddSuperNet adds value to the "super_net" field.
func (_u *MoneyFlowUpdate) AddSuperNet(v float64) *MoneyFlowUpdate {
	_u.mutation.AddSuperNet(v)
	return _u
}

// SetBigNet sets the "big_net" field.
func (_u *MoneyFlowUpdate) SetBigNet(v float64) *MoneyFlowUpdate {
	_u.mutation.ResetBigNet()
	_u.mutation.SetBigNet(v)
	return _u
}

// SetNillableBigNet sets the "big_net" field if the given value is not nil.
func (_u *MoneyFlowUpdate) SetNillableBigNet(v *float64) *MoneyFlowUpdate {
	if v != nil {
		_u.SetBigNet(*v)
	}
	return _u
}

// AddBigNet adds value to the "big_net" field.
func (_u *MoneyFlowUpdate) AddBigNet(v float64) *MoneyFlowUpdate {
	_u.mutation.AddBigNet(v)
	return _u
}

// SetMidNet sets the "mid_net" field.
func (_u *MoneyFlowUpdate) SetMidNet(v float64) *MoneyFlowUpdate {
	_u.mutation.ResetMidNet()
	_u.mutation.SetMidNet(v)
	return _u
}

// SetNillableMidNet sets the "mid_net" field if the given value is not nil.
func (_u *MoneyFlowUpdate) SetNillableMidNet(v *float64) *MoneyFlowUpdate {
	if v != nil {
		_u.SetMidNet(*v)
	}
	return _u
}

// AddMidNet adds value to the "mid_net" field.
func (_u *MoneyFlowUpdate) AddMidNet(v float64) *MoneyFlowUpdate {
	_u.mutation.AddMidNet(v)
	return _u
}

// SetSmallNet sets the "small_net" field.
func (_u *MoneyFlowUpdate) SetSmallNet(v float64) *MoneyFlowUpdate {
	_u.mutation.ResetSmallNet()
	_u.mutation.SetSmallNet(v)
	return _u
}

// SetNillableSmallNet sets the "small_net" field if the given value is not nil.
func (_u *MoneyFlowUpdate) SetNillableSmallNet(v *float64) *MoneyFlowUpdate {
	if v != nil {
		_u.SetSmallNet(*v)
	}
	return _u
}

// AddSmallNet adds value to the "small_net" field.
func (_u *MoneyFlowUpdate) AddSmallNet(v float64) *MoneyFlowUpdate {
	_u.mutation.AddSmallNet(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *MoneyFlowUpdate) SetSource(v string) *MoneyFlowUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *MoneyFlowUpdate) SetNillableSource(v *string) *MoneyFlowUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// Mutation returns the MoneyFlowMutation object of the builder.
func (_u *MoneyFlowUpdate) Mutation() *MoneyFlowMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MoneyFlowUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MoneyFlowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MoneyFlowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MoneyFlowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MoneyFlowUpdate) check() error {
	if v, ok := _u.mutation.Symbol(); ok {
		if err := moneyflow.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "MoneyFlow.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := moneyflow.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MoneyFlow.source": %w`, err)}
		}
	}
	return nil
}

func (_u *MoneyFlowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(moneyflow.Table, moneyflow.Columns, sqlgraph.NewFieldSpec(moneyflow.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(moneyflow.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeDate(); ok {
		_spec.SetField(moneyflow.FieldTradeDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MainNet(); ok {
		_spec.SetField(moneyflow.FieldMainNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMainNet(); ok {
		_spec.AddField(moneyflow.FieldMainNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SuperNet(); ok {
		_spec.SetField(moneyflow.FieldSuperNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSuperNet(); ok {
		_spec.AddField(moneyflow.FieldSuperNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BigNet(); ok {
		_spec.SetField(moneyflow.FieldBigNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBigNet(); ok {
		_spec.AddField(moneyflow.FieldBigNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MidNet(); ok {
		_spec.SetField(moneyflow.FieldMidNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMidNet(); ok {
		_spec.AddField(moneyflow.FieldMidNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SmallNet(); ok {
		_spec.SetField(moneyflow.FieldSmallNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSmallNet(); ok {
		_spec.AddField(moneyflow.FieldSmallNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(moneyflow.FieldSource, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moneyflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MoneyFlowUpdateOne is the builder for updating a single MoneyFlow entity.
type MoneyFlowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MoneyFlowMutation
}

// SetSymbol sets the "symbol" field.
func (_u *MoneyFlowUpdateOne) SetSymbol(v string) *MoneyFlowUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *MoneyFlowUpdateOne) SetNillableSymbol(v *string) *MoneyFlowUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetTradeDate sets the "trade_date" field.
func (_u *MoneyFlowUpdateOne) SetTradeDate(v time.Time) *MoneyFlowUpdateOne {
	_u.mutation.SetTradeDate(v)
	return _u
}

// SetNillableTradeDate sets the "trade_date" field if the given value is not nil.
func (_u *MoneyFlowUpdateOne) SetNillableTradeDate(v *time.Time) *MoneyFlowUpdateOne {
	if v != nil {
		_u.SetTradeDate(*v)
	}
	return _u
}

// SetMainNet sets the "main_net" field.
func (_u *MoneyFlowUpdateOne) SetMainNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.ResetMainNet()
	_u.mutation.SetMainNet(v)
	return _u
}

// SetNillableMainNet sets the "main_net" field if the given value is not nil.
func (_u *MoneyFlowUpdateOne) SetNillableMainNet(v *float64) *MoneyFlowUpdateOne {
	if v != nil {
		_u.SetMainNet(*v)
	}
	return _u
}

// AddMainNet adds value to the "main_net" field.
func (_u *MoneyFlowUpdateOne) AddMainNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.AddMainNet(v)
	return _u
}

// SetSuperNet sets the "super_net" field.
func (_u *MoneyFlowUpdateOne) SetSuperNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.ResetSuperNet()
	_u.mutation.SetSuperNet(v)
	return _u
}

// SetNillableSuperNet sets the "super_net" field if the given value is not nil.
func (_u *MoneyFlowUpdateOne) SetNillableSuperNet(v *float64) *MoneyFlowUpdateOne {
	if v != nil {
		_u.SetSuperNet(*v)
	}
	return _u
}

// AddSuperNet adds value to the "super_net" field.
func (_u *MoneyFlowUpdateOne) AddSuperNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.AddSuperNet(v)
	return _u
}

// SetBigNet sets the "big_net" field.
func (_u *MoneyFlowUpdateOne) SetBigNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.ResetBigNet()
	_u.mutation.SetBigNet(v)
	return _u
}

// SetNillableBigNet sets the "big_net" field if the given value is not nil.
func (_u *MoneyFlowUpdateOne) SetNillableBigNet(v *float64) *MoneyFlowUpdateOne {
	if v != nil {
		_u.SetBigNet(*v)
	}
	return _u
}

// AddBigNet adds value to the "big_net" field.
func (_u *MoneyFlowUpdateOne) AddBigNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.AddBigNet(v)
	return _u
}

// SetMidNet sets the "mid_net" field.
func (_u *MoneyFlowUpdateOne) SetMidNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.ResetMidNet()
	_u.mutation.SetMidNet(v)
	return _u
}

// SetNillableMidNet sets the "mid_net" field if the given value is not nil.
func (_u *MoneyFlowUpdateOne) SetNillableMidNet(v *float64) *MoneyFlowUpdateOne {
	if v != nil {
		_u.SetMidNet(*v)
	}
	return _u
}

// AddMidNet adds value to the "mid_net" field.
func (_u *MoneyFlowUpdateOne) AddMidNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.AddMidNet(v)
	return _u
}

// SetSmallNet sets the "small_net" field.
func (_u *MoneyFlowUpdateOne) SetSmallNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.ResetSmallNet()
	_u.mutation.SetSmallNet(v)
	return _u
}

// SetNillableSmallNet sets the "small_net" field if the given value is not nil.
func (_u *MoneyFlowUpdateOne) SetNillableSmallNet(v *float64) *MoneyFlowUpdateOne {
	if v != nil {
		_u.SetSmallNet(*v)
	}
	return _u
}

// AddSmallNet adds value to the "small_net" field.
func (_u *MoneyFlowUpdateOne) AddSmallNet(v float64) *MoneyFlowUpdateOne {
	_u.mutation.AddSmallNet(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *MoneyFlowUpdateOne) SetSource(v string) *MoneyFlowUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *MoneyFlowUpdateOne) SetNillableSource(v *string) *MoneyFlowUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// Mutation returns the MoneyFlowMutation object of the builder.
func (_u *MoneyFlowUpdateOne) Mutation() *MoneyFlowMutation {
	return _u.mutation
}

// Where appends a list predicates to the MoneyFlowUpdate builder.
func (_u *MoneyFlowUpdateOne) Where(ps ...predicate.MoneyFlow) *MoneyFlowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MoneyFlowUpdateOne) Select(field string, fields ...string) *MoneyFlowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MoneyFlow entity.
func (_u *MoneyFlowUpdateOne) Save(ctx context.Context) (*MoneyFlow, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MoneyFlowUpdateOne) SaveX(ctx context.Context) *MoneyFlow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MoneyFlowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MoneyFlowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MoneyFlowUpdateOne) check() error {
	if v, ok := _u.mutation.Symbol(); ok {
		if err := moneyflow.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "MoneyFlow.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := moneyflow.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MoneyFlow.source": %w`, err)}
		}
	}
	return nil
}

func (_u *MoneyFlowUpdateOne) sqlSave(ctx context.Context) (_node *MoneyFlow, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(moneyflow.Table, moneyflow.Columns, sqlgraph.NewFieldSpec(moneyflow.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MoneyFlow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moneyflow.FieldID)
		for _, f := range fields {
			if !moneyflow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != moneyflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(moneyflow.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeDate(); ok {
		_spec.SetField(moneyflow.FieldTradeDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MainNet(); ok {
		_spec.SetField(moneyflow.FieldMainNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMainNet(); ok {
		_spec.AddField(moneyflow.FieldMainNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SuperNet(); ok {
		_spec.SetField(moneyflow.FieldSuperNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSuperNet(); ok {
		_spec.AddField(moneyflow.FieldSuperNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BigNet(); ok {
		_spec.SetField(moneyflow.FieldBigNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBigNet(); ok {
		_spec.AddField(moneyflow.FieldBigNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MidNet(); ok {
		_spec.SetField(moneyflow.FieldMidNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMidNet(); ok {
		_spec.AddField(moneyflow.FieldMidNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SmallNet(); ok {
		_spec.SetField(moneyflow.FieldSmallNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSmallNet(); ok {
		_spec.AddField(moneyflow.FieldSmallNet, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(moneyflow.FieldSource, field.TypeString, value)
	}
	_node = &MoneyFlow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moneyflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
