// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/newssentiment"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NewsSentimentCreate is the builder for creating a NewsSentiment entity.
type NewsSentimentCreate struct {
	config
	mutation *NewsSentimentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNewsTitle sets the "news_title" field.
func (_c *NewsSentimentCreate) SetNewsTitle(v string) *NewsSentimentCreate {
	_c.mutation.SetNewsTitle(v)
	return _c
}

// SetNillableNewsTitle sets the "news_title" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableNewsTitle(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetNewsTitle(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *NewsSentimentCreate) SetContent(v string) *NewsSentimentCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableContent(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *NewsSentimentCreate) SetSource(v string) *NewsSentimentCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableSource(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetPublishTime sets the "publish_time" field.
func (_c *NewsSentimentCreate) SetPublishTime(v time.Time) *NewsSentimentCreate {
	_c.mutation.SetPublishTime(v)
	return _c
}

// SetNillablePublishTime sets the "publish_time" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillablePublishTime(v *time.Time) *NewsSentimentCreate {
	if v != nil {
		_c.SetPublishTime(*v)
	}
	return _c
}

// SetSentimentScore sets the "sentiment_score" field.
func (_c *NewsSentimentCreate) SetSentimentScore(v float64) *NewsSentimentCreate {
	_c.mutation.SetSentimentScore(v)
	return _c
}

// SetNillableSentimentScore sets the "sentiment_score" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableSentimentScore(v *float64) *NewsSentimentCreate {
	if v != nil {
		_c.SetSentimentScore(*v)
	}
	return _c
}

// SetImportance sets the "importance" field.
func (_c *NewsSentimentCreate) SetImportance(v int) *NewsSentimentCreate {
	_c.mutation.SetImportance(v)
	return _c
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableImportance(v *int) *NewsSentimentCreate {
	if v != nil {
		_c.SetImportance(*v)
	}
	return _c
}

// SetStockCode sets the "stock_code" field.
func (_c *NewsSentimentCreate) SetStockCode(v string) *NewsSentimentCreate {
	_c.mutation.SetStockCode(v)
	return _c
}

// SetNillableStockCode sets the "stock_code" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableStockCode(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetStockCode(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *NewsSentimentCreate) SetKind(v string) *NewsSentimentCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableKind(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *NewsSentimentCreate) SetSourceID(v string) *NewsSentimentCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableSourceID(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *NewsSentimentCreate) SetURL(v string) *NewsSentimentCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableURL(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *NewsSentimentCreate) SetContentHash(v string) *NewsSentimentCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableContentHash(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetContentHash(*v)
	}
	return _c
}

// SetSourceCodes sets the "source_codes" field.
func (_c *NewsSentimentCreate) SetSourceCodes(v []string) *NewsSentimentCreate {
	_c.mutation.SetSourceCodes(v)
	return _c
}

// SetSimhash sets the "simhash" field.
func (_c *NewsSentimentCreate) SetSimhash(v int64) *NewsSentimentCreate {
	_c.mutation.SetSimhash(v)
	return _c
}

// SetNillableSimhash sets the "simhash" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableSimhash(v *int64) *NewsSentimentCreate {
	if v != nil {
		_c.SetSimhash(*v)
	}
	return _c
}

// SetClusterID sets the "cluster_id" field.
func (_c *NewsSentimentCreate) SetClusterID(v int) *NewsSentimentCreate {
	_c.mutation.SetClusterID(v)
	return _c
}

// SetNillableClusterID sets the "cluster_id" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableClusterID(v *int) *NewsSentimentCreate {
	if v != nil {
		_c.SetClusterID(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *NewsSentimentCreate) SetEventType(v string) *NewsSentimentCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableEventType(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetEventType(*v)
	}
	return _c
}

// SetHalfLifeMinutes sets the "half_life_minutes" field.
func (_c *NewsSentimentCreate) SetHalfLifeMinutes(v int) *NewsSentimentCreate {
	_c.mutation.SetHalfLifeMinutes(v)
	return _c
}

// SetNillableHalfLifeMinutes sets the "half_life_minutes" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableHalfLifeMinutes(v *int) *NewsSentimentCreate {
	if v != nil {
		_c.SetHalfLifeMinutes(*v)
	}
	return _c
}

// SetScorer sets the "scorer" field.
func (_c *NewsSentimentCreate) SetScorer(v string) *NewsSentimentCreate {
	_c.mutation.SetScorer(v)
	return _c
}

// SetNillableScorer sets the "scorer" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableScorer(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetScorer(*v)
	}
	return _c
}

// SetDegraded sets the "degraded" field.
func (_c *NewsSentimentCreate) SetDegraded(v bool) *NewsSentimentCreate {
	_c.mutation.SetDegraded(v)
	return _c
}

// SetNillableDegraded sets the "degraded" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableDegraded(v *bool) *NewsSentimentCreate {
	if v != nil {
		_c.SetDegraded(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *NewsSentimentCreate) SetStatus(v string) *NewsSentimentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableStatus(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *NewsSentimentCreate) SetReason(v string) *NewsSentimentCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableReason(v *string) *NewsSentimentCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetPublishTimeGuessed sets the "publish_time_guessed" field.
func (_c *NewsSentimentCreate) SetPublishTimeGuessed(v bool) *NewsSentimentCreate {
	_c.mutation.SetPublishTimeGuessed(v)
	return _c
}

// SetNillablePublishTimeGuessed sets the "publish_time_guessed" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillablePublishTimeGuessed(v *bool) *NewsSentimentCreate {
	if v != nil {
		_c.SetPublishTimeGuessed(*v)
	}
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *NewsSentimentCreate) SetReceivedAt(v time.Time) *NewsSentimentCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableReceivedAt(v *time.Time) *NewsSentimentCreate {
	if v != nil {
		_c.SetReceivedAt(*v)
	}
	return _c
}

// SetScoredAt sets the "scored_at" field.
func (_c *NewsSentimentCreate) SetScoredAt(v time.Time) *NewsSentimentCreate {
	_c.mutation.SetScoredAt(v)
	return _c
}

// SetNillableScoredAt sets the "scored_at" field if the given value is not nil.
func (_c *NewsSentimentCreate) SetNillableScoredAt(v *time.Time) *NewsSentimentCreate {
	if v != nil {
		_c.SetScoredAt(*v)
	}
	return _c
}

// Mutation returns the NewsSentimentMutation object of the builder.
func (_c *NewsSentimentCreate) Mutation() *NewsSentimentMutation {
	return _c.mutation
}

// Save creates the NewsSentiment in the database.
func (_c *NewsSentimentCreate) Save(ctx context.Context) (*NewsSentiment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NewsSentimentCreate) SaveX(ctx context.Context) *NewsSentiment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NewsSentimentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NewsSentimentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NewsSentimentCreate) defaults() {
	if _, ok := _c.mutation.Importance(); !ok {
		v := newssentiment.DefaultImportance
		_c.mutation.SetImportance(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := newssentiment.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		v := newssentiment.DefaultSourceID
		_c.mutation.SetSourceID(v)
	}
	if _, ok := _c.mutation.URL(); !ok {
		v := newssentiment.DefaultURL
		_c.mutation.SetURL(v)
	}
	if _, ok := _c.mutation.Simhash(); !ok {
		v := newssentiment.DefaultSimhash
		_c.mutation.SetSimhash(v)
	}
	if _, ok := _c.mutation.EventType(); !ok {
		v := newssentiment.DefaultEventType
		_c.mutation.SetEventType(v)
	}
	if _, ok := _c.mutation.HalfLifeMinutes(); !ok {
		v := newssentiment.DefaultHalfLifeMinutes
		_c.mutation.SetHalfLifeMinutes(v)
	}
	if _, ok := _c.mutation.Scorer(); !ok {
		v := newssentiment.DefaultScorer
		_c.mutation.SetScorer(v)
	}
	if _, ok := _c.mutation.Degraded(); !ok {
		v := newssentiment.DefaultDegraded
		_c.mutation.SetDegraded(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := newssentiment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := newssentiment.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.PublishTimeGuessed(); !ok {
		v := newssentiment.DefaultPublishTimeGuessed
		_c.mutation.SetPublishTimeGuessed(v)
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		v := newssentiment.DefaultReceivedAt()
		_c.mutation.SetReceivedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NewsSentimentCreate) check() error {
	if v, ok := _c.mutation.Source(); ok {
		if err := newssentiment.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "NewsSentiment.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Importance(); !ok {
		return &ValidationError{Name: "importance", err: errors.New(`ent: missing required field "NewsSentiment.importance"`)}
	}
	if v, ok := _c.mutation.StockCode(); ok {
		if err := newssentiment.StockCodeValidator(v); err != nil {
			return &ValidationError{Name: "stock_code", err: fmt.Errorf(`ent: validator failed for field "NewsSentiment.stock_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "NewsSentiment.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := newssentiment.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NewsSentiment.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "NewsSentiment.source_id"`)}
	}
	if v, ok := _c.mutation.SourceID(); ok {
		if err := newssentiment.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "NewsSentiment.source_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "NewsSentiment.url"`)}
	}
	if v, ok := _c.mutation.ContentHash(); ok {
		if err := newssentiment.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "NewsSentiment.content_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Simhash(); !ok {
		return &ValidationError{Name: "simhash", err: errors.New(`ent: missing required field "NewsSentiment.simhash"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "NewsSentiment.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := newssentiment.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "NewsSentiment.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HalfLifeMinutes(); !ok {
		return &ValidationError{Name: "half_life_minutes", err: errors.New(`ent: missing required field "NewsSentiment.half_life_minutes"`)}
	}
	if _, ok := _c.mutation.Scorer(); !ok {
		return &ValidationError{Name: "scorer", err: errors.New(`ent: missing required field "NewsSentiment.scorer"`)}
	}
	if v, ok := _c.mutation.Scorer(); ok {
		if err := newssentiment.ScorerValidator(v); err != nil {
			return &ValidationError{Name: "scorer", err: fmt.Errorf(`ent: validator failed for field "NewsSentiment.scorer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Degraded(); !ok {
		return &ValidationError{Name: "degraded", err: errors.New(`ent: missing required field "NewsSentiment.degraded"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "NewsSentiment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := newssentiment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NewsSentiment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "NewsSentiment.reason"`)}
	}
	if _, ok := _c.mutation.PublishTimeGuessed(); !ok {
		return &ValidationError{Name: "publish_time_guessed", err: errors.New(`ent: missing required field "NewsSentiment.publish_time_guessed"`)}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "NewsSentiment.received_at"`)}
	}
	return nil
}

func (_c *NewsSentimentCreate) sqlSave(ctx context.Context) (*NewsSentiment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NewsSentimentCreate) createSpec() (*NewsSentiment, *sqlgraph.CreateSpec) {
	var (
		_node = &NewsSentiment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(newssentiment.Table, sqlgraph.NewFieldSpec(newssentiment.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.NewsTitle(); ok {
		_spec.SetField(newssentiment.FieldNewsTitle, field.TypeString, value)
		_node.NewsTitle = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(newssentiment.FieldContent, field.TypeString, value)
		_node.Content = &value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(newssentiment.FieldSource, field.TypeString, value)
		_node.Source = &value
	}
	if value, ok := _c.mutation.PublishTime(); ok {
		_spec.SetField(newssentiment.FieldPublishTime, field.TypeTime, value)
		_node.PublishTime = &value
	}
	if value, ok := _c.mutation.SentimentScore(); ok {
		_spec.SetField(newssentiment.FieldSentimentScore, field.TypeFloat64, value)
		_node.SentimentScore = &value
	}
	if value, ok := _c.mutation.Importance(); ok {
		_spec.SetField(newssentiment.FieldImportance, field.TypeInt, value)
		_node.Importance = value
	}
	if value, ok := _c.mutation.StockCode(); ok {
		_spec.SetField(newssentiment.FieldStockCode, field.TypeString, value)
		_node.StockCode = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(newssentiment.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(newssentiment.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(newssentiment.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(newssentiment.FieldContentHash, field.TypeString, value)
		_node.ContentHash = &value
	}
	if value, ok := _c.mutation.SourceCodes(); ok {
		_spec.SetField(newssentiment.FieldSourceCodes, field.TypeJSON, value)
		_node.SourceCodes = value
	}
	if value, ok := _c.mutation.Simhash(); ok {
		_spec.SetField(newssentiment.FieldSimhash, field.TypeInt64, value)
		_node.Simhash = value
	}
	if value, ok := _c.mutation.ClusterID(); ok {
		_spec.SetField(newssentiment.FieldClusterID, field.TypeInt, value)
		_node.ClusterID = &value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(newssentiment.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.HalfLifeMinutes(); ok {
		_spec.SetField(newssentiment.FieldHalfLifeMinutes, field.TypeInt, value)
		_node.HalfLifeMinutes = value
	}
	if value, ok := _c.mutation.Scorer(); ok {
		_spec.SetField(newssentiment.FieldScorer, field.TypeString, value)
		_node.Scorer = value
	}
	if value, ok := _c.mutation.Degraded(); ok {
		_spec.SetField(newssentiment.FieldDegraded, field.TypeBool, value)
		_node.Degraded = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(newssentiment.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(newssentiment.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.PublishTimeGuessed(); ok {
		_spec.SetField(newssentiment.FieldPublishTimeGuessed, field.TypeBool, value)
		_node.PublishTimeGuessed = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(newssentiment.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := _c.mutation.ScoredAt(); ok {
		_spec.SetField(newssentiment.FieldScoredAt, field.TypeTime, value)
		_node.ScoredAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NewsSentiment.Create().
//		SetNewsTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NewsSentimentUpsert) {
//			SetNewsTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *NewsSentimentCreate) OnConflict(opts ...sql.ConflictOption) *NewsSentimentUpsertOne {
	_c.conflict = opts
	return &NewsSentimentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NewsSentiment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NewsSentimentCreate) OnConflictColumns(columns ...string) *NewsSentimentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NewsSentimentUpsertOne{
		create: _c,
	}
}

type (
	// NewsSentimentUpsertOne is the builder for "upsert"-ing
	//  one NewsSentiment node.
	NewsSentimentUpsertOne struct {
		create *NewsSentimentCreate
	}

	// NewsSentimentUpsert is the "OnConflict" setter.
	NewsSentimentUpsert struct {
		*sql.UpdateSet
	}
)

// SetNewsTitle sets the "news_title" field.
func (u *NewsSentimentUpsert) SetNewsTitle(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldNewsTitle, v)
	return u
}

// UpdateNewsTitle sets the "news_title" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateNewsTitle() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldNewsTitle)
	return u
}

// ClearNewsTitle clears the value of the "news_title" field.
func (u *NewsSentimentUpsert) ClearNewsTitle() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldNewsTitle)
	return u
}

// SetContent sets the "content" field.
func (u *NewsSentimentUpsert) SetContent(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateContent() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *NewsSentimentUpsert) ClearContent() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldContent)
	return u
}

// SetSource sets the "source" field.
func (u *NewsSentimentUpsert) SetSource(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateSource() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldSource)
	return u
}

// ClearSource clears the value of the "source" field.
func (u *NewsSentimentUpsert) ClearSource() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldSource)
	return u
}

// SetPublishTime sets the "publish_time" field.
func (u *NewsSentimentUpsert) SetPublishTime(v time.Time) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldPublishTime, v)
	return u
}

// UpdatePublishTime sets the "publish_time" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdatePublishTime() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldPublishTime)
	return u
}

// ClearPublishTime clears the value of the "publish_time" field.
func (u *NewsSentimentUpsert) ClearPublishTime() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldPublishTime)
	return u
}

// SetSentimentScore sets the "sentiment_score" field.
func (u *NewsSentimentUpsert) SetSentimentScore(v float64) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldSentimentScore, v)
	return u
}

// UpdateSentimentScore sets the "sentiment_score" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateSentimentScore() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldSentimentScore)
	return u
}

// AddSentimentScore adds v to the "sentiment_score" field.
func (u *NewsSentimentUpsert) AddSentimentScore(v float64) *NewsSentimentUpsert {
	u.Add(newssentiment.FieldSentimentScore, v)
	return u
}

// ClearSentimentScore clears the value of the "sentiment_score" field.
func (u *NewsSentimentUpsert) ClearSentimentScore() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldSentimentScore)
	return u
}

// SetImportance sets the "importance" field.
func (u *NewsSentimentUpsert) SetImportance(v int) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldImportance, v)
	return u
}

// UpdateImportance sets the "importance" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateImportance() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldImportance)
	return u
}

// AddImportance adds v to the "importance" field.
func (u *NewsSentimentUpsert) AddImportance(v int) *NewsSentimentUpsert {
	u.Add(newssentiment.FieldImportance, v)
	return u
}

// SetStockCode sets the "stock_code" field.
func (u *NewsSentimentUpsert) SetStockCode(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldStockCode, v)
	return u
}

// UpdateStockCode sets the "stock_code" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateStockCode() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldStockCode)
	return u
}

// ClearStockCode clears the value of the "stock_code" field.
func (u *NewsSentimentUpsert) ClearStockCode() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldStockCode)
	return u
}

// SetKind sets the "kind" field.
func (u *NewsSentimentUpsert) SetKind(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateKind() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldKind)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *NewsSentimentUpsert) SetSourceID(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateSourceID() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldSourceID)
	return u
}

// SetURL sets the "url" field.
func (u *NewsSentimentUpsert) SetURL(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateURL() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldURL)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *NewsSentimentUpsert) SetContentHash(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateContentHash() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldContentHash)
	return u
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *NewsSentimentUpsert) ClearContentHash() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldContentHash)
	return u
}

// SetSourceCodes sets the "source_codes" field.
func (u *NewsSentimentUpsert) SetSourceCodes(v []string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldSourceCodes, v)
	return u
}

// UpdateSourceCodes sets the "source_codes" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateSourceCodes() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldSourceCodes)
	return u
}

// ClearSourceCodes clears the value of the "source_codes" field.
func (u *NewsSentimentUpsert) ClearSourceCodes() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldSourceCodes)
	return u
}

// SetSimhash sets the "simhash" field.
func (u *NewsSentimentUpsert) SetSimhash(v int64) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldSimhash, v)
	return u
}

// UpdateSimhash sets the "simhash" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateSimhash() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldSimhash)
	return u
}

// AddSimhash adds v to the "simhash" field.
func (u *NewsSentimentUpsert) AddSimhash(v int64) *NewsSentimentUpsert {
	u.Add(newssentiment.FieldSimhash, v)
	return u
}

// SetClusterID sets the "cluster_id" field.
func (u *NewsSentimentUpsert) SetClusterID(v int) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldClusterID, v)
	return u
}

// UpdateClusterID sets the "cluster_id" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateClusterID() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldClusterID)
	return u
}

// AddClusterID adds v to the "cluster_id" field.
func (u *NewsSentimentUpsert) AddClusterID(v int) *NewsSentimentUpsert {
	u.Add(newssentiment.FieldClusterID, v)
	return u
}

// ClearClusterID clears the value of the "cluster_id" field.
func (u *NewsSentimentUpsert) ClearClusterID() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldClusterID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *NewsSentimentUpsert) SetEventType(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateEventType() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldEventType)
	return u
}

// SetHalfLifeMinutes sets the "half_life_minutes" field.
func (u *NewsSentimentUpsert) SetHalfLifeMinutes(v int) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldHalfLifeMinutes, v)
	return u
}

// UpdateHalfLifeMinutes sets the "half_life_minutes" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateHalfLifeMinutes() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldHalfLifeMinutes)
	return u
}

// AddHalfLifeMinutes adds v to the "half_life_minutes" field.
func (u *NewsSentimentUpsert) AddHalfLifeMinutes(v int) *NewsSentimentUpsert {
	u.Add(newssentiment.FieldHalfLifeMinutes, v)
	return u
}

// SetScorer sets the "scorer" field.
func (u *NewsSentimentUpsert) SetScorer(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldScorer, v)
	return u
}

// UpdateScorer sets the "scorer" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateScorer() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldScorer)
	return u
}

// SetDegraded sets the "degraded" field.
func (u *NewsSentimentUpsert) SetDegraded(v bool) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldDegraded, v)
	return u
}

// UpdateDegraded sets the "degraded" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateDegraded() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldDegraded)
	return u
}

// SetStatus sets the "status" field.
func (u *NewsSentimentUpsert) SetStatus(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateStatus() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldStatus)
	return u
}

// SetReason sets the "reason" field.
func (u *NewsSentimentUpsert) SetReason(v string) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateReason() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldReason)
	return u
}

// SetPublishTimeGuessed sets the "publish_time_guessed" field.
func (u *NewsSentimentUpsert) SetPublishTimeGuessed(v bool) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldPublishTimeGuessed, v)
	return u
}

// UpdatePublishTimeGuessed sets the "publish_time_guessed" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdatePublishTimeGuessed() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldPublishTimeGuessed)
	return u
}

// SetReceivedAt sets the "received_at" field.
func (u *NewsSentimentUpsert) SetReceivedAt(v time.Time) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldReceivedAt, v)
	return u
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateReceivedAt() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldReceivedAt)
	return u
}

// SetScoredAt sets the "scored_at" field.
func (u *NewsSentimentUpsert) SetScoredAt(v time.Time) *NewsSentimentUpsert {
	u.Set(newssentiment.FieldScoredAt, v)
	return u
}

// UpdateScoredAt sets the "scored_at" field to the value that was provided on create.
func (u *NewsSentimentUpsert) UpdateScoredAt() *NewsSentimentUpsert {
	u.SetExcluded(newssentiment.FieldScoredAt)
	return u
}

// ClearScoredAt clears the value of the "scored_at" field.
func (u *NewsSentimentUpsert) ClearScoredAt() *NewsSentimentUpsert {
	u.SetNull(newssentiment.FieldScoredAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NewsSentiment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NewsSentimentUpsertOne) UpdateNewValues() *NewsSentimentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NewsSentiment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NewsSentimentUpsertOne) Ignore() *NewsSentimentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NewsSentimentUpsertOne) DoNothing() *NewsSentimentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NewsSentimentCreate.OnConflict
// documentation for more info.
func (u *NewsSentimentUpsertOne) Update(set func(*NewsSentimentUpsert)) *NewsSentimentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NewsSentimentUpsert{UpdateSet: update})
	}))
	return u
}

// SetNewsTitle sets the "news_title" field.
func (u *NewsSentimentUpsertOne) SetNewsTitle(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetNewsTitle(v)
	})
}

// UpdateNewsTitle sets the "news_title" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateNewsTitle() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateNewsTitle()
	})
}

// ClearNewsTitle clears the value of the "news_title" field.
func (u *NewsSentimentUpsertOne) ClearNewsTitle() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearNewsTitle()
	})
}

// SetContent sets the "content" field.
func (u *NewsSentimentUpsertOne) SetContent(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateContent() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *NewsSentimentUpsertOne) ClearContent() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearContent()
	})
}

// SetSource sets the "source" field.
func (u *NewsSentimentUpsertOne) SetSource(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateSource() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *NewsSentimentUpsertOne) ClearSource() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearSource()
	})
}

// SetPublishTime sets the "publish_time" field.
func (u *NewsSentimentUpsertOne) SetPublishTime(v time.Time) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetPublishTime(v)
	})
}

// UpdatePublishTime sets the "publish_time" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdatePublishTime() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdatePublishTime()
	})
}

// ClearPublishTime clears the value of the "publish_time" field.
func (u *NewsSentimentUpsertOne) ClearPublishTime() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearPublishTime()
	})
}

// SetSentimentScore sets the "sentiment_score" field.
func (u *NewsSentimentUpsertOne) SetSentimentScore(v float64) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSentimentScore(v)
	})
}

// AddSentimentScore adds v to the "sentiment_score" field.
func (u *NewsSentimentUpsertOne) AddSentimentScore(v float64) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddSentimentScore(v)
	})
}

// UpdateSentimentScore sets the "sentiment_score" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateSentimentScore() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSentimentScore()
	})
}

// ClearSentimentScore clears the value of the "sentiment_score" field.
func (u *NewsSentimentUpsertOne) ClearSentimentScore() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearSentimentScore()
	})
}

// SetImportance sets the "importance" field.
func (u *NewsSentimentUpsertOne) SetImportance(v int) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetImportance(v)
	})
}

// AddImportance adds v to the "importance" field.
func (u *NewsSentimentUpsertOne) AddImportance(v int) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddImportance(v)
	})
}

// UpdateImportance sets the "importance" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateImportance() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateImportance()
	})
}

// SetStockCode sets the "stock_code" field.
func (u *NewsSentimentUpsertOne) SetStockCode(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetStockCode(v)
	})
}

// UpdateStockCode sets the "stock_code" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateStockCode() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateStockCode()
	})
}

// ClearStockCode clears the value of the "stock_code" field.
func (u *NewsSentimentUpsertOne) ClearStockCode() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearStockCode()
	})
}

// SetKind sets the "kind" field.
func (u *NewsSentimentUpsertOne) SetKind(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateKind() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateKind()
	})
}

// SetSourceID sets the "source_id" field.
func (u *NewsSentimentUpsertOne) SetSourceID(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateSourceID() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSourceID()
	})
}

// SetURL sets the "url" field.
func (u *NewsSentimentUpsertOne) SetURL(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateURL() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateURL()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *NewsSentimentUpsertOne) SetContentHash(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateContentHash() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *NewsSentimentUpsertOne) ClearContentHash() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearContentHash()
	})
}

// SetSourceCodes sets the "source_codes" field.
func (u *NewsSentimentUpsertOne) SetSourceCodes(v []string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSourceCodes(v)
	})
}

// UpdateSourceCodes sets the "source_codes" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateSourceCodes() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSourceCodes()
	})
}

// ClearSourceCodes clears the value of the "source_codes" field.
func (u *NewsSentimentUpsertOne) ClearSourceCodes() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearSourceCodes()
	})
}

// SetSimhash sets the "simhash" field.
func (u *NewsSentimentUpsertOne) SetSimhash(v int64) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSimhash(v)
	})
}

// AddSimhash adds v to the "simhash" field.
func (u *NewsSentimentUpsertOne) AddSimhash(v int64) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddSimhash(v)
	})
}

// UpdateSimhash sets the "simhash" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateSimhash() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSimhash()
	})
}

// SetClusterID sets the "cluster_id" field.
func (u *NewsSentimentUpsertOne) SetClusterID(v int) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetClusterID(v)
	})
}

// AddClusterID adds v to the "cluster_id" field.
func (u *NewsSentimentUpsertOne) AddClusterID(v int) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddClusterID(v)
	})
}

// UpdateClusterID sets the "cluster_id" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateClusterID() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateClusterID()
	})
}

// ClearClusterID clears the value of the "cluster_id" field.
func (u *NewsSentimentUpsertOne) ClearClusterID() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearClusterID()
	})
}

// SetEventType sets the "event_type" field.
func (u *NewsSentimentUpsertOne) SetEventType(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateEventType() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateEventType()
	})
}

// SetHalfLifeMinutes sets the "half_life_minutes" field.
func (u *NewsSentimentUpsertOne) SetHalfLifeMinutes(v int) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetHalfLifeMinutes(v)
	})
}

// AddHalfLifeMinutes adds v to the "half_life_minutes" field.
func (u *NewsSentimentUpsertOne) AddHalfLifeMinutes(v int) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddHalfLifeMinutes(v)
	})
}

// UpdateHalfLifeMinutes sets the "half_life_minutes" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateHalfLifeMinutes() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateHalfLifeMinutes()
	})
}

// SetScorer sets the "scorer" field.
func (u *NewsSentimentUpsertOne) SetScorer(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetScorer(v)
	})
}

// UpdateScorer sets the "scorer" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateScorer() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateScorer()
	})
}

// SetDegraded sets the "degraded" field.
func (u *NewsSentimentUpsertOne) SetDegraded(v bool) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetDegraded(v)
	})
}

// UpdateDegraded sets the "degraded" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateDegraded() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateDegraded()
	})
}

// SetStatus sets the "status" field.
func (u *NewsSentimentUpsertOne) SetStatus(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateStatus() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *NewsSentimentUpsertOne) SetReason(v string) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateReason() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateReason()
	})
}

// SetPublishTimeGuessed sets the "publish_time_guessed" field.
func (u *NewsSentimentUpsertOne) SetPublishTimeGuessed(v bool) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetPublishTimeGuessed(v)
	})
}

// UpdatePublishTimeGuessed sets the "publish_time_guessed" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdatePublishTimeGuessed() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdatePublishTimeGuessed()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *NewsSentimentUpsertOne) SetReceivedAt(v time.Time) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateReceivedAt() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetScoredAt sets the "scored_at" field.
func (u *NewsSentimentUpsertOne) SetScoredAt(v time.Time) *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetScoredAt(v)
	})
}

// UpdateScoredAt sets the "scored_at" field to the value that was provided on create.
func (u *NewsSentimentUpsertOne) UpdateScoredAt() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateScoredAt()
	})
}

// ClearScoredAt clears the value of the "scored_at" field.
func (u *NewsSentimentUpsertOne) ClearScoredAt() *NewsSentimentUpsertOne {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearScoredAt()
	})
}

// Exec executes the query.
func (u *NewsSentimentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NewsSentimentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NewsSentimentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NewsSentimentUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NewsSentimentUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NewsSentimentCreateBulk is the builder for creating many NewsSentiment entities in bulk.
type NewsSentimentCreateBulk struct {
	config
	err      error
	builders []*NewsSentimentCreate
	conflict []sql.ConflictOption
}

// Save creates the NewsSentiment entities in the database.
func (_c *NewsSentimentCreateBulk) Save(ctx context.Context) ([]*NewsSentiment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NewsSentiment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NewsSentimentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NewsSentimentCreateBulk) SaveX(ctx context.Context) []*NewsSentiment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NewsSentimentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NewsSentimentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NewsSentiment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NewsSentimentUpsert) {
//			SetNewsTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *NewsSentimentCreateBulk) OnConflict(opts ...sql.ConflictOption) *NewsSentimentUpsertBulk {
	_c.conflict = opts
	return &NewsSentimentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NewsSentiment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NewsSentimentCreateBulk) OnConflictColumns(columns ...string) *NewsSentimentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NewsSentimentUpsertBulk{
		create: _c,
	}
}

// NewsSentimentUpsertBulk is the builder for "upsert"-ing
// a bulk of NewsSentiment nodes.
type NewsSentimentUpsertBulk struct {
	create *NewsSentimentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NewsSentiment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NewsSentimentUpsertBulk) UpdateNewValues() *NewsSentimentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NewsSentiment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NewsSentimentUpsertBulk) Ignore() *NewsSentimentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NewsSentimentUpsertBulk) DoNothing() *NewsSentimentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NewsSentimentCreateBulk.OnConflict
// documentation for more info.
func (u *NewsSentimentUpsertBulk) Update(set func(*NewsSentimentUpsert)) *NewsSentimentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NewsSentimentUpsert{UpdateSet: update})
	}))
	return u
}

// SetNewsTitle sets the "news_title" field.
func (u *NewsSentimentUpsertBulk) SetNewsTitle(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetNewsTitle(v)
	})
}

// UpdateNewsTitle sets the "news_title" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateNewsTitle() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateNewsTitle()
	})
}

// ClearNewsTitle clears the value of the "news_title" field.
func (u *NewsSentimentUpsertBulk) ClearNewsTitle() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearNewsTitle()
	})
}

// SetContent sets the "content" field.
func (u *NewsSentimentUpsertBulk) SetContent(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateContent() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *NewsSentimentUpsertBulk) ClearContent() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearContent()
	})
}

// SetSource sets the "source" field.
func (u *NewsSentimentUpsertBulk) SetSource(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateSource() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *NewsSentimentUpsertBulk) ClearSource() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearSource()
	})
}

// SetPublishTime sets the "publish_time" field.
func (u *NewsSentimentUpsertBulk) SetPublishTime(v time.Time) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetPublishTime(v)
	})
}

// UpdatePublishTime sets the "publish_time" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdatePublishTime() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdatePublishTime()
	})
}

// ClearPublishTime clears the value of the "publish_time" field.
func (u *NewsSentimentUpsertBulk) ClearPublishTime() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearPublishTime()
	})
}

// SetSentimentScore sets the "sentiment_score" field.
func (u *NewsSentimentUpsertBulk) SetSentimentScore(v float64) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSentimentScore(v)
	})
}

// AddSentimentScore adds v to the "sentiment_score" field.
func (u *NewsSentimentUpsertBulk) AddSentimentScore(v float64) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddSentimentScore(v)
	})
}

// UpdateSentimentScore sets the "sentiment_score" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateSentimentScore() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSentimentScore()
	})
}

// ClearSentimentScore clears the value of the "sentiment_score" field.
func (u *NewsSentimentUpsertBulk) ClearSentimentScore() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearSentimentScore()
	})
}

// SetImportance sets the "importance" field.
func (u *NewsSentimentUpsertBulk) SetImportance(v int) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetImportance(v)
	})
}

// AddImportance adds v to the "importance" field.
func (u *NewsSentimentUpsertBulk) AddImportance(v int) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddImportance(v)
	})
}

// UpdateImportance sets the "importance" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateImportance() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateImportance()
	})
}

// SetStockCode sets the "stock_code" field.
func (u *NewsSentimentUpsertBulk) SetStockCode(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetStockCode(v)
	})
}

// UpdateStockCode sets the "stock_code" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateStockCode() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateStockCode()
	})
}

// ClearStockCode clears the value of the "stock_code" field.
func (u *NewsSentimentUpsertBulk) ClearStockCode() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearStockCode()
	})
}

// SetKind sets the "kind" field.
func (u *NewsSentimentUpsertBulk) SetKind(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateKind() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateKind()
	})
}

// SetSourceID sets the "source_id" field.
func (u *NewsSentimentUpsertBulk) SetSourceID(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateSourceID() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSourceID()
	})
}

// SetURL sets the "url" field.
func (u *NewsSentimentUpsertBulk) SetURL(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateURL() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateURL()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *NewsSentimentUpsertBulk) SetContentHash(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateContentHash() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *NewsSentimentUpsertBulk) ClearContentHash() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearContentHash()
	})
}

// SetSourceCodes sets the "source_codes" field.
func (u *NewsSentimentUpsertBulk) SetSourceCodes(v []string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSourceCodes(v)
	})
}

// UpdateSourceCodes sets the "source_codes" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateSourceCodes() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSourceCodes()
	})
}

// ClearSourceCodes clears the value of the "source_codes" field.
func (u *NewsSentimentUpsertBulk) ClearSourceCodes() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearSourceCodes()
	})
}

// SetSimhash sets the "simhash" field.
func (u *NewsSentimentUpsertBulk) SetSimhash(v int64) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetSimhash(v)
	})
}

// AddSimhash adds v to the "simhash" field.
func (u *NewsSentimentUpsertBulk) AddSimhash(v int64) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddSimhash(v)
	})
}

// UpdateSimhash sets the "simhash" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateSimhash() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateSimhash()
	})
}

// SetClusterID sets the "cluster_id" field.
func (u *NewsSentimentUpsertBulk) SetClusterID(v int) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetClusterID(v)
	})
}

// AddClusterID adds v to the "cluster_id" field.
func (u *NewsSentimentUpsertBulk) AddClusterID(v int) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddClusterID(v)
	})
}

// UpdateClusterID sets the "cluster_id" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateClusterID() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateClusterID()
	})
}

// ClearClusterID clears the value of the "cluster_id" field.
func (u *NewsSentimentUpsertBulk) ClearClusterID() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearClusterID()
	})
}

// SetEventType sets the "event_type" field.
func (u *NewsSentimentUpsertBulk) SetEventType(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateEventType() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateEventType()
	})
}

// SetHalfLifeMinutes sets the "half_life_minutes" field.
func (u *NewsSentimentUpsertBulk) SetHalfLifeMinutes(v int) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetHalfLifeMinutes(v)
	})
}

// AddHalfLifeMinutes adds v to the "half_life_minutes" field.
func (u *NewsSentimentUpsertBulk) AddHalfLifeMinutes(v int) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.AddHalfLifeMinutes(v)
	})
}

// UpdateHalfLifeMinutes sets the "half_life_minutes" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateHalfLifeMinutes() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateHalfLifeMinutes()
	})
}

// SetScorer sets the "scorer" field.
func (u *NewsSentimentUpsertBulk) SetScorer(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetScorer(v)
	})
}

// UpdateScorer sets the "scorer" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateScorer() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateScorer()
	})
}

// SetDegraded sets the "degraded" field.
func (u *NewsSentimentUpsertBulk) SetDegraded(v bool) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetDegraded(v)
	})
}

// UpdateDegraded sets the "degraded" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateDegraded() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateDegraded()
	})
}

// SetStatus sets the "status" field.
func (u *NewsSentimentUpsertBulk) SetStatus(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateStatus() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *NewsSentimentUpsertBulk) SetReason(v string) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateReason() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateReason()
	})
}

// SetPublishTimeGuessed sets the "publish_time_guessed" field.
func (u *NewsSentimentUpsertBulk) SetPublishTimeGuessed(v bool) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetPublishTimeGuessed(v)
	})
}

// UpdatePublishTimeGuessed sets the "publish_time_guessed" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdatePublishTimeGuessed() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdatePublishTimeGuessed()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *NewsSentimentUpsertBulk) SetReceivedAt(v time.Time) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateReceivedAt() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetScoredAt sets the "scored_at" field.
func (u *NewsSentimentUpsertBulk) SetScoredAt(v time.Time) *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.SetScoredAt(v)
	})
}

// UpdateScoredAt sets the "scored_at" field to the value that was provided on create.
func (u *NewsSentimentUpsertBulk) UpdateScoredAt() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.UpdateScoredAt()
	})
}

// ClearScoredAt clears the value of the "scored_at" field.
func (u *NewsSentimentUpsertBulk) ClearScoredAt() *NewsSentimentUpsertBulk {
	return u.Update(func(s *NewsSentimentUpsert) {
		s.ClearScoredAt()
	})
}

// Exec executes the query.
func (u *NewsSentimentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NewsSentimentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NewsSentimentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NewsSentimentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
