// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/ent/overseasquote"
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OverseasQuoteDelete is the builder for deleting a OverseasQuote entity.
type OverseasQuoteDelete struct {
	config
	hooks    []Hook
	mutation *OverseasQuoteMutation
}

// Where appends a list predicates to the OverseasQuoteDelete builder.
func (_d *OverseasQuoteDelete) Where(ps ...predicate.OverseasQuote) *OverseasQuoteDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OverseasQuoteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OverseasQuoteDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OverseasQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(overseasquote.Table, sqlgraph.NewFieldSpec(overseasquote.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OverseasQuoteDeleteOne is the builder for deleting a single OverseasQuote entity.
type OverseasQuoteDeleteOne struct {
	_d *OverseasQuoteDelete
}

// Where appends a list predicates to the OverseasQuoteDelete builder.
func (_d *OverseasQuoteDeleteOne) Where(ps ...predicate.OverseasQuote) *OverseasQuoteDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OverseasQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{overseasquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OverseasQuoteDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
