// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/position"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PositionCreate is the builder for creating a Position entity.
type PositionCreate struct {
	config
	mutation *PositionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBook sets the "book" field.
func (_c *PositionCreate) SetBook(v string) *PositionCreate {
	_c.mutation.SetBook(v)
	return _c
}

// SetNillableBook sets the "book" field if the given value is not nil.
func (_c *PositionCreate) SetNillableBook(v *string) *PositionCreate {
	if v != nil {
		_c.SetBook(*v)
	}
	return _c
}

// SetSymbol sets the "symbol" field.
func (_c *PositionCreate) SetSymbol(v string) *PositionCreate {
	_c.mutation.SetSymbol(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *PositionCreate) SetQuantity(v int) *PositionCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *PositionCreate) SetNillableQuantity(v *int) *PositionCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetAvailable sets the "available" field.
func (_c *PositionCreate) SetAvailable(v int) *PositionCreate {
	_c.mutation.SetAvailable(v)
	return _c
}

// SetNillableAvailable sets the "available" field if the given value is not nil.
func (_c *PositionCreate) SetNillableAvailable(v *int) *PositionCreate {
	if v != nil {
		_c.SetAvailable(*v)
	}
	return _c
}

// SetAvgCost sets the "avg_cost" field.
func (_c *PositionCreate) SetAvgCost(v float64) *PositionCreate {
	_c.mutation.SetAvgCost(v)
	return _c
}

// SetNillableAvgCost sets the "avg_cost" field if the given value is not nil.
func (_c *PositionCreate) SetNillableAvgCost(v *float64) *PositionCreate {
	if v != nil {
		_c.SetAvgCost(*v)
	}
	return _c
}

// SetCurrentPrice sets the "current_price" field.
func (_c *PositionCreate) SetCurrentPrice(v float64) *PositionCreate {
	_c.mutation.SetCurrentPrice(v)
	return _c
}

// SetNillableCurrentPrice sets the "current_price" field if the given value is not nil.
func (_c *PositionCreate) SetNillableCurrentPrice(v *float64) *PositionCreate {
	if v != nil {
		_c.SetCurrentPrice(*v)
	}
	return _c
}

// SetPnl sets the "pnl" field.
func (_c *PositionCreate) SetPnl(v float64) *PositionCreate {
	_c.mutation.SetPnl(v)
	return _c
}

// SetNillablePnl sets the "pnl" field if the given value is not nil.
func (_c *PositionCreate) SetNillablePnl(v *float64) *PositionCreate {
	if v != nil {
		_c.SetPnl(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PositionCreate) SetUpdatedAt(v time.Time) *PositionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PositionCreate) SetNillableUpdatedAt(v *time.Time) *PositionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PositionMutation object of the builder.
func (_c *PositionCreate) Mutation() *PositionMutation {
	return _c.mutation
}

// Save creates the Position in the database.
func (_c *PositionCreate) Save(ctx context.Context) (*Position, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PositionCreate) SaveX(ctx context.Context) *Position {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PositionCreate) defaults() {
	if _, ok := _c.mutation.Book(); !ok {
		v := position.DefaultBook
		_c.mutation.SetBook(v)
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		v := position.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.Available(); !ok {
		v := position.DefaultAvailable
		_c.mutation.SetAvailable(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := position.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PositionCreate) check() error {
	if _, ok := _c.mutation.Book(); !ok {
		return &ValidationError{Name: "book", err: errors.New(`ent: missing required field "Position.book"`)}
	}
	if v, ok := _c.mutation.Book(); ok {
		if err := position.BookValidator(v); err != nil {
			return &ValidationError{Name: "book", err: fmt.Errorf(`ent: validator failed for field "Position.book": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Symbol(); !ok {
		return &ValidationError{Name: "symbol", err: errors.New(`ent: missing required field "Position.symbol"`)}
	}
	if v, ok := _c.mutation.Symbol(); ok {
		if err := position.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Position.symbol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Position.quantity"`)}
	}
	if _, ok := _c.mutation.Available(); !ok {
		return &ValidationError{Name: "available", err: errors.New(`ent: missing required field "Position.available"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Position.updated_at"`)}
	}
	return nil
}

func (_c *PositionCreate) sqlSave(ctx context.Context) (*Position, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PositionCreate) createSpec() (*Position, *sqlgraph.CreateSpec) {
	var (
		_node = &Position{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(position.Table, sqlgraph.NewFieldSpec(position.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Book(); ok {
		_spec.SetField(position.FieldBook, field.TypeString, value)
		_node.Book = value
	}
	if value, ok := _c.mutation.Symbol(); ok {
		_spec.SetField(position.FieldSymbol, field.TypeString, value)
		_node.Symbol = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(position.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.Available(); ok {
		_spec.SetField(position.FieldAvailable, field.TypeInt, value)
		_node.Available = value
	}
	if value, ok := _c.mutation.AvgCost(); ok {
		_spec.SetField(position.FieldAvgCost, field.TypeFloat64, value)
		_node.AvgCost = &value
	}
	if value, ok := _c.mutation.CurrentPrice(); ok {
		_spec.SetField(position.FieldCurrentPrice, field.TypeFloat64, value)
		_node.CurrentPrice = &value
	}
	if value, ok := _c.mutation.Pnl(); ok {
		_spec.SetField(position.FieldPnl, field.TypeFloat64, value)
		_node.Pnl = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(position.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Position.Create().
//		SetBook(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PositionUpsert) {
//			SetBook(v+v).
//		}).
//		Exec(ctx)
func (_c *PositionCreate) OnConflict(opts ...sql.ConflictOption) *PositionUpsertOne {
	_c.conflict = opts
	return &PositionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Position.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PositionCreate) OnConflictColumns(columns ...string) *PositionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PositionUpsertOne{
		create: _c,
	}
}

type (
	// PositionUpsertOne is the builder for "upsert"-ing
	//  one Position node.
	PositionUpsertOne struct {
		create *PositionCreate
	}

	// PositionUpsert is the "OnConflict" setter.
	PositionUpsert struct {
		*sql.UpdateSet
	}
)

// SetBook sets the "book" field.
func (u *PositionUpsert) SetBook(v string) *PositionUpsert {
	u.Set(position.FieldBook, v)
	return u
}

// UpdateBook sets the "book" field to the value that was provided on create.
func (u *PositionUpsert) UpdateBook() *PositionUpsert {
	u.SetExcluded(position.FieldBook)
	return u
}

// SetSymbol sets the "symbol" field.
func (u *PositionUpsert) SetSymbol(v string) *PositionUpsert {
	u.Set(position.FieldSymbol, v)
	return u
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *PositionUpsert) UpdateSymbol() *PositionUpsert {
	u.SetExcluded(position.FieldSymbol)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *PositionUpsert) SetQuantity(v int) *PositionUpsert {
	u.Set(position.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *PositionUpsert) UpdateQuantity() *PositionUpsert {
	u.SetExcluded(position.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *PositionUpsert) AddQuantity(v int) *PositionUpsert {
	u.Add(position.FieldQuantity, v)
	return u
}

// SetAvailable sets the "available" field.
func (u *PositionUpsert) SetAvailable(v int) *PositionUpsert {
	u.Set(position.FieldAvailable, v)
	return u
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *PositionUpsert) UpdateAvailable() *PositionUpsert {
	u.SetExcluded(position.FieldAvailable)
	return u
}

// AddAvailable adds v to the "available" field.
func (u *PositionUpsert) AddAvailable(v int) *PositionUpsert {
	u.Add(position.FieldAvailable, v)
	return u
}

// SetAvgCost sets the "avg_cost" field.
func (u *PositionUpsert) SetAvgCost(v float64) *PositionUpsert {
	u.Set(position.FieldAvgCost, v)
	return u
}

// UpdateAvgCost sets the "avg_cost" field to the value that was provided on create.
func (u *PositionUpsert) UpdateAvgCost() *PositionUpsert {
	u.SetExcluded(position.FieldAvgCost)
	return u
}

// AddAvgCost adds v to the "avg_cost" field.
func (u *PositionUpsert) AddAvgCost(v float64) *PositionUpsert {
	u.Add(position.FieldAvgCost, v)
	return u
}

// ClearAvgCost clears the value of the "avg_cost" field.
func (u *PositionUpsert) ClearAvgCost() *PositionUpsert {
	u.SetNull(position.FieldAvgCost)
	return u
}

// SetCurrentPrice sets the "current_price" field.
func (u *PositionUpsert) SetCurrentPrice(v float64) *PositionUpsert {
	u.Set(position.FieldCurrentPrice, v)
	return u
}

// UpdateCurrentPrice sets the "current_price" field to the value that was provided on create.
func (u *PositionUpsert) UpdateCurrentPrice() *PositionUpsert {
	u.SetExcluded(position.FieldCurrentPrice)
	return u
}

// AddCurrentPrice adds v to the "current_price" field.
func (u *PositionUpsert) AddCurrentPrice(v float64) *PositionUpsert {
	u.Add(position.FieldCurrentPrice, v)
	return u
}

// ClearCurrentPrice clears the value of the "current_price" field.
func (u *PositionUpsert) ClearCurrentPrice() *PositionUpsert {
	u.SetNull(position.FieldCurrentPrice)
	return u
}

// SetPnl sets the "pnl" field.
func (u *PositionUpsert) SetPnl(v float64) *PositionUpsert {
	u.Set(position.FieldPnl, v)
	return u
}

// UpdatePnl sets the "pnl" field to the value that was provided on create.
func (u *PositionUpsert) UpdatePnl() *PositionUpsert {
	u.SetExcluded(position.FieldPnl)
	return u
}

// AddPnl adds v to the "pnl" field.
func (u *PositionUpsert) AddPnl(v float64) *PositionUpsert {
	u.Add(position.FieldPnl, v)
	return u
}

// ClearPnl clears the value of the "pnl" field.
func (u *PositionUpsert) ClearPnl() *PositionUpsert {
	u.SetNull(position.FieldPnl)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PositionUpsert) SetUpdatedAt(v time.Time) *PositionUpsert {
	u.Set(position.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PositionUpsert) UpdateUpdatedAt() *PositionUpsert {
	u.SetExcluded(position.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Position.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PositionUpsertOne) UpdateNewValues() *PositionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Position.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PositionUpsertOne) Ignore() *PositionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PositionUpsertOne) DoNothing() *PositionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PositionCreate.OnConflict
// documentation for more info.
func (u *PositionUpsertOne) Update(set func(*PositionUpsert)) *PositionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PositionUpsert{UpdateSet: update})
	}))
	return u
}

// SetBook sets the "book" field.
func (u *PositionUpsertOne) SetBook(v string) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.SetBook(v)
	})
}

// UpdateBook sets the "book" field to the value that was provided on create.
func (u *PositionUpsertOne) UpdateBook() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateBook()
	})
}

// SetSymbol sets the "symbol" field.
func (u *PositionUpsertOne) SetSymbol(v string) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *PositionUpsertOne) UpdateSymbol() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateSymbol()
	})
}

// SetQuantity sets the "quantity" field.
func (u *PositionUpsertOne) SetQuantity(v int) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *PositionUpsertOne) AddQuantity(v int) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *PositionUpsertOne) UpdateQuantity() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateQuantity()
	})
}

// SetAvailable sets the "available" field.
func (u *PositionUpsertOne) SetAvailable(v int) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.SetAvailable(v)
	})
}

// AddAvailable adds v to the "available" field.
func (u *PositionUpsertOne) AddAvailable(v int) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.AddAvailable(v)
	})
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *PositionUpsertOne) UpdateAvailable() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateAvailable()
	})
}

// SetAvgCost sets the "avg_cost" field.
func (u *PositionUpsertOne) SetAvgCost(v float64) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.SetAvgCost(v)
	})
}

// AddAvgCost adds v to the "avg_cost" field.
func (u *PositionUpsertOne) AddAvgCost(v float64) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.AddAvgCost(v)
	})
}

// UpdateAvgCost sets the "avg_cost" field to the value that was provided on create.
func (u *PositionUpsertOne) UpdateAvgCost() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateAvgCost()
	})
}

// ClearAvgCost clears the value of the "avg_cost" field.
func (u *PositionUpsertOne) ClearAvgCost() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.ClearAvgCost()
	})
}

// SetCurrentPrice sets the "current_price" field.
func (u *PositionUpsertOne) SetCurrentPrice(v float64) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.SetCurrentPrice(v)
	})
}

// AddCurrentPrice adds v to the "current_price" field.
func (u *PositionUpsertOne) AddCurrentPrice(v float64) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.AddCurrentPrice(v)
	})
}

// UpdateCurrentPrice sets the "current_price" field to the value that was provided on create.
func (u *PositionUpsertOne) UpdateCurrentPrice() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateCurrentPrice()
	})
}

// ClearCurrentPrice clears the value of the "current_price" field.
func (u *PositionUpsertOne) ClearCurrentPrice() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.ClearCurrentPrice()
	})
}

// SetPnl sets the "pnl" field.
func (u *PositionUpsertOne) SetPnl(v float64) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.SetPnl(v)
	})
}

// AddPnl adds v to the "pnl" field.
func (u *PositionUpsertOne) AddPnl(v float64) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.AddPnl(v)
	})
}

// UpdatePnl sets the "pnl" field to the value that was provided on create.
func (u *PositionUpsertOne) UpdatePnl() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.UpdatePnl()
	})
}

// ClearPnl clears the value of the "pnl" field.
func (u *PositionUpsertOne) ClearPnl() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.ClearPnl()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PositionUpsertOne) SetUpdatedAt(v time.Time) *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PositionUpsertOne) UpdateUpdatedAt() *PositionUpsertOne {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PositionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PositionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PositionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PositionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PositionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PositionCreateBulk is the builder for creating many Position entities in bulk.
type PositionCreateBulk struct {
	config
	err      error
	builders []*PositionCreate
	conflict []sql.ConflictOption
}

// Save creates the Position entities in the database.
func (_c *PositionCreateBulk) Save(ctx context.Context) ([]*Position, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Position, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PositionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PositionCreateBulk) SaveX(ctx context.Context) []*Position {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Position.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PositionUpsert) {
//			SetBook(v+v).
//		}).
//		Exec(ctx)
func (_c *PositionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PositionUpsertBulk {
	_c.conflict = opts
	return &PositionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Position.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PositionCreateBulk) OnConflictColumns(columns ...string) *PositionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PositionUpsertBulk{
		create: _c,
	}
}

// PositionUpsertBulk is the builder for "upsert"-ing
// a bulk of Position nodes.
type PositionUpsertBulk struct {
	create *PositionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Position.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PositionUpsertBulk) UpdateNewValues() *PositionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Position.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PositionUpsertBulk) Ignore() *PositionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PositionUpsertBulk) DoNothing() *PositionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PositionCreateBulk.OnConflict
// documentation for more info.
func (u *PositionUpsertBulk) Update(set func(*PositionUpsert)) *PositionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PositionUpsert{UpdateSet: update})
	}))
	return u
}

// SetBook sets the "book" field.
func (u *PositionUpsertBulk) SetBook(v string) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.SetBook(v)
	})
}

// UpdateBook sets the "book" field to the value that was provided on create.
func (u *PositionUpsertBulk) UpdateBook() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateBook()
	})
}

// SetSymbol sets the "symbol" field.
func (u *PositionUpsertBulk) SetSymbol(v string) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *PositionUpsertBulk) UpdateSymbol() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateSymbol()
	})
}

// SetQuantity sets the "quantity" field.
func (u *PositionUpsertBulk) SetQuantity(v int) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *PositionUpsertBulk) AddQuantity(v int) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *PositionUpsertBulk) UpdateQuantity() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateQuantity()
	})
}

// SetAvailable sets the "available" field.
func (u *PositionUpsertBulk) SetAvailable(v int) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.SetAvailable(v)
	})
}

// AddAvailable adds v to the "available" field.
func (u *PositionUpsertBulk) AddAvailable(v int) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.AddAvailable(v)
	})
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *PositionUpsertBulk) UpdateAvailable() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateAvailable()
	})
}

// SetAvgCost sets the "avg_cost" field.
func (u *PositionUpsertBulk) SetAvgCost(v float64) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.SetAvgCost(v)
	})
}

// AddAvgCost adds v to the "avg_cost" field.
func (u *PositionUpsertBulk) AddAvgCost(v float64) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.AddAvgCost(v)
	})
}

// UpdateAvgCost sets the "avg_cost" field to the value that was provided on create.
func (u *PositionUpsertBulk) UpdateAvgCost() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateAvgCost()
	})
}

// ClearAvgCost clears the value of the "avg_cost" field.
func (u *PositionUpsertBulk) ClearAvgCost() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.ClearAvgCost()
	})
}

// SetCurrentPrice sets the "current_price" field.
func (u *PositionUpsertBulk) SetCurrentPrice(v float64) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.SetCurrentPrice(v)
	})
}

// AddCurrentPrice adds v to the "current_price" field.
func (u *PositionUpsertBulk) AddCurrentPrice(v float64) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.AddCurrentPrice(v)
	})
}

// UpdateCurrentPrice sets the "current_price" field to the value that was provided on create.
func (u *PositionUpsertBulk) UpdateCurrentPrice() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateCurrentPrice()
	})
}

// ClearCurrentPrice clears the value of the "current_price" field.
func (u *PositionUpsertBulk) ClearCurrentPrice() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.ClearCurrentPrice()
	})
}

// SetPnl sets the "pnl" field.
func (u *PositionUpsertBulk) SetPnl(v float64) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.SetPnl(v)
	})
}

// AddPnl adds v to the "pnl" field.
func (u *PositionUpsertBulk) AddPnl(v float64) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.AddPnl(v)
	})
}

// UpdatePnl sets the "pnl" field to the value that was provided on create.
func (u *PositionUpsertBulk) UpdatePnl() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.UpdatePnl()
	})
}

// ClearPnl clears the value of the "pnl" field.
func (u *PositionUpsertBulk) ClearPnl() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.ClearPnl()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PositionUpsertBulk) SetUpdatedAt(v time.Time) *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PositionUpsertBulk) UpdateUpdatedAt() *PositionUpsertBulk {
	return u.Update(func(s *PositionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PositionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PositionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PositionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PositionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
