// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/ent/predicate"
	"server/ent/sectormember"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SectorMemberDelete is the builder for deleting a SectorMember entity.
type SectorMemberDelete struct {
	config
	hooks    []Hook
	mutation *SectorMemberMutation
}

// Where appends a list predicates to the SectorMemberDelete builder.
func (_d *SectorMemberDelete) Where(ps ...predicate.SectorMember) *SectorMemberDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SectorMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SectorMemberDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SectorMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sectormember.Table, sqlgraph.NewFieldSpec(sectormember.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SectorMemberDeleteOne is the builder for deleting a single SectorMember entity.
type SectorMemberDeleteOne struct {
	_d *SectorMemberDelete
}

// Where appends a list predicates to the SectorMemberDelete builder.
func (_d *SectorMemberDeleteOne) Where(ps ...predicate.SectorMember) *SectorMemberDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SectorMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sectormember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SectorMemberDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
