// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/predicate"
	"server/ent/strategylibrary"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StrategyLibraryUpdate is the builder for updating StrategyLibrary entities.
type StrategyLibraryUpdate struct {
	config
	hooks    []Hook
	mutation *StrategyLibraryMutation
}

// Where appends a list predicates to the StrategyLibraryUpdate builder.
func (_u *StrategyLibraryUpdate) Where(ps ...predicate.StrategyLibrary) *StrategyLibraryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *StrategyLibraryUpdate) SetName(v string) *StrategyLibraryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StrategyLibraryUpdate) SetNillableName(v *string) *StrategyLibraryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *StrategyLibraryUpdate) SetDescription(v string) *StrategyLibraryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StrategyLibraryUpdate) SetNillableDescription(v *string) *StrategyLibraryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *StrategyLibraryUpdate) ClearDescription() *StrategyLibraryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCode sets the "code" field.
func (_u *StrategyLibraryUpdate) SetCode(v string) *StrategyLibraryUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *StrategyLibraryUpdate) SetNillableCode(v *string) *StrategyLibraryUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *StrategyLibraryUpdate) ClearCode() *StrategyLibraryUpdate {
	_u.mutation.ClearCode()
	return _u
}

// SetBacktestResult sets the "backtest_result" field.
func (_u *StrategyLibraryUpdate) SetBacktestResult(v map[string]interface{}) *StrategyLibraryUpdate {
	_u.mutation.SetBacktestResult(v)
	return _u
}

// ClearBacktestResult clears the value of the "backtest_result" field.
func (_u *StrategyLibraryUpdate) ClearBacktestResult() *StrategyLibraryUpdate {
	_u.mutation.ClearBacktestResult()
	return _u
}

// SetStatus sets the "status" field.
func (_u *StrategyLibraryUpdate) SetStatus(v string) *StrategyLibraryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StrategyLibraryUpdate) SetNillableStatus(v *string) *StrategyLibraryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the StrategyLibraryMutation object of the builder.
func (_u *StrategyLibraryUpdate) Mutation() *StrategyLibraryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StrategyLibraryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyLibraryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StrategyLibraryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyLibraryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StrategyLibraryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := strategylibrary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StrategyLibrary.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := strategylibrary.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StrategyLibrary.status": %w`, err)}
		}
	}
	return nil
}

func (_u *StrategyLibraryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategylibrary.Table, strategylibrary.Columns, sqlgraph.NewFieldSpec(strategylibrary.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(strategylibrary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(strategylibrary.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(strategylibrary.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(strategylibrary.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(strategylibrary.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.BacktestResult(); ok {
		_spec.SetField(strategylibrary.FieldBacktestResult, field.TypeJSON, value)
	}
	if _u.mutation.BacktestResultCleared() {
		_spec.ClearField(strategylibrary.FieldBacktestResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(strategylibrary.FieldStatus, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategylibrary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StrategyLibraryUpdateOne is the builder for updating a single StrategyLibrary entity.
type StrategyLibraryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StrategyLibraryMutation
}

// SetName sets the "name" field.
func (_u *StrategyLibraryUpdateOne) SetName(v string) *StrategyLibraryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StrategyLibraryUpdateOne) SetNillableName(v *string) *StrategyLibraryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *StrategyLibraryUpdateOne) SetDescription(v string) *StrategyLibraryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StrategyLibraryUpdateOne) SetNillableDescription(v *string) *StrategyLibraryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *StrategyLibraryUpdateOne) ClearDescription() *StrategyLibraryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCode sets the "code" field.
func (_u *StrategyLibraryUpdateOne) SetCode(v string) *StrategyLibraryUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *StrategyLibraryUpdateOne) SetNillableCode(v *string) *StrategyLibraryUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *StrategyLibraryUpdateOne) ClearCode() *StrategyLibraryUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// SetBacktestResult sets the "backtest_result" field.
func (_u *StrategyLibraryUpdateOne) SetBacktestResult(v map[string]interface{}) *StrategyLibraryUpdateOne {
	_u.mutation.SetBacktestResult(v)
	return _u
}

// ClearBacktestResult clears the value of the "backtest_result" field.
func (_u *StrategyLibraryUpdateOne) ClearBacktestResult() *StrategyLibraryUpdateOne {
	_u.mutation.ClearBacktestResult()
	return _u
}

// SetStatus sets the "status" field.
func (_u *StrategyLibraryUpdateOne) SetStatus(v string) *StrategyLibraryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StrategyLibraryUpdateOne) SetNillableStatus(v *string) *StrategyLibraryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the StrategyLibraryMutation object of the builder.
func (_u *StrategyLibraryUpdateOne) Mutation() *StrategyLibraryMutation {
	return _u.mutation
}

// Where appends a list predicates to the StrategyLibraryUpdate builder.
func (_u *StrategyLibraryUpdateOne) Where(ps ...predicate.StrategyLibrary) *StrategyLibraryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StrategyLibraryUpdateOne) Select(field string, fields ...string) *StrategyLibraryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StrategyLibrary entity.
func (_u *StrategyLibraryUpdateOne) Save(ctx context.Context) (*StrategyLibrary, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyLibraryUpdateOne) SaveX(ctx context.Context) *StrategyLibrary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StrategyLibraryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyLibraryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StrategyLibraryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := strategylibrary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StrategyLibrary.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := strategylibrary.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StrategyLibrary.status": %w`, err)}
		}
	}
	return nil
}

func (_u *StrategyLibraryUpdateOne) sqlSave(ctx context.Context) (_node *StrategyLibrary, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategylibrary.Table, strategylibrary.Columns, sqlgraph.NewFieldSpec(strategylibrary.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StrategyLibrary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, strategylibrary.FieldID)
		for _, f := range fields {
			if !strategylibrary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != strategylibrary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(strategylibrary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(strategylibrary.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(strategylibrary.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(strategylibrary.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(strategylibrary.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.BacktestResult(); ok {
		_spec.SetField(strategylibrary.FieldBacktestResult, field.TypeJSON, value)
	}
	if _u.mutation.BacktestResultCleared() {
		_spec.ClearField(strategylibrary.FieldBacktestResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(strategylibrary.FieldStatus, field.TypeString, value)
	}
	_node = &StrategyLibrary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategylibrary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
