// Code generated by ent, DO NOT EDIT.

package introspection

import (
	"server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldID, id))
}

// TradeDate applies equality check predicate on the "trade_date" field. It's identical to TradeDateEQ.
func TradeDate(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldTradeDate, v))
}

// Book applies equality check predicate on the "book" field. It's identical to BookEQ.
func Book(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldBook, v))
}

// WindowDays applies equality check predicate on the "window_days" field. It's identical to WindowDaysEQ.
func WindowDays(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldWindowDays, v))
}

// SampleCount applies equality check predicate on the "sample_count" field. It's identical to SampleCountEQ.
func SampleCount(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldSampleCount, v))
}

// WinRate applies equality check predicate on the "win_rate" field. It's identical to WinRateEQ.
func WinRate(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldWinRate, v))
}

// AvgReturn applies equality check predicate on the "avg_return" field. It's identical to AvgReturnEQ.
func AvgReturn(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldAvgReturn, v))
}

// MaxDrawdown applies equality check predicate on the "max_drawdown" field. It's identical to MaxDrawdownEQ.
func MaxDrawdown(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldMaxDrawdown, v))
}

// MissedCount applies equality check predicate on the "missed_count" field. It's identical to MissedCountEQ.
func MissedCount(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldMissedCount, v))
}

// Triggered applies equality check predicate on the "triggered" field. It's identical to TriggeredEQ.
func Triggered(v bool) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldTriggered, v))
}

// TriggerReason applies equality check predicate on the "trigger_reason" field. It's identical to TriggerReasonEQ.
func TriggerReason(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldTriggerReason, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldTaskID, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldCreatedAt, v))
}

// TradeDateEQ applies the EQ predicate on the "trade_date" field.
func TradeDateEQ(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldTradeDate, v))
}

// TradeDateNEQ applies the NEQ predicate on the "trade_date" field.
func TradeDateNEQ(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldTradeDate, v))
}

// TradeDateIn applies the In predicate on the "trade_date" field.
func TradeDateIn(vs ...time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldTradeDate, vs...))
}

// TradeDateNotIn applies the NotIn predicate on the "trade_date" field.
func TradeDateNotIn(vs ...time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldTradeDate, vs...))
}

// TradeDateGT applies the GT predicate on the "trade_date" field.
func TradeDateGT(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldTradeDate, v))
}

// TradeDateGTE applies the GTE predicate on the "trade_date" field.
func TradeDateGTE(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldTradeDate, v))
}

// TradeDateLT applies the LT predicate on the "trade_date" field.
func TradeDateLT(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldTradeDate, v))
}

// TradeDateLTE applies the LTE predicate on the "trade_date" field.
func TradeDateLTE(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldTradeDate, v))
}

// BookEQ applies the EQ predicate on the "book" field.
func BookEQ(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldBook, v))
}

// BookNEQ applies the NEQ predicate on the "book" field.
func BookNEQ(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldBook, v))
}

// BookIn applies the In predicate on the "book" field.
func BookIn(vs ...string) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldBook, vs...))
}

// BookNotIn applies the NotIn predicate on the "book" field.
func BookNotIn(vs ...string) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldBook, vs...))
}

// BookGT applies the GT predicate on the "book" field.
func BookGT(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldBook, v))
}

// BookGTE applies the GTE predicate on the "book" field.
func BookGTE(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldBook, v))
}

// BookLT applies the LT predicate on the "book" field.
func BookLT(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldBook, v))
}

// BookLTE applies the LTE predicate on the "book" field.
func BookLTE(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldBook, v))
}

// BookContains applies the Contains predicate on the "book" field.
func BookContains(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldContains(FieldBook, v))
}

// BookHasPrefix applies the HasPrefix predicate on the "book" field.
func BookHasPrefix(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldHasPrefix(FieldBook, v))
}

// BookHasSuffix applies the HasSuffix predicate on the "book" field.
func BookHasSuffix(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldHasSuffix(FieldBook, v))
}

// BookEqualFold applies the EqualFold predicate on the "book" field.
func BookEqualFold(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldEqualFold(FieldBook, v))
}

// BookContainsFold applies the ContainsFold predicate on the "book" field.
func BookContainsFold(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldContainsFold(FieldBook, v))
}

// WindowDaysEQ applies the EQ predicate on the "window_days" field.
func WindowDaysEQ(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldWindowDays, v))
}

// WindowDaysNEQ applies the NEQ predicate on the "window_days" field.
func WindowDaysNEQ(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldWindowDays, v))
}

// WindowDaysIn applies the In predicate on the "window_days" field.
func WindowDaysIn(vs ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldWindowDays, vs...))
}

// WindowDaysNotIn applies the NotIn predicate on the "window_days" field.
func WindowDaysNotIn(vs ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldWindowDays, vs...))
}

// WindowDaysGT applies the GT predicate on the "window_days" field.
func WindowDaysGT(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldWindowDays, v))
}

// WindowDaysGTE applies the GTE predicate on the "window_days" field.
func WindowDaysGTE(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldWindowDays, v))
}

// WindowDaysLT applies the LT predicate on the "window_days" field.
func WindowDaysLT(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldWindowDays, v))
}

// WindowDaysLTE applies the LTE predicate on the "window_days" field.
func WindowDaysLTE(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldWindowDays, v))
}

// SampleCountEQ applies the EQ predicate on the "sample_count" field.
func SampleCountEQ(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldSampleCount, v))
}

// SampleCountNEQ applies the NEQ predicate on the "sample_count" field.
func SampleCountNEQ(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldSampleCount, v))
}

// SampleCountIn applies the In predicate on the "sample_count" field.
func SampleCountIn(vs ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldSampleCount, vs...))
}

// SampleCountNotIn applies the NotIn predicate on the "sample_count" field.
func SampleCountNotIn(vs ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldSampleCount, vs...))
}

// SampleCountGT applies the GT predicate on the "sample_count" field.
func SampleCountGT(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldSampleCount, v))
}

// SampleCountGTE applies the GTE predicate on the "sample_count" field.
func SampleCountGTE(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldSampleCount, v))
}

// SampleCountLT applies the LT predicate on the "sample_count" field.
func SampleCountLT(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldSampleCount, v))
}

// SampleCountLTE applies the LTE predicate on the "sample_count" field.
func SampleCountLTE(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldSampleCount, v))
}

// WinRateEQ applies the EQ predicate on the "win_rate" field.
func WinRateEQ(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldWinRate, v))
}

// WinRateNEQ applies the NEQ predicate on the "win_rate" field.
func WinRateNEQ(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldWinRate, v))
}

// WinRateIn applies the In predicate on the "win_rate" field.
func WinRateIn(vs ...float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldWinRate, vs...))
}

// WinRateNotIn applies the NotIn predicate on the "win_rate" field.
func WinRateNotIn(vs ...float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldWinRate, vs...))
}

// WinRateGT applies the GT predicate on the "win_rate" field.
func WinRateGT(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldWinRate, v))
}

// WinRateGTE applies the GTE predicate on the "win_rate" field.
func WinRateGTE(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldWinRate, v))
}

// WinRateLT applies the LT predicate on the "win_rate" field.
func WinRateLT(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldWinRate, v))
}

// WinRateLTE applies the LTE predicate on the "win_rate" field.
func WinRateLTE(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldWinRate, v))
}

// AvgReturnEQ applies the EQ predicate on the "avg_return" field.
func AvgReturnEQ(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldAvgReturn, v))
}

// AvgReturnNEQ applies the NEQ predicate on the "avg_return" field.
func AvgReturnNEQ(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldAvgReturn, v))
}

// AvgReturnIn applies the In predicate on the "avg_return" field.
func AvgReturnIn(vs ...float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldAvgReturn, vs...))
}

// AvgReturnNotIn applies the NotIn predicate on the "avg_return" field.
func AvgReturnNotIn(vs ...float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldAvgReturn, vs...))
}

// AvgReturnGT applies the GT predicate on the "avg_return" field.
func AvgReturnGT(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldAvgReturn, v))
}

// AvgReturnGTE applies the GTE predicate on the "avg_return" field.
func AvgReturnGTE(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldAvgReturn, v))
}

// AvgReturnLT applies the LT predicate on the "avg_return" field.
func AvgReturnLT(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldAvgReturn, v))
}

// AvgReturnLTE applies the LTE predicate on the "avg_return" field.
func AvgReturnLTE(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldAvgReturn, v))
}

// MaxDrawdownEQ applies the EQ predicate on the "max_drawdown" field.
func MaxDrawdownEQ(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldMaxDrawdown, v))
}

// MaxDrawdownNEQ applies the NEQ predicate on the "max_drawdown" field.
func MaxDrawdownNEQ(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldMaxDrawdown, v))
}

// MaxDrawdownIn applies the In predicate on the "max_drawdown" field.
func MaxDrawdownIn(vs ...float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldMaxDrawdown, vs...))
}

// MaxDrawdownNotIn applies the NotIn predicate on the "max_drawdown" field.
func MaxDrawdownNotIn(vs ...float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldMaxDrawdown, vs...))
}

// MaxDrawdownGT applies the GT predicate on the "max_drawdown" field.
func MaxDrawdownGT(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldMaxDrawdown, v))
}

// MaxDrawdownGTE applies the GTE predicate on the "max_drawdown" field.
func MaxDrawdownGTE(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldMaxDrawdown, v))
}

// MaxDrawdownLT applies the LT predicate on the "max_drawdown" field.
func MaxDrawdownLT(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldMaxDrawdown, v))
}

// MaxDrawdownLTE applies the LTE predicate on the "max_drawdown" field.
func MaxDrawdownLTE(v float64) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldMaxDrawdown, v))
}

// MissedCountEQ applies the EQ predicate on the "missed_count" field.
func MissedCountEQ(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldMissedCount, v))
}

// MissedCountNEQ applies the NEQ predicate on the "missed_count" field.
func MissedCountNEQ(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldMissedCount, v))
}

// MissedCountIn applies the In predicate on the "missed_count" field.
func MissedCountIn(vs ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldMissedCount, vs...))
}

// MissedCountNotIn applies the NotIn predicate on the "missed_count" field.
func MissedCountNotIn(vs ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldMissedCount, vs...))
}

// MissedCountGT applies the GT predicate on the "missed_count" field.
func MissedCountGT(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldMissedCount, v))
}

// MissedCountGTE applies the GTE predicate on the "missed_count" field.
func MissedCountGTE(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldMissedCount, v))
}

// MissedCountLT applies the LT predicate on the "missed_count" field.
func MissedCountLT(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldMissedCount, v))
}

// MissedCountLTE applies the LTE predicate on the "missed_count" field.
func MissedCountLTE(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldMissedCount, v))
}

// AttributionIsNil applies the IsNil predicate on the "attribution" field.
func AttributionIsNil() predicate.Introspection {
	return predicate.Introspection(sql.FieldIsNull(FieldAttribution))
}

// AttributionNotNil applies the NotNil predicate on the "attribution" field.
func AttributionNotNil() predicate.Introspection {
	return predicate.Introspection(sql.FieldNotNull(FieldAttribution))
}

// TriggeredEQ applies the EQ predicate on the "triggered" field.
func TriggeredEQ(v bool) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldTriggered, v))
}

// TriggeredNEQ applies the NEQ predicate on the "triggered" field.
func TriggeredNEQ(v bool) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldTriggered, v))
}

// TriggerReasonEQ applies the EQ predicate on the "trigger_reason" field.
func TriggerReasonEQ(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldTriggerReason, v))
}

// TriggerReasonNEQ applies the NEQ predicate on the "trigger_reason" field.
func TriggerReasonNEQ(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldTriggerReason, v))
}

// TriggerReasonIn applies the In predicate on the "trigger_reason" field.
func TriggerReasonIn(vs ...string) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldTriggerReason, vs...))
}

// TriggerReasonNotIn applies the NotIn predicate on the "trigger_reason" field.
func TriggerReasonNotIn(vs ...string) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldTriggerReason, vs...))
}

// TriggerReasonGT applies the GT predicate on the "trigger_reason" field.
func TriggerReasonGT(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldTriggerReason, v))
}

// TriggerReasonGTE applies the GTE predicate on the "trigger_reason" field.
func TriggerReasonGTE(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldTriggerReason, v))
}

// TriggerReasonLT applies the LT predicate on the "trigger_reason" field.
func TriggerReasonLT(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldTriggerReason, v))
}

// TriggerReasonLTE applies the LTE predicate on the "trigger_reason" field.
func TriggerReasonLTE(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldTriggerReason, v))
}

// TriggerReasonContains applies the Contains predicate on the "trigger_reason" field.
func TriggerReasonContains(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldContains(FieldTriggerReason, v))
}

// TriggerReasonHasPrefix applies the HasPrefix predicate on the "trigger_reason" field.
func TriggerReasonHasPrefix(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldHasPrefix(FieldTriggerReason, v))
}

// TriggerReasonHasSuffix applies the HasSuffix predicate on the "trigger_reason" field.
func TriggerReasonHasSuffix(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldHasSuffix(FieldTriggerReason, v))
}

// TriggerReasonEqualFold applies the EqualFold predicate on the "trigger_reason" field.
func TriggerReasonEqualFold(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldEqualFold(FieldTriggerReason, v))
}

// TriggerReasonContainsFold applies the ContainsFold predicate on the "trigger_reason" field.
func TriggerReasonContainsFold(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldContainsFold(FieldTriggerReason, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v int) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDIsNil applies the IsNil predicate on the "task_id" field.
func TaskIDIsNil() predicate.Introspection {
	return predicate.Introspection(sql.FieldIsNull(FieldTaskID))
}

// TaskIDNotNil applies the NotNil predicate on the "task_id" field.
func TaskIDNotNil() predicate.Introspection {
	return predicate.Introspection(sql.FieldNotNull(FieldTaskID))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Introspection {
	return predicate.Introspection(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Introspection {
	return predicate.Introspection(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Introspection) predicate.Introspection {
	return predicate.Introspection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Introspection) predicate.Introspection {
	return predicate.Introspection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Introspection) predicate.Introspection {
	return predicate.Introspection(sql.NotPredicates(p))
}
