// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: api/backtest/v1/backtest.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Backtest_ListStrategies_FullMethodName     = "/api.backtest.v1.Backtest/ListStrategies"
	Backtest_CreateTask_FullMethodName         = "/api.backtest.v1.Backtest/CreateTask"
	Backtest_ListTasks_FullMethodName          = "/api.backtest.v1.Backtest/ListTasks"
	Backtest_GetTask_FullMethodName            = "/api.backtest.v1.Backtest/GetTask"
	Backtest_CancelTask_FullMethodName         = "/api.backtest.v1.Backtest/CancelTask"
	Backtest_RerunTask_FullMethodName          = "/api.backtest.v1.Backtest/RerunTask"
	Backtest_GetReport_FullMethodName          = "/api.backtest.v1.Backtest/GetReport"
	Backtest_ListTrades_FullMethodName         = "/api.backtest.v1.Backtest/ListTrades"
	Backtest_ShadowStats_FullMethodName        = "/api.backtest.v1.Backtest/ShadowStats"
	Backtest_ListIntrospections_FullMethodName = "/api.backtest.v1.Backtest/ListIntrospections"
	Backtest_RunIntrospection_FullMethodName   = "/api.backtest.v1.Backtest/RunIntrospection"
	Backtest_ListProposals_FullMethodName      = "/api.backtest.v1.Backtest/ListProposals"
	Backtest_ApproveProposal_FullMethodName    = "/api.backtest.v1.Backtest/ApproveProposal"
	Backtest_RejectProposal_FullMethodName     = "/api.backtest.v1.Backtest/RejectProposal"
	Backtest_RollbackStrategy_FullMethodName   = "/api.backtest.v1.Backtest/RollbackStrategy"
	Backtest_PeriodReport_FullMethodName       = "/api.backtest.v1.Backtest/PeriodReport"
	Backtest_Admission_FullMethodName          = "/api.backtest.v1.Backtest/Admission"
)

// BacktestClient is the client API for Backtest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Backtest 是 M07 回测与自进化。客户端经 admin /api/backtest/* 转发到 /v1/backtest/*。
// 时间字段为 RFC3339（上海时区），日期为 2006-01-02。比例都是小数。
type BacktestClient interface {
	// 已注册策略、参数范围和当前生效参数。
	ListStrategies(ctx context.Context, in *ListStrategiesRequest, opts ...grpc.CallOption) (*ListStrategiesReply, error)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksReply, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	CancelTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// 复制配置新建任务，结束后与原任务比对数据哈希和成交哈希。
	RerunTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	GetReport(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*ReportReply, error)
	ListTrades(ctx context.Context, in *ListTradesRequest, opts ...grpc.CallOption) (*ListTradesReply, error)
	ShadowStats(ctx context.Context, in *ShadowStatsRequest, opts ...grpc.CallOption) (*ShadowStatsReply, error)
	ListIntrospections(ctx context.Context, in *ListIntrospectionsRequest, opts ...grpc.CallOption) (*ListIntrospectionsReply, error)
	RunIntrospection(ctx context.Context, in *RunIntrospectionRequest, opts ...grpc.CallOption) (*Introspection, error)
	ListProposals(ctx context.Context, in *ListProposalsRequest, opts ...grpc.CallOption) (*ListProposalsReply, error)
	// 操作人取请求头 X-User，缺省 local。M11 完成后限 Owner 并写审计。
	ApproveProposal(ctx context.Context, in *DecideProposalRequest, opts ...grpc.CallOption) (*Proposal, error)
	RejectProposal(ctx context.Context, in *DecideProposalRequest, opts ...grpc.CallOption) (*Proposal, error)
	// 回到该策略最近一次批准前的参数版本。strategy_version 是全局快照，会恢复全部参数键。
	RollbackStrategy(ctx context.Context, in *RollbackStrategyRequest, opts ...grpc.CallOption) (*Proposal, error)
	PeriodReport(ctx context.Context, in *PeriodReportRequest, opts ...grpc.CallOption) (*PeriodReportReply, error)
	Admission(ctx context.Context, in *AdmissionRequest, opts ...grpc.CallOption) (*AdmissionReply, error)
}

type backtestClient struct {
	cc grpc.ClientConnInterface
}

func NewBacktestClient(cc grpc.ClientConnInterface) BacktestClient {
	return &backtestClient{cc}
}

func (c *backtestClient) ListStrategies(ctx context.Context, in *ListStrategiesRequest, opts ...grpc.CallOption) (*ListStrategiesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStrategiesReply)
	err := c.cc.Invoke(ctx, Backtest_ListStrategies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, Backtest_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksReply)
	err := c.cc.Invoke(ctx, Backtest_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, Backtest_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) CancelTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, Backtest_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) RerunTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, Backtest_RerunTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) GetReport(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*ReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportReply)
	err := c.cc.Invoke(ctx, Backtest_GetReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) ListTrades(ctx context.Context, in *ListTradesRequest, opts ...grpc.CallOption) (*ListTradesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTradesReply)
	err := c.cc.Invoke(ctx, Backtest_ListTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) ShadowStats(ctx context.Context, in *ShadowStatsRequest, opts ...grpc.CallOption) (*ShadowStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShadowStatsReply)
	err := c.cc.Invoke(ctx, Backtest_ShadowStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) ListIntrospections(ctx context.Context, in *ListIntrospectionsRequest, opts ...grpc.CallOption) (*ListIntrospectionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIntrospectionsReply)
	err := c.cc.Invoke(ctx, Backtest_ListIntrospections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) RunIntrospection(ctx context.Context, in *RunIntrospectionRequest, opts ...grpc.CallOption) (*Introspection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Introspection)
	err := c.cc.Invoke(ctx, Backtest_RunIntrospection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) ListProposals(ctx context.Context, in *ListProposalsRequest, opts ...grpc.CallOption) (*ListProposalsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProposalsReply)
	err := c.cc.Invoke(ctx, Backtest_ListProposals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) ApproveProposal(ctx context.Context, in *DecideProposalRequest, opts ...grpc.CallOption) (*Proposal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Proposal)
	err := c.cc.Invoke(ctx, Backtest_ApproveProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) RejectProposal(ctx context.Context, in *DecideProposalRequest, opts ...grpc.CallOption) (*Proposal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Proposal)
	err := c.cc.Invoke(ctx, Backtest_RejectProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) RollbackStrategy(ctx context.Context, in *RollbackStrategyRequest, opts ...grpc.CallOption) (*Proposal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Proposal)
	err := c.cc.Invoke(ctx, Backtest_RollbackStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) PeriodReport(ctx context.Context, in *PeriodReportRequest, opts ...grpc.CallOption) (*PeriodReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeriodReportReply)
	err := c.cc.Invoke(ctx, Backtest_PeriodReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestClient) Admission(ctx context.Context, in *AdmissionRequest, opts ...grpc.CallOption) (*AdmissionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmissionReply)
	err := c.cc.Invoke(ctx, Backtest_Admission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BacktestServer is the server API for Backtest service.
// All implementations must embed UnimplementedBacktestServer
// for forward compatibility.
//
// Backtest 是 M07 回测与自进化。客户端经 admin /api/backtest/* 转发到 /v1/backtest/*。
// 时间字段为 RFC3339（上海时区），日期为 2006-01-02。比例都是小数。
type BacktestServer interface {
	// 已注册策略、参数范围和当前生效参数。
	ListStrategies(context.Context, *ListStrategiesRequest) (*ListStrategiesReply, error)
	CreateTask(context.Context, *CreateTaskRequest) (*Task, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error)
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	CancelTask(context.Context, *GetTaskRequest) (*Task, error)
	// 复制配置新建任务，结束后与原任务比对数据哈希和成交哈希。
	RerunTask(context.Context, *GetTaskRequest) (*Task, error)
	GetReport(context.Context, *GetTaskRequest) (*ReportReply, error)
	ListTrades(context.Context, *ListTradesRequest) (*ListTradesReply, error)
	ShadowStats(context.Context, *ShadowStatsRequest) (*ShadowStatsReply, error)
	ListIntrospections(context.Context, *ListIntrospectionsRequest) (*ListIntrospectionsReply, error)
	RunIntrospection(context.Context, *RunIntrospectionRequest) (*Introspection, error)
	ListProposals(context.Context, *ListProposalsRequest) (*ListProposalsReply, error)
	// 操作人取请求头 X-User，缺省 local。M11 完成后限 Owner 并写审计。
	ApproveProposal(context.Context, *DecideProposalRequest) (*Proposal, error)
	RejectProposal(context.Context, *DecideProposalRequest) (*Proposal, error)
	// 回到该策略最近一次批准前的参数版本。strategy_version 是全局快照，会恢复全部参数键。
	RollbackStrategy(context.Context, *RollbackStrategyRequest) (*Proposal, error)
	PeriodReport(context.Context, *PeriodReportRequest) (*PeriodReportReply, error)
	Admission(context.Context, *AdmissionRequest) (*AdmissionReply, error)
	mustEmbedUnimplementedBacktestServer()
}

// UnimplementedBacktestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBacktestServer struct{}

func (UnimplementedBacktestServer) ListStrategies(context.Context, *ListStrategiesRequest) (*ListStrategiesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStrategies not implemented")
}
func (UnimplementedBacktestServer) CreateTask(context.Context, *CreateTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedBacktestServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedBacktestServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedBacktestServer) CancelTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedBacktestServer) RerunTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method RerunTask not implemented")
}
func (UnimplementedBacktestServer) GetReport(context.Context, *GetTaskRequest) (*ReportReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedBacktestServer) ListTrades(context.Context, *ListTradesRequest) (*ListTradesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrades not implemented")
}
func (UnimplementedBacktestServer) ShadowStats(context.Context, *ShadowStatsRequest) (*ShadowStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ShadowStats not implemented")
}
func (UnimplementedBacktestServer) ListIntrospections(context.Context, *ListIntrospectionsRequest) (*ListIntrospectionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIntrospections not implemented")
}
func (UnimplementedBacktestServer) RunIntrospection(context.Context, *RunIntrospectionRequest) (*Introspection, error) {
	return nil, status.Error(codes.Unimplemented, "method RunIntrospection not implemented")
}
func (UnimplementedBacktestServer) ListProposals(context.Context, *ListProposalsRequest) (*ListProposalsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProposals not implemented")
}
func (UnimplementedBacktestServer) ApproveProposal(context.Context, *DecideProposalRequest) (*Proposal, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveProposal not implemented")
}
func (UnimplementedBacktestServer) RejectProposal(context.Context, *DecideProposalRequest) (*Proposal, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectProposal not implemented")
}
func (UnimplementedBacktestServer) RollbackStrategy(context.Context, *RollbackStrategyRequest) (*Proposal, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackStrategy not implemented")
}
func (UnimplementedBacktestServer) PeriodReport(context.Context, *PeriodReportRequest) (*PeriodReportReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PeriodReport not implemented")
}
func (UnimplementedBacktestServer) Admission(context.Context, *AdmissionRequest) (*AdmissionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Admission not implemented")
}
func (UnimplementedBacktestServer) mustEmbedUnimplementedBacktestServer() {}
func (UnimplementedBacktestServer) testEmbeddedByValue()                  {}

// UnsafeBacktestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BacktestServer will
// result in compilation errors.
type UnsafeBacktestServer interface {
	mustEmbedUnimplementedBacktestServer()
}

func RegisterBacktestServer(s grpc.ServiceRegistrar, srv BacktestServer) {
	// If the following call panics, it indicates UnimplementedBacktestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Backtest_ServiceDesc, srv)
}

func _Backtest_ListStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStrategiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).ListStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_ListStrategies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).ListStrategies(ctx, req.(*ListStrategiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).CancelTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_RerunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).RerunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_RerunTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).RerunTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_GetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).GetReport(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_ListTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).ListTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_ListTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).ListTrades(ctx, req.(*ListTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_ShadowStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShadowStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).ShadowStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_ShadowStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).ShadowStats(ctx, req.(*ShadowStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_ListIntrospections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntrospectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).ListIntrospections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_ListIntrospections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).ListIntrospections(ctx, req.(*ListIntrospectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_RunIntrospection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunIntrospectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).RunIntrospection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_RunIntrospection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).RunIntrospection(ctx, req.(*RunIntrospectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_ListProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).ListProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_ListProposals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).ListProposals(ctx, req.(*ListProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_ApproveProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).ApproveProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_ApproveProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).ApproveProposal(ctx, req.(*DecideProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_RejectProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).RejectProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_RejectProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).RejectProposal(ctx, req.(*DecideProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_RollbackStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).RollbackStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_RollbackStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).RollbackStrategy(ctx, req.(*RollbackStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_PeriodReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeriodReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).PeriodReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_PeriodReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).PeriodReport(ctx, req.(*PeriodReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backtest_Admission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServer).Admission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backtest_Admission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServer).Admission(ctx, req.(*AdmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Backtest_ServiceDesc is the grpc.ServiceDesc for Backtest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backtest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.backtest.v1.Backtest",
	HandlerType: (*BacktestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStrategies",
			Handler:    _Backtest_ListStrategies_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _Backtest_CreateTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Backtest_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Backtest_GetTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _Backtest_CancelTask_Handler,
		},
		{
			MethodName: "RerunTask",
			Handler:    _Backtest_RerunTask_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _Backtest_GetReport_Handler,
		},
		{
			MethodName: "ListTrades",
			Handler:    _Backtest_ListTrades_Handler,
		},
		{
			MethodName: "ShadowStats",
			Handler:    _Backtest_ShadowStats_Handler,
		},
		{
			MethodName: "ListIntrospections",
			Handler:    _Backtest_ListIntrospections_Handler,
		},
		{
			MethodName: "RunIntrospection",
			Handler:    _Backtest_RunIntrospection_Handler,
		},
		{
			MethodName: "ListProposals",
			Handler:    _Backtest_ListProposals_Handler,
		},
		{
			MethodName: "ApproveProposal",
			Handler:    _Backtest_ApproveProposal_Handler,
		},
		{
			MethodName: "RejectProposal",
			Handler:    _Backtest_RejectProposal_Handler,
		},
		{
			MethodName: "RollbackStrategy",
			Handler:    _Backtest_RollbackStrategy_Handler,
		},
		{
			MethodName: "PeriodReport",
			Handler:    _Backtest_PeriodReport_Handler,
		},
		{
			MethodName: "Admission",
			Handler:    _Backtest_Admission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/backtest/v1/backtest.proto",
}
