// Code generated by ent, DO NOT EDIT.

package llmcalllog

import (
	"server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldID, id))
}

// TraceID applies equality check predicate on the "trace_id" field. It's identical to TraceIDEQ.
func TraceID(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldTraceID, v))
}

// Task applies equality check predicate on the "task" field. It's identical to TaskEQ.
func Task(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldTask, v))
}

// Tier applies equality check predicate on the "tier" field. It's identical to TierEQ.
func Tier(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldTier, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldModel, v))
}

// PromptVersion applies equality check predicate on the "prompt_version" field. It's identical to PromptVersionEQ.
func PromptVersion(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldPromptVersion, v))
}

// PromptHash applies equality check predicate on the "prompt_hash" field. It's identical to PromptHashEQ.
func PromptHash(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldPromptHash, v))
}

// InputDigest applies equality check predicate on the "input_digest" field. It's identical to InputDigestEQ.
func InputDigest(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldInputDigest, v))
}

// InputExcerpt applies equality check predicate on the "input_excerpt" field. It's identical to InputExcerptEQ.
func InputExcerpt(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldInputExcerpt, v))
}

// Output applies equality check predicate on the "output" field. It's identical to OutputEQ.
func Output(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldOutput, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldStatus, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldError, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldLatencyMs, v))
}

// QueueMs applies equality check predicate on the "queue_ms" field. It's identical to QueueMsEQ.
func QueueMs(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldQueueMs, v))
}

// PromptTokens applies equality check predicate on the "prompt_tokens" field. It's identical to PromptTokensEQ.
func PromptTokens(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldPromptTokens, v))
}

// CompletionTokens applies equality check predicate on the "completion_tokens" field. It's identical to CompletionTokensEQ.
func CompletionTokens(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldCompletionTokens, v))
}

// Attempt applies equality check predicate on the "attempt" field. It's identical to AttemptEQ.
func Attempt(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldAttempt, v))
}

// DecisionID applies equality check predicate on the "decision_id" field. It's identical to DecisionIDEQ.
func DecisionID(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldDecisionID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldCreatedAt, v))
}

// TraceIDEQ applies the EQ predicate on the "trace_id" field.
func TraceIDEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldTraceID, v))
}

// TraceIDNEQ applies the NEQ predicate on the "trace_id" field.
func TraceIDNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldTraceID, v))
}

// TraceIDIn applies the In predicate on the "trace_id" field.
func TraceIDIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldTraceID, vs...))
}

// TraceIDNotIn applies the NotIn predicate on the "trace_id" field.
func TraceIDNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldTraceID, vs...))
}

// TraceIDGT applies the GT predicate on the "trace_id" field.
func TraceIDGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldTraceID, v))
}

// TraceIDGTE applies the GTE predicate on the "trace_id" field.
func TraceIDGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldTraceID, v))
}

// TraceIDLT applies the LT predicate on the "trace_id" field.
func TraceIDLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldTraceID, v))
}

// TraceIDLTE applies the LTE predicate on the "trace_id" field.
func TraceIDLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldTraceID, v))
}

// TraceIDContains applies the Contains predicate on the "trace_id" field.
func TraceIDContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldTraceID, v))
}

// TraceIDHasPrefix applies the HasPrefix predicate on the "trace_id" field.
func TraceIDHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldTraceID, v))
}

// TraceIDHasSuffix applies the HasSuffix predicate on the "trace_id" field.
func TraceIDHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldTraceID, v))
}

// TraceIDEqualFold applies the EqualFold predicate on the "trace_id" field.
func TraceIDEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldTraceID, v))
}

// TraceIDContainsFold applies the ContainsFold predicate on the "trace_id" field.
func TraceIDContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldTraceID, v))
}

// TaskEQ applies the EQ predicate on the "task" field.
func TaskEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldTask, v))
}

// TaskNEQ applies the NEQ predicate on the "task" field.
func TaskNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldTask, v))
}

// TaskIn applies the In predicate on the "task" field.
func TaskIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldTask, vs...))
}

// TaskNotIn applies the NotIn predicate on the "task" field.
func TaskNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldTask, vs...))
}

// TaskGT applies the GT predicate on the "task" field.
func TaskGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldTask, v))
}

// TaskGTE applies the GTE predicate on the "task" field.
func TaskGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldTask, v))
}

// TaskLT applies the LT predicate on the "task" field.
func TaskLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldTask, v))
}

// TaskLTE applies the LTE predicate on the "task" field.
func TaskLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldTask, v))
}

// TaskContains applies the Contains predicate on the "task" field.
func TaskContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldTask, v))
}

// TaskHasPrefix applies the HasPrefix predicate on the "task" field.
func TaskHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldTask, v))
}

// TaskHasSuffix applies the HasSuffix predicate on the "task" field.
func TaskHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldTask, v))
}

// TaskEqualFold applies the EqualFold predicate on the "task" field.
func TaskEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldTask, v))
}

// TaskContainsFold applies the ContainsFold predicate on the "task" field.
func TaskContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldTask, v))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldTier, vs...))
}

// TierGT applies the GT predicate on the "tier" field.
func TierGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldTier, v))
}

// TierGTE applies the GTE predicate on the "tier" field.
func TierGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldTier, v))
}

// TierLT applies the LT predicate on the "tier" field.
func TierLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldTier, v))
}

// TierLTE applies the LTE predicate on the "tier" field.
func TierLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldTier, v))
}

// TierContains applies the Contains predicate on the "tier" field.
func TierContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldTier, v))
}

// TierHasPrefix applies the HasPrefix predicate on the "tier" field.
func TierHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldTier, v))
}

// TierHasSuffix applies the HasSuffix predicate on the "tier" field.
func TierHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldTier, v))
}

// TierEqualFold applies the EqualFold predicate on the "tier" field.
func TierEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldTier, v))
}

// TierContainsFold applies the ContainsFold predicate on the "tier" field.
func TierContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldTier, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldModel, v))
}

// PromptVersionEQ applies the EQ predicate on the "prompt_version" field.
func PromptVersionEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldPromptVersion, v))
}

// PromptVersionNEQ applies the NEQ predicate on the "prompt_version" field.
func PromptVersionNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldPromptVersion, v))
}

// PromptVersionIn applies the In predicate on the "prompt_version" field.
func PromptVersionIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldPromptVersion, vs...))
}

// PromptVersionNotIn applies the NotIn predicate on the "prompt_version" field.
func PromptVersionNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldPromptVersion, vs...))
}

// PromptVersionGT applies the GT predicate on the "prompt_version" field.
func PromptVersionGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldPromptVersion, v))
}

// PromptVersionGTE applies the GTE predicate on the "prompt_version" field.
func PromptVersionGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldPromptVersion, v))
}

// PromptVersionLT applies the LT predicate on the "prompt_version" field.
func PromptVersionLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldPromptVersion, v))
}

// PromptVersionLTE applies the LTE predicate on the "prompt_version" field.
func PromptVersionLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldPromptVersion, v))
}

// PromptVersionContains applies the Contains predicate on the "prompt_version" field.
func PromptVersionContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldPromptVersion, v))
}

// PromptVersionHasPrefix applies the HasPrefix predicate on the "prompt_version" field.
func PromptVersionHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldPromptVersion, v))
}

// PromptVersionHasSuffix applies the HasSuffix predicate on the "prompt_version" field.
func PromptVersionHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldPromptVersion, v))
}

// PromptVersionEqualFold applies the EqualFold predicate on the "prompt_version" field.
func PromptVersionEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldPromptVersion, v))
}

// PromptVersionContainsFold applies the ContainsFold predicate on the "prompt_version" field.
func PromptVersionContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldPromptVersion, v))
}

// PromptHashEQ applies the EQ predicate on the "prompt_hash" field.
func PromptHashEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldPromptHash, v))
}

// PromptHashNEQ applies the NEQ predicate on the "prompt_hash" field.
func PromptHashNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldPromptHash, v))
}

// PromptHashIn applies the In predicate on the "prompt_hash" field.
func PromptHashIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldPromptHash, vs...))
}

// PromptHashNotIn applies the NotIn predicate on the "prompt_hash" field.
func PromptHashNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldPromptHash, vs...))
}

// PromptHashGT applies the GT predicate on the "prompt_hash" field.
func PromptHashGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldPromptHash, v))
}

// PromptHashGTE applies the GTE predicate on the "prompt_hash" field.
func PromptHashGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldPromptHash, v))
}

// PromptHashLT applies the LT predicate on the "prompt_hash" field.
func PromptHashLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldPromptHash, v))
}

// PromptHashLTE applies the LTE predicate on the "prompt_hash" field.
func PromptHashLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldPromptHash, v))
}

// PromptHashContains applies the Contains predicate on the "prompt_hash" field.
func PromptHashContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldPromptHash, v))
}

// PromptHashHasPrefix applies the HasPrefix predicate on the "prompt_hash" field.
func PromptHashHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldPromptHash, v))
}

// PromptHashHasSuffix applies the HasSuffix predicate on the "prompt_hash" field.
func PromptHashHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldPromptHash, v))
}

// PromptHashEqualFold applies the EqualFold predicate on the "prompt_hash" field.
func PromptHashEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldPromptHash, v))
}

// PromptHashContainsFold applies the ContainsFold predicate on the "prompt_hash" field.
func PromptHashContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldPromptHash, v))
}

// InputDigestEQ applies the EQ predicate on the "input_digest" field.
func InputDigestEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldInputDigest, v))
}

// InputDigestNEQ applies the NEQ predicate on the "input_digest" field.
func InputDigestNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldInputDigest, v))
}

// InputDigestIn applies the In predicate on the "input_digest" field.
func InputDigestIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldInputDigest, vs...))
}

// InputDigestNotIn applies the NotIn predicate on the "input_digest" field.
func InputDigestNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldInputDigest, vs...))
}

// InputDigestGT applies the GT predicate on the "input_digest" field.
func InputDigestGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldInputDigest, v))
}

// InputDigestGTE applies the GTE predicate on the "input_digest" field.
func InputDigestGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldInputDigest, v))
}

// InputDigestLT applies the LT predicate on the "input_digest" field.
func InputDigestLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldInputDigest, v))
}

// InputDigestLTE applies the LTE predicate on the "input_digest" field.
func InputDigestLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldInputDigest, v))
}

// InputDigestContains applies the Contains predicate on the "input_digest" field.
func InputDigestContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldInputDigest, v))
}

// InputDigestHasPrefix applies the HasPrefix predicate on the "input_digest" field.
func InputDigestHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldInputDigest, v))
}

// InputDigestHasSuffix applies the HasSuffix predicate on the "input_digest" field.
func InputDigestHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldInputDigest, v))
}

// InputDigestEqualFold applies the EqualFold predicate on the "input_digest" field.
func InputDigestEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldInputDigest, v))
}

// InputDigestContainsFold applies the ContainsFold predicate on the "input_digest" field.
func InputDigestContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldInputDigest, v))
}

// InputExcerptEQ applies the EQ predicate on the "input_excerpt" field.
func InputExcerptEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldInputExcerpt, v))
}

// InputExcerptNEQ applies the NEQ predicate on the "input_excerpt" field.
func InputExcerptNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldInputExcerpt, v))
}

// InputExcerptIn applies the In predicate on the "input_excerpt" field.
func InputExcerptIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldInputExcerpt, vs...))
}

// InputExcerptNotIn applies the NotIn predicate on the "input_excerpt" field.
func InputExcerptNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldInputExcerpt, vs...))
}

// InputExcerptGT applies the GT predicate on the "input_excerpt" field.
func InputExcerptGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldInputExcerpt, v))
}

// InputExcerptGTE applies the GTE predicate on the "input_excerpt" field.
func InputExcerptGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldInputExcerpt, v))
}

// InputExcerptLT applies the LT predicate on the "input_excerpt" field.
func InputExcerptLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldInputExcerpt, v))
}

// InputExcerptLTE applies the LTE predicate on the "input_excerpt" field.
func InputExcerptLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldInputExcerpt, v))
}

// InputExcerptContains applies the Contains predicate on the "input_excerpt" field.
func InputExcerptContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldInputExcerpt, v))
}

// InputExcerptHasPrefix applies the HasPrefix predicate on the "input_excerpt" field.
func InputExcerptHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldInputExcerpt, v))
}

// InputExcerptHasSuffix applies the HasSuffix predicate on the "input_excerpt" field.
func InputExcerptHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldInputExcerpt, v))
}

// InputExcerptEqualFold applies the EqualFold predicate on the "input_excerpt" field.
func InputExcerptEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldInputExcerpt, v))
}

// InputExcerptContainsFold applies the ContainsFold predicate on the "input_excerpt" field.
func InputExcerptContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldInputExcerpt, v))
}

// OutputEQ applies the EQ predicate on the "output" field.
func OutputEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldOutput, v))
}

// OutputNEQ applies the NEQ predicate on the "output" field.
func OutputNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldOutput, v))
}

// OutputIn applies the In predicate on the "output" field.
func OutputIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldOutput, vs...))
}

// OutputNotIn applies the NotIn predicate on the "output" field.
func OutputNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldOutput, vs...))
}

// OutputGT applies the GT predicate on the "output" field.
func OutputGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldOutput, v))
}

// OutputGTE applies the GTE predicate on the "output" field.
func OutputGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldOutput, v))
}

// OutputLT applies the LT predicate on the "output" field.
func OutputLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldOutput, v))
}

// OutputLTE applies the LTE predicate on the "output" field.
func OutputLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldOutput, v))
}

// OutputContains applies the Contains predicate on the "output" field.
func OutputContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldOutput, v))
}

// OutputHasPrefix applies the HasPrefix predicate on the "output" field.
func OutputHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldOutput, v))
}

// OutputHasSuffix applies the HasSuffix predicate on the "output" field.
func OutputHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldOutput, v))
}

// OutputEqualFold applies the EqualFold predicate on the "output" field.
func OutputEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldOutput, v))
}

// OutputContainsFold applies the ContainsFold predicate on the "output" field.
func OutputContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldOutput, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldHasSuffix(FieldError, v))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldContainsFold(FieldError, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldLatencyMs, v))
}

// QueueMsEQ applies the EQ predicate on the "queue_ms" field.
func QueueMsEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldQueueMs, v))
}

// QueueMsNEQ applies the NEQ predicate on the "queue_ms" field.
func QueueMsNEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldQueueMs, v))
}

// QueueMsIn applies the In predicate on the "queue_ms" field.
func QueueMsIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldQueueMs, vs...))
}

// QueueMsNotIn applies the NotIn predicate on the "queue_ms" field.
func QueueMsNotIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldQueueMs, vs...))
}

// QueueMsGT applies the GT predicate on the "queue_ms" field.
func QueueMsGT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldQueueMs, v))
}

// QueueMsGTE applies the GTE predicate on the "queue_ms" field.
func QueueMsGTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldQueueMs, v))
}

// QueueMsLT applies the LT predicate on the "queue_ms" field.
func QueueMsLT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldQueueMs, v))
}

// QueueMsLTE applies the LTE predicate on the "queue_ms" field.
func QueueMsLTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldQueueMs, v))
}

// PromptTokensEQ applies the EQ predicate on the "prompt_tokens" field.
func PromptTokensEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldPromptTokens, v))
}

// PromptTokensNEQ applies the NEQ predicate on the "prompt_tokens" field.
func PromptTokensNEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldPromptTokens, v))
}

// PromptTokensIn applies the In predicate on the "prompt_tokens" field.
func PromptTokensIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldPromptTokens, vs...))
}

// PromptTokensNotIn applies the NotIn predicate on the "prompt_tokens" field.
func PromptTokensNotIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldPromptTokens, vs...))
}

// PromptTokensGT applies the GT predicate on the "prompt_tokens" field.
func PromptTokensGT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldPromptTokens, v))
}

// PromptTokensGTE applies the GTE predicate on the "prompt_tokens" field.
func PromptTokensGTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldPromptTokens, v))
}

// PromptTokensLT applies the LT predicate on the "prompt_tokens" field.
func PromptTokensLT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldPromptTokens, v))
}

// PromptTokensLTE applies the LTE predicate on the "prompt_tokens" field.
func PromptTokensLTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldPromptTokens, v))
}

// CompletionTokensEQ applies the EQ predicate on the "completion_tokens" field.
func CompletionTokensEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldCompletionTokens, v))
}

// CompletionTokensNEQ applies the NEQ predicate on the "completion_tokens" field.
func CompletionTokensNEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldCompletionTokens, v))
}

// CompletionTokensIn applies the In predicate on the "completion_tokens" field.
func CompletionTokensIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldCompletionTokens, vs...))
}

// CompletionTokensNotIn applies the NotIn predicate on the "completion_tokens" field.
func CompletionTokensNotIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldCompletionTokens, vs...))
}

// CompletionTokensGT applies the GT predicate on the "completion_tokens" field.
func CompletionTokensGT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldCompletionTokens, v))
}

// CompletionTokensGTE applies the GTE predicate on the "completion_tokens" field.
func CompletionTokensGTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldCompletionTokens, v))
}

// CompletionTokensLT applies the LT predicate on the "completion_tokens" field.
func CompletionTokensLT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldCompletionTokens, v))
}

// CompletionTokensLTE applies the LTE predicate on the "completion_tokens" field.
func CompletionTokensLTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldCompletionTokens, v))
}

// AttemptEQ applies the EQ predicate on the "attempt" field.
func AttemptEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldAttempt, v))
}

// AttemptNEQ applies the NEQ predicate on the "attempt" field.
func AttemptNEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldAttempt, v))
}

// AttemptIn applies the In predicate on the "attempt" field.
func AttemptIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldAttempt, vs...))
}

// AttemptNotIn applies the NotIn predicate on the "attempt" field.
func AttemptNotIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldAttempt, vs...))
}

// AttemptGT applies the GT predicate on the "attempt" field.
func AttemptGT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldAttempt, v))
}

// AttemptGTE applies the GTE predicate on the "attempt" field.
func AttemptGTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldAttempt, v))
}

// AttemptLT applies the LT predicate on the "attempt" field.
func AttemptLT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldAttempt, v))
}

// AttemptLTE applies the LTE predicate on the "attempt" field.
func AttemptLTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldAttempt, v))
}

// DecisionIDEQ applies the EQ predicate on the "decision_id" field.
func DecisionIDEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldDecisionID, v))
}

// DecisionIDNEQ applies the NEQ predicate on the "decision_id" field.
func DecisionIDNEQ(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldDecisionID, v))
}

// DecisionIDIn applies the In predicate on the "decision_id" field.
func DecisionIDIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldDecisionID, vs...))
}

// DecisionIDNotIn applies the NotIn predicate on the "decision_id" field.
func DecisionIDNotIn(vs ...int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldDecisionID, vs...))
}

// DecisionIDGT applies the GT predicate on the "decision_id" field.
func DecisionIDGT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldDecisionID, v))
}

// DecisionIDGTE applies the GTE predicate on the "decision_id" field.
func DecisionIDGTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldDecisionID, v))
}

// DecisionIDLT applies the LT predicate on the "decision_id" field.
func DecisionIDLT(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldDecisionID, v))
}

// DecisionIDLTE applies the LTE predicate on the "decision_id" field.
func DecisionIDLTE(v int) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldDecisionID, v))
}

// DecisionIDIsNil applies the IsNil predicate on the "decision_id" field.
func DecisionIDIsNil() predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIsNull(FieldDecisionID))
}

// DecisionIDNotNil applies the NotNil predicate on the "decision_id" field.
func DecisionIDNotNil() predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotNull(FieldDecisionID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LlmCallLog) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LlmCallLog) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LlmCallLog) predicate.LlmCallLog {
	return predicate.LlmCallLog(sql.NotPredicates(p))
}
