// Code generated by ent, DO NOT EDIT.

package intelfact

import (
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLTE(FieldID, id))
}

// NewsID applies equality check predicate on the "news_id" field. It's identical to NewsIDEQ.
func NewsID(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldNewsID, v))
}

// FactType applies equality check predicate on the "fact_type" field. It's identical to FactTypeEQ.
func FactType(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldFactType, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v float64) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldValue, v))
}

// Unit applies equality check predicate on the "unit" field. It's identical to UnitEQ.
func Unit(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldUnit, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldText, v))
}

// Start applies equality check predicate on the "start" field. It's identical to StartEQ.
func Start(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldStart, v))
}

// End applies equality check predicate on the "end" field. It's identical to EndEQ.
func End(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldEnd, v))
}

// NewsIDEQ applies the EQ predicate on the "news_id" field.
func NewsIDEQ(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldNewsID, v))
}

// NewsIDNEQ applies the NEQ predicate on the "news_id" field.
func NewsIDNEQ(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNEQ(FieldNewsID, v))
}

// NewsIDIn applies the In predicate on the "news_id" field.
func NewsIDIn(vs ...int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldIn(FieldNewsID, vs...))
}

// NewsIDNotIn applies the NotIn predicate on the "news_id" field.
func NewsIDNotIn(vs ...int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNotIn(FieldNewsID, vs...))
}

// NewsIDGT applies the GT predicate on the "news_id" field.
func NewsIDGT(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGT(FieldNewsID, v))
}

// NewsIDGTE applies the GTE predicate on the "news_id" field.
func NewsIDGTE(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGTE(FieldNewsID, v))
}

// NewsIDLT applies the LT predicate on the "news_id" field.
func NewsIDLT(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLT(FieldNewsID, v))
}

// NewsIDLTE applies the LTE predicate on the "news_id" field.
func NewsIDLTE(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLTE(FieldNewsID, v))
}

// FactTypeEQ applies the EQ predicate on the "fact_type" field.
func FactTypeEQ(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldFactType, v))
}

// FactTypeNEQ applies the NEQ predicate on the "fact_type" field.
func FactTypeNEQ(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNEQ(FieldFactType, v))
}

// FactTypeIn applies the In predicate on the "fact_type" field.
func FactTypeIn(vs ...string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldIn(FieldFactType, vs...))
}

// FactTypeNotIn applies the NotIn predicate on the "fact_type" field.
func FactTypeNotIn(vs ...string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNotIn(FieldFactType, vs...))
}

// FactTypeGT applies the GT predicate on the "fact_type" field.
func FactTypeGT(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGT(FieldFactType, v))
}

// FactTypeGTE applies the GTE predicate on the "fact_type" field.
func FactTypeGTE(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGTE(FieldFactType, v))
}

// FactTypeLT applies the LT predicate on the "fact_type" field.
func FactTypeLT(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLT(FieldFactType, v))
}

// FactTypeLTE applies the LTE predicate on the "fact_type" field.
func FactTypeLTE(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLTE(FieldFactType, v))
}

// FactTypeContains applies the Contains predicate on the "fact_type" field.
func FactTypeContains(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldContains(FieldFactType, v))
}

// FactTypeHasPrefix applies the HasPrefix predicate on the "fact_type" field.
func FactTypeHasPrefix(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldHasPrefix(FieldFactType, v))
}

// FactTypeHasSuffix applies the HasSuffix predicate on the "fact_type" field.
func FactTypeHasSuffix(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldHasSuffix(FieldFactType, v))
}

// FactTypeEqualFold applies the EqualFold predicate on the "fact_type" field.
func FactTypeEqualFold(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEqualFold(FieldFactType, v))
}

// FactTypeContainsFold applies the ContainsFold predicate on the "fact_type" field.
func FactTypeContainsFold(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldContainsFold(FieldFactType, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v float64) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v float64) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...float64) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...float64) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v float64) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v float64) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v float64) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v float64) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLTE(FieldValue, v))
}

// ValueIsNil applies the IsNil predicate on the "value" field.
func ValueIsNil() predicate.IntelFact {
	return predicate.IntelFact(sql.FieldIsNull(FieldValue))
}

// ValueNotNil applies the NotNil predicate on the "value" field.
func ValueNotNil() predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNotNull(FieldValue))
}

// UnitEQ applies the EQ predicate on the "unit" field.
func UnitEQ(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldUnit, v))
}

// UnitNEQ applies the NEQ predicate on the "unit" field.
func UnitNEQ(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNEQ(FieldUnit, v))
}

// UnitIn applies the In predicate on the "unit" field.
func UnitIn(vs ...string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldIn(FieldUnit, vs...))
}

// UnitNotIn applies the NotIn predicate on the "unit" field.
func UnitNotIn(vs ...string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNotIn(FieldUnit, vs...))
}

// UnitGT applies the GT predicate on the "unit" field.
func UnitGT(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGT(FieldUnit, v))
}

// UnitGTE applies the GTE predicate on the "unit" field.
func UnitGTE(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGTE(FieldUnit, v))
}

// UnitLT applies the LT predicate on the "unit" field.
func UnitLT(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLT(FieldUnit, v))
}

// UnitLTE applies the LTE predicate on the "unit" field.
func UnitLTE(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLTE(FieldUnit, v))
}

// UnitContains applies the Contains predicate on the "unit" field.
func UnitContains(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldContains(FieldUnit, v))
}

// UnitHasPrefix applies the HasPrefix predicate on the "unit" field.
func UnitHasPrefix(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldHasPrefix(FieldUnit, v))
}

// UnitHasSuffix applies the HasSuffix predicate on the "unit" field.
func UnitHasSuffix(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldHasSuffix(FieldUnit, v))
}

// UnitEqualFold applies the EqualFold predicate on the "unit" field.
func UnitEqualFold(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEqualFold(FieldUnit, v))
}

// UnitContainsFold applies the ContainsFold predicate on the "unit" field.
func UnitContainsFold(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldContainsFold(FieldUnit, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldContainsFold(FieldText, v))
}

// StartEQ applies the EQ predicate on the "start" field.
func StartEQ(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldStart, v))
}

// StartNEQ applies the NEQ predicate on the "start" field.
func StartNEQ(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNEQ(FieldStart, v))
}

// StartIn applies the In predicate on the "start" field.
func StartIn(vs ...int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldIn(FieldStart, vs...))
}

// StartNotIn applies the NotIn predicate on the "start" field.
func StartNotIn(vs ...int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNotIn(FieldStart, vs...))
}

// StartGT applies the GT predicate on the "start" field.
func StartGT(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGT(FieldStart, v))
}

// StartGTE applies the GTE predicate on the "start" field.
func StartGTE(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGTE(FieldStart, v))
}

// StartLT applies the LT predicate on the "start" field.
func StartLT(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLT(FieldStart, v))
}

// StartLTE applies the LTE predicate on the "start" field.
func StartLTE(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLTE(FieldStart, v))
}

// EndEQ applies the EQ predicate on the "end" field.
func EndEQ(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldEQ(FieldEnd, v))
}

// EndNEQ applies the NEQ predicate on the "end" field.
func EndNEQ(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNEQ(FieldEnd, v))
}

// EndIn applies the In predicate on the "end" field.
func EndIn(vs ...int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldIn(FieldEnd, vs...))
}

// EndNotIn applies the NotIn predicate on the "end" field.
func EndNotIn(vs ...int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldNotIn(FieldEnd, vs...))
}

// EndGT applies the GT predicate on the "end" field.
func EndGT(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGT(FieldEnd, v))
}

// EndGTE applies the GTE predicate on the "end" field.
func EndGTE(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldGTE(FieldEnd, v))
}

// EndLT applies the LT predicate on the "end" field.
func EndLT(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLT(FieldEnd, v))
}

// EndLTE applies the LTE predicate on the "end" field.
func EndLTE(v int) predicate.IntelFact {
	return predicate.IntelFact(sql.FieldLTE(FieldEnd, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntelFact) predicate.IntelFact {
	return predicate.IntelFact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntelFact) predicate.IntelFact {
	return predicate.IntelFact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntelFact) predicate.IntelFact {
	return predicate.IntelFact(sql.NotPredicates(p))
}
